project:
  type: book
  output-dir: output/pdf

book:
  title: "MLmetrics: Machine Learning for Econometricians"
  author: "Onno Kleen"
  output-file: "mlmetrics"
  chapters:
    - index.qmd
    - part: "Background"
      chapters:
        - information_theory.qmd
        - cross_validation.qmd
        - optimization.qmd
        - evaluating_distributions.qmd
    - part: "Neural Networks"
      chapters:
        - feed_forward_nns.qmd
        - recurrent_neural_networks.qmd
        - lstm_neural_networks.qmd
        - nn_example.qmd
        - distributions_via_nns.qmd
    - part: "Tree-Based Methods"
      chapters:
        - decision_trees.qmd
        - random_forests.qmd
        - gradient_boosting.qmd
        - adv_tree_based_methods.qmd
    - part: "Further Topics"
      chapters:
        - hpo.qmd
        - conformal_prediction.qmd
  appendices:
    - datasets.qmd
    - references.qmd

filters:
  - split-display-math.lua
  - pdf-hide-code.lua

format:
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    papersize: a4
    fontsize: 10pt
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    code-overflow: wrap
    include-in-header: pdf-header.tex
    geometry:
      - top=25mm
      - bottom=25mm
      - left=25mm
      - right=25mm

execute:
  cache: true
  echo: false
