<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>distributions_via_nns – MLmetrics: Machine Learning for Econometricians</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./decision_trees.html" rel="next">
<link href="./nn_example.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
(function () {
  function markInternalLinks() {
    const links = window.document.querySelectorAll("a[href]");

    for (const link of links) {
      if (link.origin !== window.location.origin) {
        continue;
      }

      link.classList.add("no-external");

      if (link.getAttribute("target") === "_blank") {
        link.removeAttribute("target");
      }

      const rel = link.getAttribute("rel");
      if (rel === "noopener") {
        link.removeAttribute("rel");
      }
    }
  }

  if (window.document.readyState === "loading") {
    window.document.addEventListener("DOMContentLoaded", markInternalLinks, {
      once: true,
    });
  } else {
    markInternalLinks();
  }
})();
</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./feed_forward_nns.html">Neural Networks</a></li><li class="breadcrumb-item"><a href="./distributions_via_nns.html">9. Distribution Modeling with Neural Networks</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About This Book</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./information_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Information Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cross_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Cross-Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Optimization for Machine Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluating_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Evaluating Predictive Distributions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Neural Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./feed_forward_nns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Feed-Forward Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recurrent_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Recurrent Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lstm_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. LSTM Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nn_example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Empirical Exercise: Networks for Time Series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions_via_nns.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">9. Distribution Modeling with Neural Networks</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Tree-Based Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Decision Trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random_forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11. Random Forests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gradient_boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12. Gradient Boosting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./adv_tree_based_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13. Advanced Tree-Based Methods</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Further Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hpo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14. Advanced Hyperparameter Optimization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conformal_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">15. Conformal Prediction</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Appendix</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-distnn" id="toc-sec-distnn" class="nav-link active" data-scroll-target="#sec-distnn"><span class="header-section-number">9</span> Distributional Neural Networks</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">9.1</span> Overview</a></li>
  <li><a href="#roadmap" id="toc-roadmap" class="nav-link" data-scroll-target="#roadmap"><span class="header-section-number">9.2</span> Roadmap</a></li>
  <li><a href="#sec-point-to-distnn" id="toc-sec-point-to-distnn" class="nav-link" data-scroll-target="#sec-point-to-distnn"><span class="header-section-number">9.3</span> From Point Forecasts to Predictive Distributions</a></li>
  <li><a href="#sec-distnn-training-scores" id="toc-sec-distnn-training-scores" class="nav-link" data-scroll-target="#sec-distnn-training-scores"><span class="header-section-number">9.4</span> Training Scores and Information Theory</a></li>
  <li><a href="#sec-hnn" id="toc-sec-hnn" class="nav-link" data-scroll-target="#sec-hnn"><span class="header-section-number">9.5</span> A Case Study: Hemisphere Neural Networks (HNN)</a></li>
  <li><a href="#sec-mdn" id="toc-sec-mdn" class="nav-link" data-scroll-target="#sec-mdn"><span class="header-section-number">9.6</span> Handling Complex Distributions: Mixture Density Networks (MDNs)</a></li>
  <li><a href="#sec-distnn-empirical" id="toc-sec-distnn-empirical" class="nav-link" data-scroll-target="#sec-distnn-empirical"><span class="header-section-number">9.7</span> Empirical Application: Predictive Distributions for SPY Returns</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9.8</span> Summary</a></li>
  <li><a href="#sec-distnn-exercises" id="toc-sec-distnn-exercises" class="nav-link" data-scroll-target="#sec-distnn-exercises"><span class="header-section-number">9.9</span> Exercises</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9.10</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./feed_forward_nns.html">Neural Networks</a></li><li class="breadcrumb-item"><a href="./distributions_via_nns.html">9. Distribution Modeling with Neural Networks</a></li></ol></nav></header>
<div class="alert alert-warning" role="alert" style="margin: 0; border-radius: 0; border: none; border-bottom: 1px solid #f0c842; text-align: center; font-size: 0.9em; padding: 0.5rem 1rem;">
  <strong>Under active development.</strong> A stable version is expected in November 2026. Feedback is welcome by <a href="mailto:kleen@ese.eur.nl">email</a> or via <a href="https://github.com/onnokleen/mlmetrics/issues">GitHub issues</a>.
</div>




<section id="sec-distnn" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Distributional Neural Networks</h1>
<section id="overview" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">9.1</span> Overview</h2>
<p>In many economic and financial applications, the signal-to-noise ratio is low, and decisions depend on the entire <strong>predictive distribution</strong> (also called a distribution forecast), not just a single point estimate. A central bank may care about downside inflation risk, a financial economist may care about the left tail of returns, and a risk manager may care about the probability of a large loss. A neural network (NN) trained with mean squared error (MSE) can be useful for estimating a conditional mean, <span class="math inline">\mathbb{E}[Y \mid \mathbf{X}=\mathbf{x}]</span>, but it does not by itself provide a calibrated predictive distribution.</p>
<p>Distributional neural networks address this by reframing the prediction problem. Instead of predicting a single number, the network predicts the parameters of a full conditional distribution. This connects the neural-network chapters back to the earlier chapters on information theory and evaluating predictive distributions: likelihood-based training corresponds to the log score, and alternative proper scoring rules such as the continuous ranked probability score (CRPS) can also be used when we want different sensitivity to tails or outliers. The broader literature on probabilistic forecasting and its evaluation is reviewed in <span class="citation" data-cites="GneitingKatzfuss2014">Gneiting and Katzfuss (<a href="#ref-GneitingKatzfuss2014" role="doc-biblioref">2014</a>)</span>.</p>
</section>
<section id="roadmap" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="roadmap"><span class="header-section-number">9.2</span> Roadmap</h2>
<ol type="1">
<li>We first contrast point-prediction networks with distributional networks.</li>
<li>We then connect negative log-likelihood training to cross-entropy, Kullback–Leibler (KL) divergence, and proper scoring rules.</li>
<li>Next, we study Gaussian distributional networks and the instability that arises when mean and variance are trained jointly.</li>
<li>We use Hemisphere Neural Networks (HNNs)—networks with a shared representation and separate mean and variance branches—as a case study for stabilizing distributional estimation in macro-financial settings.</li>
<li>We then turn to Mixture Density Networks (MDNs), which output the weights and component parameters of a mixture distribution, for richer conditional distributions.</li>
<li>We close with an empirical application—predictive distributions for next-day returns on the S&amp;P 500 exchange-traded fund, comparing Gaussian and Student-<span class="math inline">t</span> distributional networks with a constant Gaussian benchmark by proper scoring rules and calibration histograms on a held-out test period—followed by key takeaways, common pitfalls, and exercises.</li>
</ol>
</section>
<section id="sec-point-to-distnn" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-point-to-distnn"><span class="header-section-number">9.3</span> From Point Forecasts to Predictive Distributions</h2>
<p>As discussed in the <a href="./feed_forward_nns.html">Feed-Forward Neural Networks chapter</a>, a standard neural network trained with mean squared error produces a point forecast:</p>
<ul>
<li><strong>Traditional NN Output</strong>: <span class="math inline">\hat{y} = f_\theta(\mathbf{x})</span></li>
<li><strong>Distributional NN Output</strong>: <span class="math inline">p_\phi(y \mid \mathbf{x}) = p(y \mid \boldsymbol{\eta}_\phi(\mathbf{x}))</span>, where <span class="math inline">\boldsymbol{\eta}_\phi(\mathbf{x})</span> are the distribution parameters learned by the network.</li>
</ul>
<p>The distributional version replaces the scalar output by one or more output heads that map features into distributional parameters. For example, a Gaussian distributional network can produce a conditional mean and variance, while a Student-t network can additionally produce a degrees-of-freedom parameter. For the Gaussian case the parameter vector is <span class="math inline">\boldsymbol{\eta}_\phi(\mathbf{x})=(\mu(\mathbf{x}),\log\sigma^2(\mathbf{x}))</span> (equivalently <span class="math inline">(\mu(\mathbf{x}),\sigma^2(\mathbf{x}))</span>), so the scalar heads <span class="math inline">\mu_t</span> and <span class="math inline">\sigma_t^2</span> that appear later are recognizably its components.</p>
<p>The model is typically trained by maximizing the log-likelihood of the data, which is equivalent to minimizing the negative log-likelihood (NLL) loss:</p>
<div class="display-math-block">
<p><span class="math display">
L(\phi) = -\frac{1}{N}\sum_{i=1}^N \log p(y_i \mid \mathbf{x}_i; \boldsymbol{\eta}_\phi(\mathbf{x}_i)).
</span></p>
</div>
<p>Here, <span class="math inline">y_i</span> is the observed outcome, <span class="math inline">\mathbf{x}_i</span> is the feature vector, <span class="math inline">\boldsymbol{\eta}_\phi(\mathbf{x}_i)</span> denotes the distributional parameters implied by the neural network, and <span class="math inline">\phi</span> collects all trainable network weights. We write the objective as a sample average, matching the loss convention of the network chapters; the <span class="math inline">1/N</span> does not affect the minimizer.</p>
<p><strong>The same construction outside forecasting.</strong> Distributional output heads are not tied to predicting a future outcome. <span class="citation" data-cites="WeiJiang2025">Wei and Jiang (<a href="#ref-WeiJiang2025" role="doc-biblioref">2025</a>)</span> estimate the parameters of a structural econometric model by training a neural network on data simulated from the model itself: each training example pairs a parameter draw with the vector of data moments computed from the data set that this draw generated, and the network learns to map moments back to the parameter value behind them. Adding a second output head for a covariance matrix and training under the Gaussian negative log-likelihood above turns that point estimator into a distributional one. As in the quasi-likelihood argument of <a href="#sec-hnn" class="quarto-xref">Section&nbsp;9.5</a>, the Gaussian form of the loss is a device for targeting the first two moments and does not require that this conditional distribution be Gaussian.</p>
</section>
<section id="sec-distnn-training-scores" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sec-distnn-training-scores"><span class="header-section-number">9.4</span> Training Scores and Information Theory</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Information-theoretic interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>This NLL objective is the cross-entropy loss encountered in the <a href="./information_theory.html#sec-mle-kl-divergence">likelihood and KL-divergence discussion</a>: maximum likelihood estimation (MLE) minimizes sample cross-entropy. At the population level, expected conditional NLL differs from the expected conditional Kullback–Leibler (KL) divergence from the true conditional distribution to the model by a term that does not depend on the model parameters. Provided the relevant expectations are finite, both criteria therefore have the same population minimizer: the KL projection of the true conditional distribution onto the represented model family. Convergence of the empirical estimator to that target additionally requires identification within the density family, dependence-appropriate control of model complexity, a uniform law of large numbers, and sufficiently accurate optimization.</p>
<p>The score and the model family play different roles. A <em>realized</em> logarithmic score (LogS) is local: it evaluates only the density assigned to the outcome that occurred. Its <em>expected</em> value is strictly proper and is uniquely minimized by the true density when that density belongs to the admissible class and the expectations are finite. A Gaussian network can adjust only its represented conditional mean and variance functions, so its population target under misspecification is the closest represented Gaussian in KL divergence. Student-<span class="math inline">t</span> and mixture outputs enlarge the family of distributions to which the expected score can respond.</p>
</div>
</div>
<p>The same logic can be stated in the language of proper scoring rules. The negative log-likelihood corresponds to LogS: after observing <span class="math inline">y_i</span>, the model is rewarded for assigning high density to the realized outcome. Minimizing average NLL is therefore the training analogue of minimizing the out-of-sample log score; see the discussion of LogS and CRPS in the <a href="./evaluating_distributions.html">Evaluating Predictive Distributions chapter</a>.</p>
<p>Other proper scoring rules can also be used as training losses if they are computable and differentiable for the chosen predictive family. For example, the CRPS compares the full predictive cumulative distribution function (CDF) to the realized outcome. The choice of training score should match the forecasting object: log-likelihood is very sensitive to tail misspecification and extreme observations, while CRPS often behaves more like an integrated distributional error.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Question for Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question for Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>You fit a Gaussian distributional network by maximum likelihood for daily stock returns. The in-sample log-likelihood is high, but the realized probability integral transform (PIT) histogram, computed as in the <a href="./evaluating_distributions.html">predictive-distribution chapter</a>, is U-shaped. What does the U-shape suggest, and why does it not establish that conclusion by itself? Name two model failures that are both compatible with it, and propose one additional diagnostic that helps separate them.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggested Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A U-shaped PIT histogram is descriptive evidence consistent with underdispersion or tail misspecification: realizations appear in the predictive tails more often than the forecast expects. It is not proof, because a finite and serially dependent PIT sample can produce an irregular histogram through sampling variation. Two compatible model failures are a variance head that systematically understates conditional dispersion and a Gaussian family whose tails are too light. The standardized residuals <span class="math inline">(y_{t+1} - \hat{\mu}_t)/\hat{\sigma}_t</span> help separate them: a variance well above one supports broad scale underestimation, while a variance near one together with excess tail mass points toward shape misspecification. This diagnostic is not conclusive on its own, because state-dependent scale errors can average out; formal uniformity and conditional-calibration checks that account for serial dependence provide a stronger assessment. The Student-<span class="math inline">t</span> extension and the mixture density networks introduced later in the chapter provide natural robustness checks when the diagnostics point toward shape misspecification.</p>
</div>
</div>
</div>
<p>For dependent data, likelihood-based training does not by itself require an independence assumption. A correctly specified full conditional likelihood can be written as </p>
<div class="display-math-block">
<p><span class="math display">
\sum_{t=1}^{T} \log p_\phi(y_t \mid \mathcal{F}_{t-1}),
</span></p>
</div>
<p> where <span class="math inline">\mathcal{F}_{t-1}</span> is the information set available at the forecast origin. Equivalently, in one-step-ahead notation, the chain-rule likelihood is <span class="math inline">\sum_{t=0}^{T-1}\log p_\phi(y_{t+1}\mid\mathcal{F}_t)</span>. If the feature vector <span class="math inline">\mathbf{x}_t</span> is sufficient for the relevant past information, then <span class="math inline">p(y_{t+1}\mid\mathcal{F}_t)=p(y_{t+1}\mid\mathbf{x}_t)</span> and the network criterion is the full conditional likelihood. Otherwise, the same sum is better viewed as a conditional log-score, or quasi-likelihood, for the coarser distribution of <span class="math inline">Y_{t+1}</span> given <span class="math inline">\mathbf{x}_t</span>. Remaining serial dependence then matters for laws of large numbers, inference, and forecast evaluation even though it need not invalidate the forecasting target.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Link to Predictive-Distribution Evaluation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Training a distributional neural network and evaluating a distributional forecast are two sides of the same problem. During training, a proper scoring rule defines the loss. During evaluation, the same class of scores can be used out of sample to compare predictive distributions.</p>
</div>
</div>
</section>
<section id="sec-hnn" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-hnn"><span class="header-section-number">9.5</span> A Case Study: Hemisphere Neural Networks (HNN)</h2>
<p>A key challenge in distributional modeling is reliably estimating multiple distribution parameters at once. Consider the Gaussian case where we want to learn both the conditional mean and variance: </p>
<div class="display-math-block">
<p><span class="math display">
Y_{t+1}\mid\mathbf{X}_t=\mathbf{x}_t \sim \mathcal{N}\big(\mu_t, \sigma_t^2\big),\quad
\mu_t = f_{\phi_\mu}(\mathbf{x}_t),\ \ \sigma_t^2 = g_{\phi_\sigma}(\mathbf{x}_t)&gt;0,
</span></p>
</div>
<p> where <span class="math inline">Y_{t+1}</span> is the random outcome and <span class="math inline">\mathbf{X}_t</span> the random predictor vector with realization <span class="math inline">\mathbf{x}_t</span>, following the book’s case convention. Throughout this chapter, conditioning on <span class="math inline">\mathbf{x}_t</span> abbreviates conditioning on the event <span class="math inline">\mathbf{X}_t=\mathbf{x}_t</span>. The subscript <span class="math inline">t</span> on <span class="math inline">\mu_t</span> and <span class="math inline">\sigma_t^2</span> records the forecast origin: both are functions of <span class="math inline">\mathbf{x}_t</span> and describe the conditional distribution of <span class="math inline">Y_{t+1}</span>, consistent with the two-index convention <span class="math inline">\hat{y}_{t+1\mid t}</span> used elsewhere in the book. The per-time-step negative log-likelihood loss is, up to an additive constant, </p>
<div class="display-math-block">
<p><span class="math display">
\ell_{t+1}(\phi_\mu,\phi_\sigma)= \frac{1}{2}\log g_{\phi_\sigma}(\mathbf{x}_t) + \frac{(y_{t+1}-f_{\phi_\mu}(\mathbf{x}_t))^2}{2\,g_{\phi_\sigma}(\mathbf{x}_t)},
</span></p>
</div>
<p> the form analyzed in Exercise 9.1. Econometricians have met this objective before: it is exactly the Gaussian quasi-likelihood of a generalized autoregressive conditional heteroskedasticity (GARCH) model, with the parametric variance recursion replaced by the network map <span class="math inline">g_{\phi_\sigma}(\mathbf{x}_t)</span>. The quasi-maximum-likelihood theory of <span class="citation" data-cites="BollerslevWooldridge1992">Bollerslev and Wooldridge (<a href="#ref-BollerslevWooldridge1992" role="doc-biblioref">1992</a>)</span> also explains why this objective is a sensible target even when the true conditional distribution is not Gaussian: the criterion identifies the conditional mean and the conditional variance as long as those two moments are correctly specified.</p>
<p>In overparameterized models, jointly training the mean and variance heads by maximum likelihood can be unstable. The model can achieve a low loss by letting the mean network overfit, which drives residuals and therefore the fitted variance toward zero, or by letting the variance network absorb too much variation. This is a distributional overfitting problem: the model has to learn both the location and the uncertainty, and the two tasks can interfere with each other.</p>
<p>The <strong>HNN architecture</strong>, proposed by <span class="citation" data-cites="GouletCoulombeFrenetteKlieber2026">Goulet Coulombe, Frenette, and Klieber (<a href="#ref-GouletCoulombeFrenetteKlieber2026" role="doc-biblioref">2026</a>)</span>, is designed to stabilize this process.</p>
<p><strong>HNN architecture.</strong> The architecture splits the network after a shared <em>common core</em> into two specialized <em>hemispheres</em>. The core is a set of shared layers that learn a common representation of the inputs; because latent drivers can influence both moments through this shared representation, the two heads draw on common predictors—a <em>representation-level</em> link between mean and variance. Genuine autoregressive conditional heteroskedasticity (ARCH)-type dynamics, in which the variance is driven by past innovations, or volatility-in-mean effects, in which the conditional variance enters the mean equation, do not follow from shared layers alone: they arise only if the corresponding variables—lagged residuals, lagged variance, or an explicit cross-head connection—enter the model, as in the Temporal Dynamics extension below. The mean hemisphere is a dedicated stack of layers ending in a linear output head that predicts <span class="math inline">\mu_t</span>. The variance hemisphere mirrors it with a <code>softplus</code> output head—the softplus transform <span class="math inline">\zeta(z)=\log(1+e^{z})&gt;0</span> (introduced in the <a href="./feed_forward_nns.html#sec-def-multilayer-nn">Feed-Forward Neural Networks chapter</a>) maps any real pre-activation to a positive value—so that the predicted variance <span class="math inline">\sigma_t^2</span> is always positive.</p>
<p>The resulting architecture is illustrated in <a href="#fig-hnn" class="quarto-xref">Figure&nbsp;9.1</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-hnn" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/hemispheres.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="404">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Architecture of a Hemisphere Neural Network. The input vector <span class="math inline">\mathbf{x}_t</span> (top) passes through a shared common core of <span class="math inline">L_c</span> layers, after which the network splits into two dedicated branches: a mean hemisphere of <span class="math inline">L_m</span> layers ending in a linear head that outputs <span class="math inline">\mu_t = f_{\phi_\mu}(\mathbf{x}_t)</span> (lower left), and a variance hemisphere of <span class="math inline">L_v</span> layers ending in a softplus head that outputs <span class="math inline">\sigma_t^2 = g_{\phi_\sigma}(\mathbf{x}_t) &gt; 0</span> (lower right). Arrows show the flow of computation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>When <span class="math inline">\mathbf{x}_t</span> contains relevant lagged shocks or variance measures, the network can learn reactive volatility in which variance rises after shocks, as in GARCH-type dynamics. With genuine leading indicators known at the forecast origin, it can instead learn proactive volatility in which predicted variance rises before the realization. The econometric intuition is that some variables may move the conditional mean, some may move conditional uncertainty, and some may affect both.</p>
<p><strong>Stabilizing joint MLE in practice.</strong></p>
<p>The HNN framework introduces three key ingredients to discipline the unstable MLE procedure:</p>
<ol type="1">
<li><p><strong>Volatility-emphasis constraint.</strong> If <span class="math inline">Y_{t+1}</span> has a finite second moment, the population law of total variance gives </p>
<div class="display-math-block">
<p><span class="math display">
\operatorname{Var}(Y_{t+1}) = \mathbb{E}\bigl[\operatorname{Var}(Y_{t+1}\mid \mathbf{X}_t)\bigr] + \operatorname{Var}\bigl(\mathbb{E}[Y_{t+1}\mid \mathbf{X}_t]\bigr),
</span></p>
</div>
<p> where the outer expectation and variance average over the random predictor vector <span class="math inline">\mathbf{X}_t</span>. Thus, the expected conditional variance is strictly less than the unconditional variance whenever the conditional mean varies with the predictors. Under stationarity and ergodicity, time averages can estimate these population moments. In finite samples, HNN uses the corresponding empirical relation as a regularization device: </p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{T}\sum_{t=1}^{T} g_{\phi_\sigma}(\mathbf{x}_t) \approx \kappa\cdot \operatorname{Var}(Y_{t+1}),
\qquad 0 &lt; \kappa &lt; 1.
</span></p>
</div>
<p> The multiplier <span class="math inline">\kappa</span> is calibrated from <em>out-of-bag</em> residuals of a non-distributional baseline—residuals computed for each observation from fits whose training draws exclude it, the device used in the <a href="./evaluating_distributions.html#sec-eval-dist-empirical">empirical application of the predictive-distribution chapter</a> and treated fully in the <a href="./random_forests.html">random forests chapter</a>. The constraint regularizes the variance hemisphere away from zero and prevents it from absorbing predictable variation that should be explained by the mean hemisphere.</p></li>
<li><p><strong>Blocked subsampling (time-aware bagging).</strong> Blocked subsampling trains the model repeatedly on different time blocks (“bags”). It adapts <em>bagging</em>—short for bootstrap aggregation—to time-series data; the <a href="./random_forests.html">random forests chapter</a> introduces bagging in full. Predictions for <span class="math inline">\mu_t</span> and <span class="math inline">\sigma_t^2</span> are averaged only across fits for which time <span class="math inline">t</span> was held out of the training sample. Averaging reduces variation across training samples and network initializations.</p></li>
<li><p><strong>Blocked out-of-bag recalibration.</strong> After estimation, the fitted variance path is recalibrated against out-of-bag squared forecast errors—errors from fits that did not see the corresponding observations—so that predicted uncertainty is disciplined by prediction errors rather than by in-sample residuals <span class="citation" data-cites="GouletCoulombeFrenetteKlieber2026">(<a href="#ref-GouletCoulombeFrenetteKlieber2026" role="doc-biblioref">Goulet Coulombe, Frenette, and Klieber 2026</a>)</span>. Mechanically, the log out-of-bag squared errors are regressed on the log fitted variance, so the recalibration adjusts both the level and, through the slope, the amplitude of the variance path, damping its variation when the raw variance head has overfit. This recalibration is distinct from the subsampling in ingredient 2 that generates the out-of-bag predictions.</p></li>
</ol>
<p>Together, these three ingredients provide the stabilization: dedicated output heads alone do not prevent joint-likelihood degeneracy.</p>
<p><strong>Beyond Gaussian outputs.</strong> The hemisphere approach can be extended to a location-scale Student-<span class="math inline">t</span> output by adding a third hemisphere for the degrees-of-freedom parameter, <span class="math inline">\nu</span>. Write <span class="math inline">Y=\mu+sZ</span> with <span class="math inline">Z\sim t_\nu</span>. The density is defined for <span class="math inline">\nu&gt;0</span>, its mean is finite only for <span class="math inline">\nu&gt;1</span>, and its variance is finite only for <span class="math inline">\nu&gt;2</span>. Requiring <span class="math inline">\nu&gt;2</span>, for instance through <span class="math inline">\nu=2+\zeta(z)</span>, guarantees finite variance, but <span class="math inline">s^2</span> is not that variance: </p>
<div class="display-math-block">
<p><span class="math display">
\operatorname{Var}(Y)=s^2\frac{\nu}{\nu-2}.
</span></p>
</div>
<p> If an existing variance head <span class="math inline">v(\mathbf{x}_t)</span>—the role played by <span class="math inline">g_{\phi_\sigma}(\mathbf{x}_t)</span> above—is meant to retain the interpretation of a conditional variance, the Student-<span class="math inline">t</span> scale must satisfy <span class="math inline">s^2(\mathbf{x}_t)=v(\mathbf{x}_t)(\nu-2)/\nu</span>.</p>
<p><strong>Temporal dynamics.</strong> Lagged outcomes, innovations, or squared residuals can enter <span class="math inline">\mathbf{x}_t</span> to capture GARCH-type effects directly. For more complex sequences, the common core could be a Long Short-Term Memory (LSTM) network.</p>
</section>
<section id="sec-mdn" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="sec-mdn"><span class="header-section-number">9.6</span> Handling Complex Distributions: Mixture Density Networks (MDNs)</h2>
<p>For distributions that are skewed, multimodal, or heavier-tailed over empirically relevant ranges than a single Gaussian, one parametric component can be too restrictive. <strong>MDNs</strong>, proposed by <span class="citation" data-cites="Bishop1994MDN">Bishop (<a href="#ref-Bishop1994MDN" role="doc-biblioref">1994</a>)</span>, address this by modeling the conditional distribution as a mixture of simpler ones, such as Gaussians: </p>
<div class="display-math-block">
<p><span class="math display">
p(y \mid \mathbf{x})=\sum_{k=1}^K \pi_k(\mathbf{x})\,\mathcal{N}\!\big(y;\,\mu_k(\mathbf{x}),\,\sigma_k^2(\mathbf{x})\big).
</span></p>
</div>
<p>A finite Gaussian mixture can be substantially more leptokurtic than one Gaussian over the range relevant for an application, but its asymptotic tails remain Gaussian and are dominated by the component with the largest variance. It is therefore not fat-tailed in the strict power-law sense.</p>
<p>The network has three output heads to predict the parameters for all <span class="math inline">K</span> components:</p>
<ul>
<li><strong>Mixing Weights <span class="math inline">\pi_k(\mathbf{x})</span></strong>: A <code>softmax</code> layer over the <span class="math inline">K</span> components, <span class="math inline">\pi_k(\mathbf{x})=\exp(a_k(\mathbf{x}))/\sum_{j=1}^K \exp(a_j(\mathbf{x}))</span>. Here, <span class="math inline">k = 1, \ldots, K</span> indexes the mixture components and <span class="math inline">K</span> is their number; the transform yields <span class="math inline">\pi_k&gt;0</span> and <span class="math inline">\sum_{k=1}^K\pi_k=1</span>.</li>
<li><strong>Means <span class="math inline">\mu_k(\mathbf{x})</span></strong>: A linear layer.</li>
<li><strong>Standard Deviations <span class="math inline">\sigma_k(\mathbf{x})</span></strong>: A <code>softplus</code> layer ensures positivity.</li>
</ul>
<p>MDNs are particularly useful for modeling phenomena whose predictive distributions are multimodal. Examples include:</p>
<ul>
<li>Multimodal inflation distributions (e.g., a low-inflation versus a high-inflation regime).</li>
<li>Asset returns with regime-switching behavior.</li>
<li>Labor market dynamics that might feature multiple equilibria.</li>
</ul>
<p>MDN training has two transparent difficulties <span class="citation" data-cites="Bishop1994MDN">(<a href="#ref-Bishop1994MDN" role="doc-biblioref">Bishop 1994</a>)</span>. First, component labels are not identified and a subset of components can receive almost all the weight. Second, the likelihood is unbounded if a sufficiently flexible component centers on an observation while its scale approaches zero and its mixing weight does not vanish quickly enough. Careful initialization, penalties on extreme mixing weights, and a positive scale floor are possible safeguards, although the latter two change the criterion or parameter space.</p>
<p>A different route to flexible distributional output is to train separate network heads with the quantile, or pinball, loss </p>
<div class="display-math-block">
<p><span class="math display">
\rho_\tau(y-q)=(y-q)\bigl(\tau-\mathbf{1}\{y&lt;q\}\bigr),
\qquad \tau\in(0,1),
</span></p>
</div>
<p> at several quantile levels. The conditional expected loss is minimized by a conditional <span class="math inline">\tau</span>-quantile <span class="math inline">q_\tau(\mathbf{x})</span>. Unless the architecture or loss imposes an ordering restriction, the estimated quantiles can cross. A parametric density head avoids crossing because all quantiles come from one cumulative distribution function.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Econometric Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>An MDN is a flexible way to approximate a conditional density with latent regimes. It should not automatically be interpreted as a structural regime-switching model: the mixture components are learned predictive components unless additional economic restrictions are imposed.</p>
</div>
</div>
</section>
<section id="sec-distnn-empirical" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="sec-distnn-empirical"><span class="header-section-number">9.7</span> Empirical Application: Predictive Distributions for SPY Returns</h2>
<p>The Overview motivated distributional networks with a financial economist who cares about the left tail of returns. We now construct such a forecast. The realized-variance illustration of the <a href="./nn_example.html">previous chapter</a> produced point forecasts of daily log realized variance for SPY, the S&amp;P 500 exchange-traded fund. Here the same realized-variance information becomes the input to a predictive distribution for the next day’s SPY return. Returns are the classic setting for conditional heteroskedasticity: at a daily horizon their conditional mean is hard to predict, whereas their conditional variance moves with recent volatility, as in GARCH models. A predictive distribution for returns should therefore draw most of its value from a scale that responds to the inputs and, if large moves are more frequent than a Gaussian distribution allows, from its tails.</p>
<p><strong>Target and information set.</strong> Let <span class="math inline">r_{t+1}</span> denote the SPY log return, in percent, from the close of trading day <span class="math inline">t</span> to the close of trading day <span class="math inline">t+1</span>, and let <span class="math inline">R_{t+1}</span> denote the corresponding random variable. The forecast origin is the close of day <span class="math inline">t</span>. The input vector contains the three log heterogeneous autoregressive (HAR) components of <span class="citation" data-cites="CorsiHAR2009">Corsi (<a href="#ref-CorsiHAR2009" role="doc-biblioref">2009</a>)</span> used in the previous chapter, all known at that close: </p>
<div class="display-math-block">
<p><span class="math display">
\mathbf{x}_t=\Bigl(\log RV_t,\ \log\bigl(\tfrac{1}{5}\textstyle\sum_{j=0}^{4} RV_{t-j}\bigr),\ \log\bigl(\tfrac{1}{21}\textstyle\sum_{j=0}^{20} RV_{t-j}\bigr)\Bigr)',
</span></p>
</div>
<p> where <span class="math inline">RV_t</span> is the realized variance of day <span class="math inline">t</span>: the sum of squared 5-minute log returns over regular trading hours, after multiplying returns by 100, so that its units are squared percentage points. The inputs measure price variation up to day <span class="math inline">t</span>, whereas <span class="math inline">r_{t+1}</span> refers to day <span class="math inline">t+1</span> and also contains the overnight price change from the close of day <span class="math inline">t</span> to the open of day <span class="math inline">t+1</span>, which realized variance never covers. The inputs are therefore predictors of the return distribution rather than measurements of its variance: each model must learn how <span class="math inline">\mathbf{x}_t</span> maps into the location, scale, and tail shape of <span class="math inline">R_{t+1}</span> given <span class="math inline">\mathbf{x}_t</span>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p><strong>Sample split.</strong> We keep the test years of the previous chapter: the test block contains the 502 return targets dated in 2023 and 2024. All earlier targets form a single estimation sample. Because all hyperparameters are fixed in advance, no validation block is needed. Each model is fitted once on the estimation sample and held fixed throughout the test block; unlike the previous chapter, we do not refit at the start of 2024.</p>
<p><strong>Three predictive distributions.</strong> We compare three ways of forming a predictive distribution for <span class="math inline">R_{t+1}</span> given <span class="math inline">\mathbf{x}_t</span>: a benchmark that ignores the inputs and two distributional networks.</p>
<ol type="1">
<li>The <strong>constant Gaussian</strong> forecast is <span class="math inline">\mathcal{N}(\bar r, s_r^2)</span> on every test day, where <span class="math inline">\bar r</span> and <span class="math inline">s_r^2</span> are the estimation-sample mean and the maximum-likelihood variance of the returns (the sum of squared deviations divided by the number of observations). It ignores <span class="math inline">\mathbf{x}_t</span>.</li>
<li>The <strong>Gaussian HAR-FNN</strong> is a feed-forward neural network (FNN) with one hidden layer of 32 softplus units, a linear mean head <span class="math inline">\mu_\phi(\mathbf{x}_t)</span>, and an unconstrained variance pre-activation <span class="math inline">a_\phi(\mathbf{x}_t)</span>. The predictive variance is <span class="math inline">\sigma_\phi^2(\mathbf{x}_t)=c+\zeta(a_\phi(\mathbf{x}_t))</span>, where <span class="math inline">\zeta</span> is the softplus function and <span class="math inline">c&gt;0</span> is a small floor.</li>
<li>The <strong>Student-<span class="math inline">t</span> HAR-FNN</strong> adds the third output head for the degrees of freedom proposed in <a href="#sec-hnn" class="quarto-xref">Section&nbsp;9.5</a>. Its second head now delivers the squared scale, <span class="math inline">s_\phi^2(\mathbf{x}_t)=c+\zeta(a_\phi(\mathbf{x}_t))</span>, and its third head a pre-activation <span class="math inline">b_\phi(\mathbf{x}_t)</span> with <span class="math inline">\nu_\phi(\mathbf{x}_t)=2+\zeta(b_\phi(\mathbf{x}_t))&gt;2</span>. The degrees of freedom may therefore vary with the inputs. As in <a href="#sec-hnn" class="quarto-xref">Section&nbsp;9.5</a>, the implied conditional variance is <span class="math inline">s_\phi^2(\mathbf{x}_t)\,\nu_\phi(\mathbf{x}_t)/(\nu_\phi(\mathbf{x}_t)-2)</span>, not <span class="math inline">s_\phi^2(\mathbf{x}_t)</span>.</li>
</ol>
<p>The unconstrained outputs <span class="math inline">(\mu_\phi,a_\phi)</span> and <span class="math inline">(\mu_\phi,a_\phi,b_\phi)</span> play the role of the parameter vector <span class="math inline">\boldsymbol{\eta}_\phi(\mathbf{x}_t)</span> of <a href="#sec-point-to-distnn" class="quarto-xref">Section&nbsp;9.3</a> before the positivity transformations are applied. In each network the heads share one hidden representation, in the spirit of the HNN common core in <a href="#sec-hnn" class="quarto-xref">Section&nbsp;9.5</a>, but neither network uses the volatility-emphasis constraint, blocked subsampling, or out-of-bag recalibration. Each network minimizes its own negative log-likelihood. We evaluate all three forecasts on the test block with LogS, CRPS, and PIT histograms, as in the <a href="./evaluating_distributions.html#sec-eval-dist-empirical">empirical application of the predictive-distribution chapter</a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">"KERAS_BACKEND"</span>] <span class="op">=</span> <span class="st">"tensorflow"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">"TF_CPP_MIN_LOG_LEVEL"</span>] <span class="op">=</span> <span class="st">"3"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> keras</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tensorflow <span class="im">as</span> tf</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> keras <span class="im">import</span> layers, ops</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> special</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm, t <span class="im">as</span> student_t</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> properscoring <span class="im">as</span> ps</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>random.seed(<span class="dv">0</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">0</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>keras.utils.set_random_seed(<span class="dv">0</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>spy <span class="op">=</span> (</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    pd.read_csv(<span class="st">"data/taq_spy/SPY_daily_measures.csv"</span>, parse_dates<span class="op">=</span>[<span class="st">"date"</span>])</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    .sort_values(<span class="st">"date"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    .loc[:, [<span class="st">"date"</span>, <span class="st">"close_taq"</span>, <span class="st">"rv"</span>]]</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    .reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> spy[<span class="st">"date"</span>].is_monotonic_increasing <span class="kw">and</span> <span class="kw">not</span> spy[<span class="st">"date"</span>].duplicated().<span class="bu">any</span>()</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> (spy[<span class="st">"rv"</span>] <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">all</span>() <span class="kw">and</span> (spy[<span class="st">"close_taq"</span>] <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">all</span>()</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>window <span class="op">=</span> <span class="dv">22</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_log_har_returns(rv_arr, close_arr):</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Row for origin `end`: log-HAR inputs through day `end`, percent log return to close `end + 1`."""</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    X, r, idx <span class="op">=</span> [], [], []</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> end <span class="kw">in</span> <span class="bu">range</span>(window <span class="op">-</span> <span class="dv">1</span>, <span class="bu">len</span>(rv_arr) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>        X.append(np.log([</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>            rv_arr[end],</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>            rv_arr[end <span class="op">-</span> <span class="dv">4</span> : end <span class="op">+</span> <span class="dv">1</span>].mean(),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>            rv_arr[end <span class="op">-</span> <span class="dv">20</span> : end <span class="op">+</span> <span class="dv">1</span>].mean(),</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>        ]))</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>        r.append(<span class="dv">100</span> <span class="op">*</span> np.log(close_arr[end <span class="op">+</span> <span class="dv">1</span>] <span class="op">/</span> close_arr[end]))</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>        idx.append(end <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.asarray(X), np.asarray(r), np.asarray(idx)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>X, r, target_idx <span class="op">=</span> make_log_har_returns(spy[<span class="st">"rv"</span>].to_numpy(), spy[<span class="st">"close_taq"</span>].to_numpy())</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>dates <span class="op">=</span> spy.loc[target_idx, <span class="st">"date"</span>].reset_index(drop<span class="op">=</span><span class="va">True</span>)  <span class="co"># target dates</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>in_est <span class="op">=</span> (dates <span class="op">&lt;</span> <span class="st">"2023-01-01"</span>).to_numpy()</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>X_est, r_est <span class="op">=</span> X[in_est], r[in_est]</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>X_te, r_te <span class="op">=</span> X[<span class="op">~</span>in_est], r[<span class="op">~</span>in_est]</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>dates_te <span class="op">=</span> dates[<span class="op">~</span>in_est].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>x_center, x_scale <span class="op">=</span> X_est.mean(axis<span class="op">=</span><span class="dv">0</span>), X_est.std(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>r_center, r_scale <span class="op">=</span> <span class="bu">float</span>(r_est.mean()), <span class="bu">float</span>(r_est.std())  <span class="co"># r-bar and s_r</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>Xs_est, Xs_te <span class="op">=</span> (X_est <span class="op">-</span> x_center) <span class="op">/</span> x_scale, (X_te <span class="op">-</span> x_center) <span class="op">/</span> x_scale</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"estimation targets: </span><span class="sc">{</span>in_est<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(</span><span class="sc">{</span>dates[in_est]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">.</span>date()<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>dates[in_est]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>]<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>estimation targets: 1992 (2015-02-04 to 2022-12-30)</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"test targets: </span><span class="sc">{</span>(<span class="op">~</span>in_est)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>dates_te<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">.</span>date()<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>dates_te<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>]<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>test targets: 502 (2023-01-03 to 2024-12-31)</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"standard deviation of returns: estimation </span><span class="sc">{</span>r_est<span class="sc">.</span>std()<span class="sc">:.2f}</span><span class="ss">, test </span><span class="sc">{</span>r_te<span class="sc">.</span>std()<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>standard deviation of returns: estimation 1.19, test 0.81</code></pre>
</div>
</div>
<p>The <code>make_log_har_returns</code> helper builds the same three HAR averages as the <a href="./nn_example.html">Chapter 8 illustration</a> and takes their logarithms. Row <span class="math inline">t</span> of <code>X</code> holds <span class="math inline">\mathbf{x}_t</span>, and the matching entry of <code>r</code> holds <span class="math inline">r_{t+1}</span>, so both arrays are indexed by forecast origin while <code>dates</code> records the target date. The inputs are standardized with estimation-sample constants only, so no test-block information enters the scaling. The target needs no standardization, because percent returns already have a mean close to zero and a standard deviation of order one. The printed standard deviations already hint at a problem for the constant Gaussian benchmark: returns in the 2023–2024 test block were considerably less volatile than in the estimation sample, which contains the turbulent years 2020 and 2022.</p>
<p>The constant Gaussian benchmark needs no neural network: it reuses the scaling constants <span class="math inline">\bar r</span> and <span class="math inline">s_r</span> on every test day.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mu_const_te <span class="op">=</span> np.full_like(r_te, r_center)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sigma_const_te <span class="op">=</span> np.full_like(r_te, r_scale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The two distributional networks share one architecture and differ only in the number of output heads and in the negative log-likelihood they minimize. The Gaussian loss is the per-observation NLL of <a href="#sec-hnn" class="quarto-xref">Section&nbsp;9.5</a>, with the smooth variance floor that prevents a degenerate density when residuals are near zero (the pathology analyzed in Exercise 9.1). Exercise 9.1 derives the optimum under a hard inequality constraint; the implementation uses a smooth map because applying a hard maximum to a network output would give a zero derivative whenever the floor binds. The Student-<span class="math inline">t</span> loss is the negative logarithm of the location-scale Student-<span class="math inline">t</span> density, </p>
<div class="display-math-block">
<p><span class="math display">
-\log\Gamma\Bigl(\frac{\nu+1}{2}\Bigr)+\log\Gamma\Bigl(\frac{\nu}{2}\Bigr)+\frac{1}{2}\log(\nu\pi s^2)+\frac{\nu+1}{2}\log\Bigl(1+\frac{(r-\mu)^2}{\nu s^2}\Bigr),
</span></p>
</div>
<p> evaluated at the network outputs <span class="math inline">(\mu,s^2,\nu)</span> for each observation. Keras’s backend-independent <code>ops</code> module has no log-gamma function, so the Student-<span class="math inline">t</span> loss calls TensorFlow’s <code>tf.math.lgamma</code> directly.</p>
<p>We fix all hyperparameters <em>a priori</em>—32 hidden units, learning rate <span class="math inline">10^{-3}</span>, 200 epochs, and batch size 32—without a data-driven tuning step. The results below describe one fixed configuration and a single training run per network with a fixed random seed, not a stable architecture ranking; repeated seeds or resamples would be needed to quantify optimization variability.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>VAR_FLOOR <span class="op">=</span> <span class="fl">1e-3</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gaussian_nll(y_true, y_pred):</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> y_pred[..., <span class="dv">0</span>:<span class="dv">1</span>]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    var <span class="op">=</span> VAR_FLOOR <span class="op">+</span> ops.softplus(y_pred[..., <span class="dv">1</span>:<span class="dv">2</span>])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">0.5</span> <span class="op">*</span> (ops.log(<span class="fl">2.0</span> <span class="op">*</span> np.pi <span class="op">*</span> var) <span class="op">+</span> ops.square(y_true <span class="op">-</span> mu) <span class="op">/</span> var)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> student_t_nll(y_true, y_pred):</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> y_pred[..., <span class="dv">0</span>:<span class="dv">1</span>]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    scale2 <span class="op">=</span> VAR_FLOOR <span class="op">+</span> ops.softplus(y_pred[..., <span class="dv">1</span>:<span class="dv">2</span>])</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    nu <span class="op">=</span> <span class="fl">2.0</span> <span class="op">+</span> ops.softplus(y_pred[..., <span class="dv">2</span>:<span class="dv">3</span>])</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    log_density <span class="op">=</span> (</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>        tf.math.lgamma((nu <span class="op">+</span> <span class="fl">1.0</span>) <span class="op">/</span> <span class="fl">2.0</span>) <span class="op">-</span> tf.math.lgamma(nu <span class="op">/</span> <span class="fl">2.0</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> ops.log(nu <span class="op">*</span> np.pi <span class="op">*</span> scale2)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> (nu <span class="op">+</span> <span class="fl">1.0</span>) <span class="op">*</span> ops.log1p(ops.square(y_true <span class="op">-</span> mu) <span class="op">/</span> (nu <span class="op">*</span> scale2))</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_density</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_dist_har_fnn(n_heads, loss, n_neurons<span class="op">=</span><span class="dv">32</span>, learning_rate<span class="op">=</span><span class="fl">1e-3</span>):</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    inputs <span class="op">=</span> keras.Input(shape<span class="op">=</span>(<span class="dv">3</span>,))</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> layers.Dense(n_neurons, activation<span class="op">=</span><span class="st">"softplus"</span>)(inputs)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    heads <span class="op">=</span> [layers.Dense(<span class="dv">1</span>)(h) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_heads)]</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> keras.Model(inputs, layers.Concatenate()(heads))</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">compile</span>(loss<span class="op">=</span>loss, optimizer<span class="op">=</span>keras.optimizers.Adam(learning_rate))</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softplus(a):</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.logaddexp(<span class="fl">0.0</span>, a)</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>gauss_model <span class="op">=</span> make_dist_har_fnn(n_heads<span class="op">=</span><span class="dv">2</span>, loss<span class="op">=</span>gaussian_nll)</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> gauss_model.fit(Xs_est, r_est.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), epochs<span class="op">=</span><span class="dv">200</span>, batch_size<span class="op">=</span><span class="dv">32</span>, verbose<span class="op">=</span><span class="dv">0</span>, shuffle<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> gauss_model.predict(Xs_te, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>mu_gauss_te <span class="op">=</span> pred[:, <span class="dv">0</span>]</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>sigma_gauss_te <span class="op">=</span> np.sqrt(VAR_FLOOR <span class="op">+</span> softplus(pred[:, <span class="dv">1</span>]))</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>t_model <span class="op">=</span> make_dist_har_fnn(n_heads<span class="op">=</span><span class="dv">3</span>, loss<span class="op">=</span>student_t_nll)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> t_model.fit(Xs_est, r_est.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), epochs<span class="op">=</span><span class="dv">200</span>, batch_size<span class="op">=</span><span class="dv">32</span>, verbose<span class="op">=</span><span class="dv">0</span>, shuffle<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> t_model.predict(Xs_te, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>mu_t_te <span class="op">=</span> pred[:, <span class="dv">0</span>]</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>s_t_te <span class="op">=</span> np.sqrt(VAR_FLOOR <span class="op">+</span> softplus(pred[:, <span class="dv">1</span>]))</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>nu_t_te <span class="op">=</span> <span class="fl">2.0</span> <span class="op">+</span> softplus(pred[:, <span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Because the networks are trained directly on percent returns, their outputs need no back-transformation: <span class="math inline">\mu_\phi(\mathbf{x}_t)</span>, <span class="math inline">\sigma_\phi^2(\mathbf{x}_t)</span>, and <span class="math inline">s_\phi^2(\mathbf{x}_t)</span> are already on the percent scale, and the variance floor <span class="math inline">c=10^{-3}</span> corresponds to a standard deviation of only about 0.03 percent. A nonlinear transformation of the target would require more than rescaling. Had we modeled <span class="math inline">\log RV_{t+1}</span> as in the previous chapter, a Gaussian predictive density with mean <span class="math inline">m</span> and variance <span class="math inline">v</span> on the log scale would imply a lognormal density for <span class="math inline">RV_{t+1}</span>, whose mean is <span class="math inline">\exp(m+v/2)</span> rather than <span class="math inline">\exp(m)</span>; the density itself changes according to the change-of-variables formula. Scores are therefore comparable only when all forecasts and outcomes are expressed on one common scale, here the percent return. Under the LogS and CRPS, multiplying forecasts and outcomes by the same positive factor preserves model rankings <span class="citation" data-cites="Kleen2024">(<a href="#ref-Kleen2024" role="doc-biblioref">Kleen 2024</a>)</span>, and shifting both by a common constant leaves the scores unchanged; rescaling does, however, change absolute score levels.</p>
<p>Scoring the Student-<span class="math inline">t</span> forecasts needs one more ingredient. The Gaussian CRPS is available in <code>properscoring</code>, whereas the Student-<span class="math inline">t</span> CRPS uses the closed form for <span class="math inline">\nu&gt;1</span> reported by <span class="citation" data-cites="JordanKruegerLerch2019">Jordan, Krüger, and Lerch (<a href="#ref-JordanKruegerLerch2019" role="doc-biblioref">2019</a>)</span>. The table lists each forecast’s average LogS and CRPS over the 502 test days, together with its largest single-day LogS, the date of that day, and its CRPS on that day.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> crps_student_t(r, mu, s, nu):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Closed-form CRPS of a location-scale Student-t forecast, valid for nu &gt; 1."""</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> (r <span class="op">-</span> mu) <span class="op">/</span> s</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    const <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> np.sqrt(nu) <span class="op">*</span> special.beta(<span class="fl">0.5</span>, nu <span class="op">-</span> <span class="fl">0.5</span>) <span class="op">/</span> ((nu <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> special.beta(<span class="fl">0.5</span>, nu <span class="op">/</span> <span class="dv">2</span>) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> s <span class="op">*</span> (z <span class="op">*</span> (<span class="dv">2</span> <span class="op">*</span> student_t.cdf(z, nu) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                <span class="op">+</span> <span class="dv">2</span> <span class="op">*</span> student_t.pdf(z, nu) <span class="op">*</span> (nu <span class="op">+</span> z<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> (nu <span class="op">-</span> <span class="dv">1</span>) <span class="op">-</span> const)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>forecasts <span class="op">=</span> {</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Constant Gaussian"</span>: (<span class="st">"gaussian"</span>, mu_const_te, sigma_const_te, <span class="va">None</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Gaussian HAR-FNN"</span>: (<span class="st">"gaussian"</span>, mu_gauss_te, sigma_gauss_te, <span class="va">None</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Student-t HAR-FNN"</span>: (<span class="st">"student_t"</span>, mu_t_te, s_t_te, nu_t_te),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>rows, pit <span class="op">=</span> [], {}</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (family, mu, s, nu) <span class="kw">in</span> forecasts.items():</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> family <span class="op">==</span> <span class="st">"gaussian"</span>:</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        logs <span class="op">=</span> <span class="op">-</span>norm.logpdf(r_te, mu, s)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>        crps <span class="op">=</span> ps.crps_gaussian(r_te, mu<span class="op">=</span>mu, sig<span class="op">=</span>s)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        pit[name] <span class="op">=</span> norm.cdf(r_te, mu, s)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>        logs <span class="op">=</span> <span class="op">-</span>(student_t.logpdf((r_te <span class="op">-</span> mu) <span class="op">/</span> s, nu) <span class="op">-</span> np.log(s))</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>        crps <span class="op">=</span> crps_student_t(r_te, mu, s, nu)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        pit[name] <span class="op">=</span> student_t.cdf((r_te <span class="op">-</span> mu) <span class="op">/</span> s, nu)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    worst <span class="op">=</span> <span class="bu">int</span>(np.argmax(logs))</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    rows.append({</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"model"</span>: name,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_LogS"</span>: logs.mean(),</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_CRPS"</span>: crps.mean(),</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"largest_LogS"</span>: logs[worst],</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">"largest_LogS_date"</span>: dates_te[worst].date(),</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">"CRPS_that_day"</span>: crps[worst],</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> pd.DataFrame(rows).set_index(<span class="st">"model"</span>)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(scores.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   mean_LogS  mean_CRPS  largest_LogS largest_LogS_date  CRPS_that_day
model                                                                                 
Constant Gaussian     1.3253     0.4743        4.3608        2024-12-18         2.3772
Gaussian HAR-FNN      1.2096     0.4459       21.4506        2024-12-18         2.8234
Student-t HAR-FNN     1.1692     0.4422        8.5227        2024-12-18         2.8556</code></pre>
</div>
</div>
<p>The second table summarizes the remaining outputs of the two networks over the test block: the range of the predictive standard deviations, where the Student-<span class="math inline">t</span> standard deviation is the scale multiplied by <span class="math inline">\sqrt{\nu/(\nu-2)}</span>; the share of test days on which the standard deviation lies below the constant standard deviation <span class="math inline">s_r</span>; and the ranges of the predicted means and of the degrees of freedom.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sd_t_te <span class="op">=</span> s_t_te <span class="op">*</span> np.sqrt(nu_t_te <span class="op">/</span> (nu_t_te <span class="op">-</span> <span class="dv">2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> pd.DataFrame({</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    name: {</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sd_min"</span>: sd.<span class="bu">min</span>(),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sd_max"</span>: sd.<span class="bu">max</span>(),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"share_sd_below_s_r"</span>: np.mean(sd <span class="op">&lt;</span> r_scale),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_min"</span>: mu.<span class="bu">min</span>(),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_max"</span>: mu.<span class="bu">max</span>(),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"nu_min"</span>: np.nan <span class="cf">if</span> nu <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> nu.<span class="bu">min</span>(),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"nu_max"</span>: np.nan <span class="cf">if</span> nu <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> nu.<span class="bu">max</span>(),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, sd, mu, nu <span class="kw">in</span> [</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"Gaussian HAR-FNN"</span>, sigma_gauss_te, mu_gauss_te, <span class="va">None</span>),</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"Student-t HAR-FNN"</span>, sd_t_te, mu_t_te, nu_t_te),</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>}).T</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(summary.<span class="bu">round</span>(<span class="dv">2</span>).to_string())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   sd_min  sd_max  share_sd_below_s_r  mean_min  mean_max  nu_min  nu_max
Gaussian HAR-FNN     0.28    2.11                0.86     -0.13      0.08     NaN     NaN
Student-t HAR-FNN    0.29    2.19                0.86     -0.09      0.15    5.97    7.74</code></pre>
</div>
</div>
<p><a href="#fig-distnn-empirical-bands" class="quarto-xref">Figure&nbsp;9.2</a> places the constant Gaussian benchmark and the Student-<span class="math inline">t</span> HAR-FNN on a common scale. Compare how the width of each shaded band relates to the realized returns over time.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>lower_t <span class="op">=</span> mu_t_te <span class="op">+</span> s_t_te <span class="op">*</span> student_t.ppf(<span class="fl">0.025</span>, nu_t_te)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>upper_t <span class="op">=</span> mu_t_te <span class="op">+</span> s_t_te <span class="op">*</span> student_t.ppf(<span class="fl">0.975</span>, nu_t_te)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>bands <span class="op">=</span> [</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Constant Gaussian"</span>, mu_const_te <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> sigma_const_te, mu_const_te <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> sigma_const_te, <span class="st">"C1"</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Student-t HAR-FNN"</span>, lower_t, upper_t, <span class="st">"C0"</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, lower, upper, _ <span class="kw">in</span> bands:</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    n_outside <span class="op">=</span> <span class="bu">int</span>(np.<span class="bu">sum</span>((r_te <span class="op">&lt;</span> lower) <span class="op">|</span> (r_te <span class="op">&gt;</span> upper)))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>n_outside<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(r_te)<span class="sc">}</span><span class="ss"> realized returns outside the central 95% interval"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Constant Gaussian: 3 of 502 realized returns outside the central 95% interval
Student-t HAR-FNN: 26 of 502 realized returns outside the central 95% interval</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">6.4</span>), sharex<span class="op">=</span><span class="va">True</span>, sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (label, lower, upper, color) <span class="kw">in</span> <span class="bu">zip</span>(axes, bands):</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.plot(dates_te, r_te, color<span class="op">=</span><span class="st">"0.55"</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="st">"realized return"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.fill_between(dates_te, lower, upper, color<span class="op">=</span>color, alpha<span class="op">=</span><span class="fl">0.25</span>, label<span class="op">=</span><span class="st">"central 95</span><span class="sc">% i</span><span class="st">nterval"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.<span class="bu">set</span>(title<span class="op">=</span>label, ylabel<span class="op">=</span><span class="st">"return (%)"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.legend(frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"lower left"</span>, ncol<span class="op">=</span><span class="dv">2</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.25</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Target date"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-distnn-empirical-bands" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distnn-empirical-bands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="distributions_via_nns_files/figure-html/fig-distnn-empirical-bands-1.png" class="img-fluid figure-img" width="1056">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distnn-empirical-bands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Realized close-to-close SPY returns <span class="math inline">r_{t+1}</span> in percent on the 2023–2024 test block (gray) with central 95% predictive intervals (shaded), each issued at the close of the previous trading day. Top: constant Gaussian forecast, whose interval uses the estimation-sample mean and standard deviation. Bottom: Student-<span class="math inline">t</span> HAR-FNN, whose interval endpoints are the 2.5% and 97.5% quantiles of the fitted location-scale Student-<span class="math inline">t</span> distribution. Both panels share the vertical axis.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The constant Gaussian band is a pair of parallel lines at roughly <span class="math inline">\pm 2.3</span> percent: a single estimation-sample variance is replayed at every test date. That variance reflects an estimation sample containing the turbulent years 2020 and 2022, so during the calmer test block the band is too wide on most days. Only 3 of the 502 realized returns fall outside it, whereas a calibrated central 95% interval would miss about 5 percent of outcomes on average. The Student-<span class="math inline">t</span> HAR-FNN band instead narrows in quiet stretches and widens after volatile days, most visibly in mid-March 2023 and in early August 2024; it is also wide in the first days of 2023, when the weekly and monthly components still reflect the volatile end of 2022. By comparison, 26 of the 502 realized returns (5.2 percent) fall outside this band. Because the inputs are realized variances up to the forecast origin, the band reacts to volatility that has already been observed; it cannot anticipate a large move on a day that follows a calm period.</p>
<p>The score table quantifies these differences. Both networks improve markedly on the constant Gaussian benchmark: average LogS falls from 1.325 to 1.210 for the Gaussian HAR-FNN and to 1.169 for the Student-<span class="math inline">t</span> HAR-FNN, and average CRPS from 0.474 to 0.446 and 0.442. Between the two networks, the Student-<span class="math inline">t</span> output has the clearly lower average LogS, whereas the two average CRPS values differ only in the third decimal. The last three columns show where much of the LogS gap between the networks comes from. On 18 December 2024, SPY fell by about 3 percent after a calm stretch in which the Gaussian network’s predictive standard deviation was about 0.5 percent, so the realized return lay more than six predictive standard deviations below the predictive mean. The Gaussian density at that outcome is so small that this single day has a LogS of about 21, compared with about 8.5 for the Student-<span class="math inline">t</span> network. Divided by 502 test days, this one difference accounts for roughly 0.026 of the average LogS gap of 0.040; without that day, the gap shrinks to about 0.015. This sensitivity is the tail behavior of the LogS discussed in <a href="#sec-distnn-training-scores" class="quarto-xref">Section&nbsp;9.4</a>: the LogS evaluates only the density at the realized outcome, and the Gaussian LogS grows quadratically in the standardized surprise, whereas the Student-<span class="math inline">t</span> LogS grows only logarithmically. The CRPS instead compares the predictive CDF with the step CDF of the outcome. For a large surprise it grows roughly linearly in the distance between the outcome and the predictive location and depends mainly on location and spread rather than on tail shape; on 18 December 2024, the two networks therefore receive almost the same CRPS. As in the <a href="./nn_example.html">previous chapter</a>, we do not test these differences formally; a <span class="citation" data-cites="DieboldMariano1995">Diebold and Mariano (<a href="#ref-DieboldMariano1995" role="doc-biblioref">1995</a>)</span> comparison of the score differentials with heteroskedasticity- and autocorrelation-consistent (HAC) standard errors, as developed in Exercise 4.3 of the <a href="./evaluating_distributions.html">predictive-distribution chapter</a>, would be the appropriate formal comparison.</p>
<p><a href="#fig-distnn-empirical-pit" class="quarto-xref">Figure&nbsp;9.3</a> turns from average scores to calibration. For each forecast, a flat histogram means that the realized returns fall about equally often into each of the 15 equal-probability intervals of the predictive distributions.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> {<span class="st">"Constant Gaussian"</span>: <span class="st">"C1"</span>, <span class="st">"Gaussian HAR-FNN"</span>: <span class="st">"C2"</span>, <span class="st">"Student-t HAR-FNN"</span>: <span class="st">"C0"</span>}</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">16</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">3.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (name, pit_values) <span class="kw">in</span> <span class="bu">zip</span>(axes, pit.items()):</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.hist(pit_values, bins<span class="op">=</span>bins, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span>colors[name], edgecolor<span class="op">=</span><span class="st">"white"</span>, alpha<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.axhline(<span class="fl">1.0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> ax.<span class="bu">set</span>(title<span class="op">=</span>name, xlabel<span class="op">=</span><span class="st">"PIT value"</span>, ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="fl">2.3</span>))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.25</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-distnn-empirical-pit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distnn-empirical-pit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="distributions_via_nns_files/figure-html/fig-distnn-empirical-pit-3.png" class="img-fluid figure-img" width="1152">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distnn-empirical-pit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: PIT histograms on the 2023–2024 test block, one panel per forecast. Each PIT value is the predictive CDF issued at origin <span class="math inline">t</span>, evaluated at the realized return <span class="math inline">r_{t+1}</span>; the histograms use 15 equal-width bins on <span class="math inline">[0,1]</span> and are scaled as densities. The red dashed line marks the uniform density that a calibrated forecast produces in population.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The constant Gaussian histogram is hump-shaped: far too few PIT values fall in the outer bins and too many near the center. Realized returns landed in the tails of this predictive distribution much less often than the forecast implies, which is the calibration counterpart of the overly wide band in <a href="#fig-distnn-empirical-bands" class="quarto-xref">Figure&nbsp;9.2</a>. The two network forecasts show no comparable systematic pattern; their bin heights scatter around the uniform density without a clear hump or U-shape. Because the PIT sample is finite and the PIT sequence may be serially dependent, these histograms are descriptive diagnostics rather than formal calibration tests, and they cannot rank the two networks against each other. That ranking rests on the scores.</p>
<p>The two networks share their inputs, architecture, and training settings, yet the Student-<span class="math inline">t</span> network attains the lower LogS. Do they differ in the scale of their predictive distributions or only in their tails? <a href="#fig-distnn-empirical-sd" class="quarto-xref">Figure&nbsp;9.4</a> compares the predictive standard deviations of the two networks, whose ranges appear in the second table above.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">4</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ax.scatter(dates_te, np.<span class="bu">abs</span>(r_te), s<span class="op">=</span><span class="dv">6</span>, color<span class="op">=</span><span class="st">"0.72"</span>, label<span class="op">=</span><span class="st">"|realized return|"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ax.plot(dates_te, sigma_gauss_te, color<span class="op">=</span>colors[<span class="st">"Gaussian HAR-FNN"</span>], linewidth<span class="op">=</span><span class="fl">1.0</span>, label<span class="op">=</span><span class="st">"Gaussian HAR-FNN"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ax.plot(dates_te, sd_t_te, color<span class="op">=</span>colors[<span class="st">"Student-t HAR-FNN"</span>], linewidth<span class="op">=</span><span class="fl">1.0</span>, linestyle<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"Student-t HAR-FNN"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>ax.axhline(r_scale, color<span class="op">=</span>colors[<span class="st">"Constant Gaussian"</span>], linestyle<span class="op">=</span><span class="st">":"</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, label<span class="op">=</span><span class="st">"Constant Gaussian"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Target date"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"percent"</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"upper left"</span>, ncol<span class="op">=</span><span class="dv">4</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.25</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-distnn-empirical-sd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distnn-empirical-sd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="distributions_via_nns_files/figure-html/fig-distnn-empirical-sd-5.png" class="img-fluid figure-img" width="1056">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distnn-empirical-sd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: Predictive standard deviations in percent on the 2023–2024 test block, each issued at origin <span class="math inline">t</span> for the return on the plotted target date. Solid line: the Gaussian HAR-FNN, with standard deviation <span class="math inline">\sigma_\phi(\mathbf{x}_t)</span>. Dashed line: the Student-<span class="math inline">t</span> HAR-FNN, with standard deviation <span class="math inline">s_\phi(\mathbf{x}_t)\sqrt{\nu_\phi(\mathbf{x}_t)/(\nu_\phi(\mathbf{x}_t)-2)}</span>. The dotted horizontal line is the constant Gaussian standard deviation <span class="math inline">s_r</span>. Gray dots show absolute realized returns <span class="math inline">|r_{t+1}|</span> for reference.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two standard-deviation paths are almost indistinguishable. Both rise sharply in mid-March 2023 and in early August 2024, reach lows of about 0.3 percent on the calmest days, and lie below the constant standard deviation <span class="math inline">s_r</span> on about 86 percent of test days, consistent with a constant forecast that is too wide for this test block. The two networks therefore agree on the scale of the predictive distribution, and the variance heads have learned to track the volatility information in the realized-variance inputs. The Student-<span class="math inline">t</span> network’s advantage under the LogS comes from the shape of its distribution: with degrees of freedom between about 6.0 and 7.7 on the test block, its tails assign more density to large surprises such as the return of 18 December 2024. The location heads add little: the predicted means stay within about 0.15 percentage points of zero, small relative to predictive standard deviations between about 0.3 and 2.2 percent. In this application, the gains over the constant benchmark therefore come from a variance head that responds to the realized-variance inputs and, for the LogS, from the heavier-tailed output family.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Question for Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question for Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Student-<span class="math inline">t</span> HAR-FNN restricts its degrees of freedom to <span class="math inline">\nu_\phi(\mathbf{x}_t)&gt;2</span>. Suppose the restriction were relaxed to <span class="math inline">\nu_\phi(\mathbf{x}_t)&gt;0</span>. For which values of <span class="math inline">\nu</span> would each of the following remain finite: (i) the LogS at a realized return, and (ii) the predictive standard deviation plotted in <a href="#fig-distnn-empirical-sd" class="quarto-xref">Figure&nbsp;9.4</a>?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggested Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li>The location-scale Student-<span class="math inline">t</span> density is positive and finite at every real outcome for any <span class="math inline">\nu&gt;0</span>, so the LogS at a realized return is finite for all <span class="math inline">\nu&gt;0</span>. (ii) The variance <span class="math inline">s^2\nu/(\nu-2)</span> is finite only for <span class="math inline">\nu&gt;2</span>.</li>
</ol>
</div>
</div>
</div>
<p>These comparisons rank complete forecasting procedures, each fitted once on one estimation sample, the two networks with a single random seed. The Gaussian and Student-<span class="math inline">t</span> networks share their architecture, inputs, and training settings and differ only in the output family, so the LogS gap between them speaks to tail shape, with the caveat that more than half of it comes from a single test day. The size of the improvement over the constant benchmark also depends on the test period: the calmer the test block is relative to the estimation sample, the more a constant variance overstates uncertainty. Nor does the comparison show that a neural network is needed to obtain these gains: a parametric model whose variance depends on the same realized-variance inputs would be the natural benchmark for judging the added flexibility of the network. Applying the full HNN stabilization procedure, or adding inputs whose effect on the return distribution may be nonlinear, would be natural next experiments.</p>
<p>The methodological lesson is that the diagnostics answer different questions. The bands and standard-deviation paths show whether the predictive scale responds to the information set. The PIT histograms show whether realized returns fall into the predictive distributions with the right frequencies. The scores combine calibration and concentration near the realized outcomes into one number per forecast. The constant Gaussian forecast fails the first two checks. Among the network forecasts, only the scores separate the Gaussian from the Student-<span class="math inline">t</span> output family.</p>
</section>
<section id="summary" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="summary"><span class="header-section-number">9.8</span> Summary</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Distributional networks predict parameters of a conditional distribution rather than only a point forecast.</li>
<li>Negative log-likelihood minimizes LogS; CRPS provides an alternative when it is differentiable for the chosen model.</li>
<li>Hemisphere networks stabilize joint learning through a constraint emphasizing volatility, blocked subsampling and blocked out-of-bag recalibration, in addition to separate outputs for location and scale.</li>
<li>Mixture density networks combine component distributions to represent shapes such as skewness and multiple modes.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Common Pitfalls
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Producing a valid density does not establish calibration, which must be checked on held-out outcomes.</li>
<li>Mixture components are not identified economic regimes without additional restrictions.</li>
</ul>
</div>
</div>
</section>
<section id="sec-distnn-exercises" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="sec-distnn-exercises"><span class="header-section-number">9.9</span> Exercises</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 9.1: Why Joint Gaussian NLL Training Can Be Ill-Posed
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a Gaussian distributional model for one-step-ahead forecasting. Maximizing the likelihood is equivalent to maximizing the log-likelihood, which in turn is equivalent to minimizing the negative log-likelihood. We therefore work with the per-observation Gaussian negative log-likelihood, up to an additive constant, </p>
<div class="display-math-block">
<p><span class="math display">
\ell_{t+1}(e_{t+1},\sigma_t^2)=\frac{1}{2}\log(\sigma_t^2)+\frac{e_{t+1}^2}{2\sigma_t^2},
\qquad e_{t+1}=y_{t+1}-\mu_t,\qquad \sigma_t^2&gt;0.
</span></p>
</div>
<ol type="1">
<li>For fixed <span class="math inline">e_{t+1} \neq 0</span>, derive the value of <span class="math inline">\sigma_t^2</span> that minimizes <span class="math inline">\ell_{t+1}(e_{t+1},\sigma_t^2)</span>. Verify that this critical point is a minimum.</li>
<li>Show that if <span class="math inline">e_{t+1}=0</span>, then the infimum of <span class="math inline">\ell_{t+1}(e_{t+1},\sigma_t^2)</span> over <span class="math inline">\sigma_t^2&gt;0</span> equals <span class="math inline">-\infty</span> and is not attained at any finite variance value. Conclude that if an overparameterized mean network interpolates the training sample exactly, so that <span class="math inline">e_{t+1}=0</span> for all <span class="math inline">t=1,\dots,T</span>, and the variance head can choose each <span class="math inline">\sigma_t^2</span> freely, the sample Gaussian NLL has no finite minimizer.</li>
<li>Suppose instead that the model imposes a variance floor <span class="math inline">\sigma_t^2 \ge c</span> for some constant <span class="math inline">c&gt;0</span>. Solve the constrained minimization problem for one observation and show that the optimal variance is <span class="math display">
\sigma_t^{2\ast}=\max\{e_{t+1}^2,c\}.
</span> Explain briefly why this removes the pathology from Part 2, but does not by itself guarantee good out-of-sample calibration.</li>
<li>Assume <span class="math inline">Y_{t+1}</span> and <span class="math inline">\mathbb{E}[Y_{t+1}\mid\mathbf{X}_t]</span> have finite second moments and that the process is stationary and ergodic. Use the law of total variance to show that <span class="math inline">\mathbb{E}[\operatorname{Var}(Y_{t+1}\mid\mathbf{X}_t)]\leq\operatorname{Var}(Y_{t+1})</span>, with strict inequality when the conditional mean is nonconstant.</li>
<li>Suppose a flexible mean interpolates every training outcome. State its in-sample average squared residual, explain why those residuals cannot calibrate the variance scale, and explain why blocked out-of-bag forecast errors are preferable when overlapping time-series windows share observations.</li>
</ol>
<p><em>Exam level. Parts 2–5 test whether students understand the instability behind joint mean-variance training and the motivation for out-of-bag calibration rather than only the Gaussian likelihood formula.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint for Part 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First solve the unconstrained problem from Part 1. Then check whether that solution satisfies the inequality constraint <span class="math inline">\sigma_t^2 \ge c</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part 1</strong></p>
<p>Differentiate with respect to <span class="math inline">\sigma_t^2</span>: </p>
<div class="display-math-block">
<p><span class="math display">
\frac{\partial \ell_{t+1}}{\partial \sigma_t^2}
= \frac{1}{2\sigma_t^2}-\frac{e_{t+1}^2}{2(\sigma_t^2)^2}.
</span></p>
</div>
<p> Setting this equal to zero gives </p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{2\sigma_t^2}=\frac{e_{t+1}^2}{2(\sigma_t^2)^2}
\quad\Longrightarrow\quad
\sigma_t^2=e_{t+1}^2.
</span></p>
</div>
<p> To verify that this is a minimum, compute the second derivative: </p>
<div class="display-math-block">
<p><span class="math display">
\frac{\partial^2 \ell_{t+1}}{\partial (\sigma_t^2)^2}
= -\frac{1}{2(\sigma_t^2)^2}+\frac{e_{t+1}^2}{(\sigma_t^2)^3}.
</span></p>
</div>
<p> Evaluating at <span class="math inline">\sigma_t^2=e_{t+1}^2</span> yields </p>
<div class="display-math-block">
<p><span class="math display">
\frac{\partial^2 \ell_{t+1}}{\partial (\sigma_t^2)^2}\Big|_{\sigma_t^2=e_{t+1}^2}
= \frac{1}{2e_{t+1}^4}&gt;0.
</span></p>
</div>
<p> Hence the minimizer for fixed <span class="math inline">e_{t+1}\neq 0</span> is <span class="math inline">\sigma_t^2=e_{t+1}^2</span>.</p>
<p><strong>Part 2</strong></p>
<p>If <span class="math inline">e_{t+1}=0</span>, then </p>
<div class="display-math-block">
<p><span class="math display">
\ell_{t+1}(0,\sigma_t^2)=\frac{1}{2}\log(\sigma_t^2).
</span></p>
</div>
<p> As <span class="math inline">\sigma_t^2 \downarrow 0</span>, </p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{2}\log(\sigma_t^2)\to -\infty.
</span></p>
</div>
<p> Therefore the infimum of the objective is <span class="math inline">-\infty</span>. However, no finite positive value of <span class="math inline">\sigma_t^2</span> attains this infimum, so the problem has no minimizer.</p>
<p>For the sample statement, if the mean network interpolates the training sample exactly, then <span class="math inline">e_{t+1}=0</span> for all <span class="math inline">t</span>. The sample objective is </p>
<div class="display-math-block">
<p><span class="math display">
\sum_{t=1}^{T}\ell_{t+1}(0,\sigma_t^2)=\frac{1}{2}\sum_{t=1}^{T}\log(\sigma_t^2).
</span></p>
</div>
<p> By sending each <span class="math inline">\sigma_t^2</span> arbitrarily close to zero, this sum can be made arbitrarily negative. Hence the training Gaussian NLL has no finite minimizer. This is the basic ill-posedness behind unstable joint training of very flexible mean and variance networks.</p>
<p><strong>Part 3</strong></p>
<p>From Part 1, the unconstrained minimizer is <span class="math inline">\sigma_t^2=e_{t+1}^2</span>. Under the constraint <span class="math inline">\sigma_t^2\ge c</span>, there are two cases:</p>
<ul>
<li>If <span class="math inline">e_{t+1}^2\ge c</span>, the unconstrained optimum is feasible, so <span class="math inline">\sigma_t^{2\ast}=e_{t+1}^2</span>.</li>
<li>If <span class="math inline">e_{t+1}^2&lt;c</span>, the unconstrained optimum violates the constraint, so the constrained optimum lies at the boundary, <span class="math inline">\sigma_t^{2\ast}=c</span>.</li>
</ul>
<p>Therefore </p>
<div class="display-math-block">
<p><span class="math display">
\sigma_t^{2\ast}=\max\{e_{t+1}^2,c\}.
</span></p>
</div>
<p>The positive variance floor removes the pathology from Part 2 because even if <span class="math inline">e_{t+1}=0</span>, the smallest admissible variance is now <span class="math inline">c</span>, so the objective cannot be driven to <span class="math inline">-\infty</span> by shrinking the variance to zero. But this does not guarantee good out-of-sample calibration: a variance floor prevents a mathematical degeneracy, yet the learned variance process can still be badly misspecified for future data.</p>
<p><strong>Part 4</strong></p>
<p>The law of total variance gives </p>
<div class="display-math-block">
<p><span class="math display">
\operatorname{Var}(Y_{t+1})
=\mathbb{E}\!\left[\operatorname{Var}(Y_{t+1}\mid\mathbf{X}_t)\right]
+\operatorname{Var}\!\left(\mathbb{E}[Y_{t+1}\mid\mathbf{X}_t]\right).
</span></p>
</div>
<p> The second term is nonnegative, which proves the weak inequality. It is positive when the conditional mean is nonconstant, giving strict inequality. Stationarity and ergodicity justify estimating these population moments with time averages.</p>
<p><strong>Part 5</strong></p>
<p>If the fitted mean interpolates every training outcome, then <span class="math inline">e_{t+1}=0</span> for every training origin and </p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{T}\sum_{t=1}^{T}e_{t+1}^2=0.
</span></p>
</div>
<p> These in-sample residuals contain no information about the variance of genuine forecast errors and therefore cannot calibrate <span class="math inline">\kappa</span> or the overall variance scale. An out-of-bag error at time <span class="math inline">t+1</span> comes from a fit that did not train on that target. Holding out contiguous blocks also reduces the direct information sharing created when adjacent, overlapping windows contain many of the same observations. Blocked out-of-bag errors are therefore more credible proxies for time-series forecast errors than either interpolating residuals or errors from randomly held-out individual dates.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 9.2: Moment-Matched Gaussian Forecasts versus MDNs
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the symmetric two-component conditional density </p>
<div class="display-math-block">
<p><span class="math display">
f_M(y\mid \mathbf{x}_t)
= \frac{1}{2}\,\varphi(y;-m_t,s^2)+\frac{1}{2}\,\varphi(y;m_t,s^2),
\qquad m_t&gt;0,\ s&gt;0,
</span></p>
</div>
<p> where <span class="math inline">\varphi(y;\mu,\sigma^2)</span> denotes the Gaussian density with mean <span class="math inline">\mu</span> and variance <span class="math inline">\sigma^2</span>.</p>
<p>Now consider the Gaussian forecast </p>
<div class="display-math-block">
<p><span class="math display">
f_G(y\mid \mathbf{x}_t)=\varphi(y;0,m_t^2+s^2),
</span></p>
</div>
<p> which matches the first two moments of <span class="math inline">f_M</span>.</p>
<ol type="1">
<li>Derive the conditional mean and conditional variance of <span class="math inline">f_M(y\mid \mathbf{x}_t)</span> and verify that <span class="math inline">f_G</span> indeed matches these two moments.</li>
<li>Show that the point forecast that minimizes conditional MSE under both <span class="math inline">f_M</span> and <span class="math inline">f_G</span> is zero. Explain why an MSE comparison cannot distinguish these two forecast distributions.</li>
<li>Evaluate both densities at the realized outcome <span class="math inline">y_{t+1}=m_t</span>: <span class="math display">
f_M(m_t\mid \mathbf{x}_t)
\qquad\text{and}\qquad
f_G(m_t\mid \mathbf{x}_t).
</span> Show that as <span class="math inline">m_t \to \infty</span> with <span class="math inline">s</span> fixed, the mixture density at <span class="math inline">y_{t+1}=m_t</span> stays bounded away from zero, while the Gaussian density goes to zero. Conclude that LogS can strongly prefer the MDN-style forecast even when MSE cannot distinguish the two models.</li>
<li>Show formally that swapping the labels of the two mixture components leaves <span class="math inline">f_M(y\mid \mathbf{x}_t)</span> unchanged. Explain why this means that mixture components are not structurally identified without additional restrictions.</li>
</ol>
<p><em>Exam level. The point of this exercise is that matching means and variances is not enough to match the predictive distribution, and that distributional scores can detect this while MSE cannot.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint for Part 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Use the symmetry of the mixture. For the variance, compute <span class="math inline">\mathbb{E}[Y_{t+1}^2\mid \mathbf{x}_t]</span> first.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part 1</strong></p>
<p>By symmetry, </p>
<div class="display-math-block">
<p><span class="math display">
\mathbb{E}[Y_{t+1}\mid \mathbf{x}_t]
= \frac{1}{2}(-m_t)+\frac{1}{2}(m_t)=0.
</span></p>
</div>
<p> For the second moment, </p>
<div class="display-math-block">
<p><span class="math display">
\mathbb{E}[Y_{t+1}^2\mid \mathbf{x}_t]
= \frac{1}{2}(m_t^2+s^2)+\frac{1}{2}(m_t^2+s^2)
= m_t^2+s^2.
</span></p>
</div>
<p> Hence </p>
<div class="display-math-block">
<p><span class="math display">
\operatorname{Var}(Y_{t+1}\mid \mathbf{x}_t)
= \mathbb{E}[Y_{t+1}^2\mid \mathbf{x}_t]
- \big(\mathbb{E}[Y_{t+1}\mid \mathbf{x}_t]\big)^2
= m_t^2+s^2.
</span></p>
</div>
<p> The Gaussian forecast <span class="math inline">f_G(y\mid \mathbf{x}_t)=\varphi(y;0,m_t^2+s^2)</span> therefore matches the conditional mean and variance of the mixture forecast.</p>
<p><strong>Part 2</strong></p>
<p>Under squared-error loss, the optimal point forecast is the conditional mean. Since both forecast distributions have conditional mean zero, the MSE-optimal point forecast is </p>
<div class="display-math-block">
<p><span class="math display">
\hat{y}_{t+1\mid t}=0.
</span></p>
</div>
<p> Therefore an MSE comparison cannot distinguish the two forecast distributions: both imply exactly the same optimal point forecast, even though one forecast is bimodal and the other is unimodal.</p>
<p><strong>Part 3</strong></p>
<p>For the mixture density at <span class="math inline">y_{t+1}=m_t</span>, </p>
<div class="display-math-block">
<p><span class="math display">
f_M(m_t\mid \mathbf{x}_t)
= \frac{1}{2}\varphi(m_t;-m_t,s^2)+\frac{1}{2}\varphi(m_t;m_t,s^2).
</span></p>
</div>
<p> Using the Gaussian density formula, </p>
<div class="display-math-block">
<p><span class="math display">
f_M(m_t\mid \mathbf{x}_t)
= \frac{1}{2}\frac{1}{\sqrt{2\pi}s}e^{-2m_t^2/s^2}
+ \frac{1}{2}\frac{1}{\sqrt{2\pi}s}
= \frac{1}{2\sqrt{2\pi}s}\Big(1+e^{-2m_t^2/s^2}\Big).
</span></p>
</div>
<p>For the Gaussian forecast, </p>
<div class="display-math-block">
<p><span class="math display">
f_G(m_t\mid \mathbf{x}_t)
= \frac{1}{\sqrt{2\pi(m_t^2+s^2)}}\exp\!\left(-\frac{m_t^2}{2(m_t^2+s^2)}\right).
</span></p>
</div>
<p>As <span class="math inline">m_t \to \infty</span> with <span class="math inline">s</span> fixed, we have </p>
<div class="display-math-block">
<p><span class="math display">
f_M(m_t\mid \mathbf{x}_t)\to \frac{1}{2\sqrt{2\pi}s},
</span></p>
</div>
<p> which is strictly positive, whereas </p>
<div class="display-math-block">
<p><span class="math display">
f_G(m_t\mid \mathbf{x}_t)
\sim \frac{e^{-1/2}}{\sqrt{2\pi}\,m_t}\to 0.
</span></p>
</div>
<p> So when the realization lands near one of the two modes and the modes are well separated, the mixture forecast assigns much higher density to the realized value. Therefore the mixture forecast achieves a substantially lower (better) LogS, even though MSE cannot distinguish it from the moment-matched Gaussian.</p>
<p><strong>Part 4</strong></p>
<p>If we swap the component labels, the predictive density becomes </p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{2}\varphi(y;m_t,s^2)+\frac{1}{2}\varphi(y;-m_t,s^2),
</span></p>
</div>
<p> which is exactly the same expression as the original density, just with the two terms reversed. Hence the predictive density is unchanged by relabeling the components.</p>
<p>This is the label-switching problem. It implies that the two mixture components are not structurally identified from predictive fit alone. To interpret them as economic regimes, one would need additional restrictions, theory, or identifying assumptions beyond the MDN likelihood.</p>
</div>
</div>
</div>
</section>
<section id="references" class="level2" data-number="9.10">
<h2 data-number="9.10" class="anchored" data-anchor-id="references"><span class="header-section-number">9.10</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Bishop1994MDN" class="csl-entry" role="listitem">
Bishop, Christopher M. 1994. <span>“Mixture Density Networks.”</span> Technical Report NCRG/94/004. Birmingham, U.K.: Neural Computing Research Group, Aston University.
</div>
<div id="ref-BollerslevWooldridge1992" class="csl-entry" role="listitem">
Bollerslev, Tim, and Jeffrey M. Wooldridge. 1992. <span>“Quasi-Maximum Likelihood Estimation and Inference in Dynamic Models with Time-Varying Covariances.”</span> <em>Econometric Reviews</em> 11 (2): 143–72. <a href="https://doi.org/10.1080/07474939208800229">https://doi.org/10.1080/07474939208800229</a>.
</div>
<div id="ref-CorsiHAR2009" class="csl-entry" role="listitem">
Corsi, Fulvio. 2009. <span>“A Simple Approximate Long-Memory Model of Realized Volatility.”</span> <em>Journal of Financial Econometrics</em> 7 (2): 174–96. <a href="https://doi.org/10.1093/jjfinec/nbp001">https://doi.org/10.1093/jjfinec/nbp001</a>.
</div>
<div id="ref-DieboldMariano1995" class="csl-entry" role="listitem">
Diebold, Francis X, and Robert S Mariano. 1995. <span>“<span class="nocase">Comparing predictive accuracy</span>.”</span> <em>Journal of Business and Economic Statistics</em> 13 (3): 253–63. <a href="https://doi.org/10.1080/07350015.1995.10524599">https://doi.org/10.1080/07350015.1995.10524599</a>.
</div>
<div id="ref-GneitingKatzfuss2014" class="csl-entry" role="listitem">
Gneiting, Tilmann, and Matthias Katzfuss. 2014. <span>“Probabilistic Forecasting.”</span> <em>Annual Review of Statistics and Its Application</em> 1: 125–51. <a href="https://doi.org/10.1146/annurev-statistics-062713-085831">https://doi.org/10.1146/annurev-statistics-062713-085831</a>.
</div>
<div id="ref-GouletCoulombeFrenetteKlieber2026" class="csl-entry" role="listitem">
Goulet Coulombe, Philippe, Mikael Frenette, and Karin Klieber. 2026. <span>“<span class="nocase">From Reactive to Proactive Volatility Modeling With Hemisphere Neural Networks</span>.”</span> <em>Journal of Applied Econometrics</em> 41 (3): 265–79. <a href="https://doi.org/10.1002/jae.70042">https://doi.org/10.1002/jae.70042</a>.
</div>
<div id="ref-JordanKruegerLerch2019" class="csl-entry" role="listitem">
Jordan, Alexander, Fabian Krüger, and Sebastian Lerch. 2019. <span>“<span class="nocase">Evaluating probabilistic forecasts with scoringRules</span>.”</span> <em>Journal of Statistical Software</em> 90 (12): 1–37. <a href="https://doi.org/10.18637/jss.v090.i12">https://doi.org/10.18637/jss.v090.i12</a>.
</div>
<div id="ref-Kleen2024" class="csl-entry" role="listitem">
Kleen, Onno. 2024. <span>“Scaling and Measurement Error Sensitivity of Scoring Rules for Distribution Forecasts.”</span> <em>Journal of Applied Econometrics</em> 39 (5): 833–49. <a href="https://doi.org/10.1002/jae.3056">https://doi.org/10.1002/jae.3056</a>.
</div>
<div id="ref-WeiJiang2025" class="csl-entry" role="listitem">
Wei, Yanhao, and Zhenling Jiang. 2025. <span>“<span class="nocase">Estimating Parameters of Structural Models Using Neural Networks</span>.”</span> <em>Marketing Science</em> 44 (1): 102–28. <a href="https://doi.org/10.1287/mksc.2022.0360">https://doi.org/10.1287/mksc.2022.0360</a>.
</div>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The data file <code>data/taq_spy/SPY_daily_measures.csv</code> covers 2015-01-02 through 2024-12-31 and is documented in <a href="./datasets.html#sec-spy-taq-realized">the dataset appendix</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mlmetrics\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./nn_example.html" class="pagination-link" aria-label="8. Empirical Exercise: Networks for Time Series">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">8. Empirical Exercise: Networks for Time Series</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./decision_trees.html" class="pagination-link" aria-label="10. Decision Trees">
        <span class="nav-page-text">10. Decision Trees</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2026, Onno Kleen</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>