<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>gradient_boosting – MLmetrics: Machine Learning for Econometricians</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./adv_tree_based_methods.html" rel="next">
<link href="./random_forests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
(function () {
  function markInternalLinks() {
    const links = window.document.querySelectorAll("a[href]");

    for (const link of links) {
      if (link.origin !== window.location.origin) {
        continue;
      }

      link.classList.add("no-external");

      if (link.getAttribute("target") === "_blank") {
        link.removeAttribute("target");
      }

      const rel = link.getAttribute("rel");
      if (rel === "noopener") {
        link.removeAttribute("rel");
      }
    }
  }

  if (window.document.readyState === "loading") {
    window.document.addEventListener("DOMContentLoaded", markInternalLinks, {
      once: true,
    });
  } else {
    markInternalLinks();
  }
})();
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./decision_trees.html">Tree-Based Methods</a></li><li class="breadcrumb-item"><a href="./gradient_boosting.html">12. Gradient Boosting</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About This Book</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./information_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Information Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cross_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Cross-Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Optimization for Machine Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluating_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Evaluating Predictive Distributions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Neural Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./feed_forward_nns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Feed-Forward Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recurrent_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Recurrent Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lstm_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. LSTM Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nn_example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Empirical Exercise: Networks for Time Series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions_via_nns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Distribution Modeling with Neural Networks</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Tree-Based Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Decision Trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random_forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11. Random Forests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gradient_boosting.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">12. Gradient Boosting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./adv_tree_based_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13. Advanced Tree-Based Methods</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Further Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hpo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14. Advanced Hyperparameter Optimization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conformal_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">15. Conformal Prediction</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kernel_smoothing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kernel Smoothing Primer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-gradient-boosting" id="toc-sec-gradient-boosting" class="nav-link active" data-scroll-target="#sec-gradient-boosting"><span class="header-section-number">12</span> Gradient Boosting</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">12.1</span> Overview</a></li>
  <li><a href="#roadmap" id="toc-roadmap" class="nav-link" data-scroll-target="#roadmap"><span class="header-section-number">12.2</span> Roadmap</a></li>
  <li><a href="#sec-gb-additive" id="toc-sec-gb-additive" class="nav-link" data-scroll-target="#sec-gb-additive"><span class="header-section-number">12.3</span> Additive Stagewise Modeling</a></li>
  <li><a href="#sec-gb-squared-error" id="toc-sec-gb-squared-error" class="nav-link" data-scroll-target="#sec-gb-squared-error"><span class="header-section-number">12.4</span> Squared-Error Boosting</a></li>
  <li><a href="#sec-gb-general" id="toc-sec-gb-general" class="nav-link" data-scroll-target="#sec-gb-general"><span class="header-section-number">12.5</span> General Gradient Boosting</a></li>
  <li><a href="#sec-gb-regularization" id="toc-sec-gb-regularization" class="nav-link" data-scroll-target="#sec-gb-regularization"><span class="header-section-number">12.6</span> Regularization in Boosting</a></li>
  <li><a href="#sec-gb-early-stopping" id="toc-sec-gb-early-stopping" class="nav-link" data-scroll-target="#sec-gb-early-stopping"><span class="header-section-number">12.7</span> Early Stopping and Validation</a></li>
  <li><a href="#sec-gb-credit-default" id="toc-sec-gb-credit-default" class="nav-link" data-scroll-target="#sec-gb-credit-default"><span class="header-section-number">12.8</span> Empirical Comparison: Credit-Default Probabilities</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">12.9</span> Summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">12.10</span> Exercises</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">12.11</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./decision_trees.html">Tree-Based Methods</a></li><li class="breadcrumb-item"><a href="./gradient_boosting.html">12. Gradient Boosting</a></li></ol></nav></header>
<div class="alert alert-warning" role="alert" style="margin: 0; border-radius: 0; border: none; border-bottom: 1px solid #f0c842; text-align: center; font-size: 0.9em; padding: 0.5rem 1rem;">
  <strong>Under active development.</strong> A stable version is expected in November 2026. Feedback is welcome by <a href="mailto:kleen@ese.eur.nl">email</a> or via <a href="https://github.com/onnokleen/mlmetrics/issues">GitHub issues</a>.
</div>




<section id="sec-gradient-boosting" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Gradient Boosting</h1>
<section id="overview" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">12.1</span> Overview</h2>
<p>Gradient boosting is a sequential tree-based method that builds an additive predictor by repeatedly fitting new trees to the mistakes of the current ensemble. Random forests are designed primarily to stabilize high-variance trees through averaging, whereas boosting often emphasizes bias reduction through successive corrections. In practice, both methods can change both bias and variance. The modern gradient-boosting formulation is due to <span class="citation" data-cites="Friedman2001Greedy">J. H. Friedman (<a href="#ref-Friedman2001Greedy" role="doc-biblioref">2001</a>)</span>; adaptive boosting (AdaBoost) is an important predecessor and special case in the broader boosting literature <span class="citation" data-cites="FreundSchapire1997">(<a href="#ref-FreundSchapire1997" role="doc-biblioref">Freund and Schapire 1997</a>)</span>.</p>
<p>For econometricians, boosting is a flexible predictive tool for tabular data. It can learn nonlinearities, interactions, threshold effects, and asymmetric predictive relationships without the researcher specifying them. It is well suited to settings where the signal is spread across many variables: representing such structure with one regularized tree may require many splits and produce an unstable approximation.</p>
<p>At the same time, boosting has several interacting tuning choices. Learning rate, tree depth, early stopping—halting the boosting run at the iteration count that performs best on held-out data—and validation design are all consequential. In time-series and forecasting applications, careless validation can create large but spurious performance gains. A common credit-default application near the end of the chapter compares boosting with a single tree, a random forest, logistic regression, and a feed-forward neural network (FNN) using the same data split and the same probability-based scores.</p>
</section>
<section id="roadmap" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="roadmap"><span class="header-section-number">12.2</span> Roadmap</h2>
<ol type="1">
<li>We begin with the additive structure of boosting and contrast it with random forests.</li>
<li>We then derive the squared-error version, where each new tree fits residuals.</li>
<li>Next we generalize to arbitrary differentiable losses, with each new tree fitted to the negative loss gradients—the <em>pseudo-residuals</em>.</li>
<li>We then discuss shrinkage (scaling each tree’s contribution by a learning rate), tree depth, subsampling, and early stopping.</li>
<li>We then revisit credit-card default prediction to compare the tree-based methods with logistic regression and a feed-forward neural network.</li>
<li>Finally, we summarize how boosting should be interpreted and validated in econometric applications.</li>
</ol>
</section>
<section id="sec-gb-additive" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="sec-gb-additive"><span class="header-section-number">12.3</span> Additive Stagewise Modeling</h2>
<p>Following the standard notation in the boosting literature, this chapter writes <span class="math inline">\hat F_m</span> for the fitted ensemble prediction function after iteration <span class="math inline">m</span> and <span class="math inline">F</span> for a generic candidate function. This chapter-local notation is distinct from the use of <span class="math inline">F</span> for a predictive cumulative distribution function in earlier chapters. In regression, <span class="math inline">\hat F_m(x)</span> is a point prediction; in Bernoulli classification below, it is the log-odds of the event.</p>
<p>Boosting constructs the predictor</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_M(x) = \hat F_0(x) + \nu \sum_{m=1}^M \hat h_m(x),
</span></p>
</div>
<p>where:</p>
<ul>
<li><span class="math inline">\hat F_0</span> is an initial simple predictor</li>
<li><span class="math inline">\hat h_m</span> is the tree added at iteration <span class="math inline">m</span></li>
<li><span class="math inline">\nu \in (0,1]</span> is the learning rate—the boosting counterpart of the gradient-descent step size <span class="math inline">\eta</span> in the <a href="./optimization.html">optimization chapter</a>; the symbol <span class="math inline">\nu</span> follows the boosting literature and is unrelated to the degrees-of-freedom parameter of the <a href="./distributions_via_nns.html">distributional network chapter</a></li>
<li><span class="math inline">M</span> is the number of boosting iterations</li>
</ul>
<p>Each tree here plays the role of a <em>weak learner</em> (equivalently, a <em>base learner</em>): a deliberately low-complexity base model—in this chapter a shallow regression tree. The name comes from classification boosting, where a weak learner performs only slightly better than random guessing. Gradient boosting imposes no such requirement on any tree in isolation. Each tree’s job is instead to move the current ensemble in a descent direction of the loss, so it is fitted to the current residuals or pseudo-residuals rather than directly to the original target.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Random Forests vs Boosting
</div>
</div>
<div class="callout-body-container callout-body">
<p>The two methods use the same basic building block, the decision tree, but in different ways:</p>
<ol type="1">
<li>Random forests grow many trees largely independently and average them, primarily to stabilize high-variance tree predictions.</li>
<li>Boosting grows trees sequentially, with each new tree correcting the current ensemble; this often reduces bias, but can also change variance.</li>
<li>Random forests do not have a learning-rate–iteration-count tradeoff; boosting requires these two choices to be tuned jointly.</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Ensemble structure</th>
<th>Main regularization or stabilization lever</th>
<th>Main risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single tree</td>
<td>No ensemble</td>
<td>Tree depth, leaf size, pruning</td>
<td>High variance and discontinuity</td>
</tr>
<tr class="even">
<td>Bagging</td>
<td>Parallel bootstrap trees</td>
<td>Tree size; <span class="math inline">B</span> controls Monte Carlo error in the average</td>
<td>Trees may remain highly correlated</td>
</tr>
<tr class="odd">
<td>Random forest</td>
<td>Parallel bootstrap trees with feature subsampling</td>
<td><code>max_features</code> and leaf size; <span class="math inline">B</span> controls Monte Carlo error in the average</td>
<td>Out-of-bag (OOB) error can mislead under dependence</td>
</tr>
<tr class="even">
<td>Gradient boosting</td>
<td>Sequential trees fit to residuals or pseudo-residuals</td>
<td>Learning rate, number of trees, tree depth, early stopping</td>
<td>Sensitive tuning and validation leakage</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="sec-gb-squared-error" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="sec-gb-squared-error"><span class="header-section-number">12.4</span> Squared-Error Boosting</h2>
<p>Start with regression. The training sample is <span class="math inline">\{(x_i, y_i)\}_{i=1}^N</span>, with predictor vector <span class="math inline">x_i \in \mathbb{R}^p</span> and scalar outcome <span class="math inline">y_i</span>—in the book’s case convention, the realized values of random pairs <span class="math inline">(X_i, Y_i)</span>, as in the <a href="./decision_trees.html">decision trees chapter</a>. Under squared loss, the training objective of a candidate prediction function <span class="math inline">F</span> is</p>
<div class="display-math-block">
<p><span class="math display">
L(F) = \frac{1}{2}\sum_{i=1}^N (y_i - F(x_i))^2.
</span></p>
</div>
<p>The factor <span class="math inline">\frac{1}{2}</span> is algebraically convenient and does not affect the minimizer.</p>
<p>Two conventions in this display are worth flagging, since they differ from earlier chapters. First, <span class="math inline">L</span> here is the <em>total</em> training loss, summed and not averaged over observations—the convention of the boosting literature, and the one that makes the pseudo-residuals below come out as <span class="math inline">y_i - F(x_i)</span> without a trailing <span class="math inline">1/N</span>. The <a href="./optimization.html">optimization chapter</a> instead wrote <span class="math inline">L(\boldsymbol\theta) = N^{-1}\sum_{i=1}^N \ell_i(\boldsymbol\theta)</span> for the sample average; the two differ by the constant factor <span class="math inline">N</span>, which changes neither the minimizer nor the direction of the gradient. Second, the per-observation loss is written outcome first, <span class="math inline">\ell(y_i, F(x_i))</span>, as in the <a href="./feed_forward_nns.html">feed-forward networks chapter</a>.</p>
<p><strong>Step 0: Initial Model</strong></p>
<p>The best constant predictor minimizes</p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{2}\sum_{i=1}^N (y_i - c)^2.
</span></p>
</div>
<p>Differentiating with respect to <span class="math inline">c</span> gives</p>
<div class="display-math-block">
<p><span class="math display">
\sum_{i=1}^N (c - y_i) = 0
\quad \Longrightarrow \quad
\hat F_0(x) \equiv \bar y.
</span></p>
</div>
<p>So the initial model is simply the sample mean.</p>
<p><strong>Step 1: Residual Fitting</strong></p>
<p>At iteration <span class="math inline">m</span>, define the residuals of the current ensemble as</p>
<div class="display-math-block">
<p><span class="math display">
r_{im} = y_i - \hat F_{m-1}(x_i).
</span></p>
</div>
<p>Under squared loss, these residuals are negative derivatives of the loss with respect to the prediction. Hold observation <span class="math inline">i</span> fixed and regard its loss contribution <span class="math inline">\tfrac{1}{2}(y_i - z)^2</span> as an ordinary function of one real argument <span class="math inline">z</span>, the prediction for that observation. Its derivative is <span class="math inline">z - y_i</span>, so the negative derivative, evaluated at the current fitted value <span class="math inline">z = \hat F_{m-1}(x_i)</span>, is exactly the residual <span class="math inline">r_{im}</span>. Boosting therefore fits the next tree <span class="math inline">\hat h_m(x)</span> to the residuals by least squares. The ideal tree would solve</p>
<div class="display-math-block">
<p><span class="math display">
\min_{h}\ \sum_{i=1}^N \bigl(r_{im} - h(x_i)\bigr)^2,
</span></p>
</div>
<p>where the minimization runs over all regression trees <span class="math inline">h</span> of maximum depth <span class="math inline">d</span>. Solving this problem exactly is computationally infeasible, so in practice <span class="math inline">\hat h_m</span> is grown by <a href="./decision_trees.html#sec-dt-regression">recursive binary splitting</a> with the residuals as the response. Each split is myopically optimal given the splits already made, so the fitted tree aims at a small value of the least-squares criterion without any guarantee of attaining its global minimum over depth-<span class="math inline">d</span> trees. One part of the fit is exact, though: given the partition the greedy search selects, the prediction in each leaf is the mean of the residuals in that leaf, which is the least-squares-optimal constant there.</p>
<p>The update is then</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_m(x) = \hat F_{m-1}(x) + \nu \hat h_m(x).
</span></p>
</div>
<p>If <span class="math inline">\nu = 1</span>, the correction is taken in full. If <span class="math inline">\nu &lt; 1</span>, the update is shrunken.</p>
<p>For an econometrician, this is shrunken forward-stagewise regression. If the candidate weak learners were single regressors rather than trees, each stage would run a low-complexity ordinary least squares regression of the current residuals on the candidate regressors, add only a fraction <span class="math inline">\nu</span> of the selected fitted value, and then recompute the residuals.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Squared-Error Boosting Algorithm
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the regression-tree case, the algorithm can be summarized as follows.</p>
<ol type="1">
<li>Initialize <span class="math inline">\hat F_0(x)=\bar y</span> and residuals <span class="math inline">r_i=y_i-\bar y</span>.</li>
<li>For <span class="math inline">m=1,\ldots,M</span>:
<ul>
<li>fit a shallow tree <span class="math inline">\hat h_m</span> with maximum depth <span class="math inline">d</span> to the current residuals</li>
<li>update <span class="math inline">\hat F_m(x)=\hat F_{m-1}(x)+\nu \hat h_m(x)</span></li>
<li>update residuals <span class="math inline">r_i=y_i-\hat F_m(x_i)</span></li>
</ul></li>
<li>Return the boosted predictor <span class="math inline">\hat F_M(x)</span>.</li>
</ol>
<p>The maximum depth <span class="math inline">d</span> bounds the interaction order available along a root-to-leaf path, while <span class="math inline">\nu</span> controls how cautiously each correction is added.</p>
</div>
</div>
<p><a href="#fig-boosting-sequence" class="quarto-xref">Figure&nbsp;12.1</a> follows the fitted function from the initial constant through two later boosting stages. The data are simulated: a single predictor, an outcome that combines a sine wave, a mild linear trend, and an upward level shift beyond <span class="math inline">x = 0.8</span>, plus Gaussian noise.</p>
<div id="cell-fig-boosting-sequence" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> GradientBoostingRegressor</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">202</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.sort(rng.uniform(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">200</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> np.sin(<span class="fl">1.3</span> <span class="op">*</span> x) <span class="op">+</span> <span class="fl">0.35</span> <span class="op">*</span> x <span class="op">+</span> <span class="fl">0.8</span> <span class="op">*</span> (x <span class="op">&gt;</span> <span class="fl">0.8</span>) <span class="op">+</span> rng.normal(scale<span class="op">=</span><span class="fl">0.35</span>, size<span class="op">=</span>x.shape[<span class="dv">0</span>])</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>gbr <span class="op">=</span> GradientBoostingRegressor(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    n_estimators<span class="op">=</span><span class="dv">60</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    learning_rate<span class="op">=</span><span class="fl">0.1</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    max_depth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    min_samples_leaf<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">202</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>gbr.fit(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), y)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>x_grid <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">3.1</span>, <span class="fl">3.1</span>, <span class="dv">500</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>staged <span class="op">=</span> <span class="bu">list</span>(gbr.staged_predict(x_grid.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>f0 <span class="op">=</span> np.full_like(x_grid, np.mean(y))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="fl">4.5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, pred, title <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    axes,</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    [f0, staged[<span class="dv">2</span>], staged[<span class="dv">39</span>]],</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Initial constant model"</span>, <span class="st">"After 3 trees"</span>, <span class="st">"After 40 trees"</span>],</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    ax.scatter(x, y, s<span class="op">=</span><span class="dv">15</span>, color<span class="op">=</span><span class="st">"0.4"</span>, alpha<span class="op">=</span><span class="fl">0.65</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    ax.plot(x_grid, pred, linewidth<span class="op">=</span><span class="fl">2.4</span>, color<span class="op">=</span><span class="st">"C3"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Predictor"</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Outcome"</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-boosting-sequence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boosting-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="gradient_boosting_files/figure-html/fig-boosting-sequence-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boosting-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Training observations (gray points) and the boosted fit (red line) at three stages: the initial constant model (left), after 3 trees (center), and after 40 trees (right).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The ensemble starts as a constant. With each iteration, the fit becomes more refined because the next tree is trained on what the current ensemble still gets wrong.</p>
<p><strong>Why Small Trees Are Used</strong></p>
<p>Boosting usually uses shallow trees rather than deep ones. A <strong>decision stump</strong> is a depth-1 tree with one split, so it captures a single threshold effect. A tree of depth 2 or 3 can capture low-order interactions. This is deliberate regularization:</p>
<ul>
<li>shallow trees make each correction simple</li>
<li>many simple corrections can approximate a complicated function</li>
<li>restricting tree depth reduces the risk of overfitting each stage</li>
</ul>
<p>This stagewise logic is one reason boosting performs well on tabular data when the regression function has low- to moderate-order interactions.</p>
</section>
<section id="sec-gb-general" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="sec-gb-general"><span class="header-section-number">12.5</span> General Gradient Boosting</h2>
<p>Squared loss gives us a particularly convenient starting point. Under <span class="math inline">\ell(y,z)=\tfrac12(y-z)^2</span>, the negative gradient <span class="math inline">y-z</span> is an ordinary residual, measured in the same units as the outcome and the prediction. The residual therefore directly describes an additive correction on the target scale. Moreover, its average within a fixed tree leaf is already the loss-minimizing correction for that leaf. These properties make squared-error boosting especially simple.</p>
<p>Gradient boosting extends beyond squared loss by replacing the residual with the negative gradient of a differentiable loss. Suppose the objective is</p>
<div class="display-math-block">
<p><span class="math display">
\sum_{i=1}^N \ell(y_i, F(x_i)),
</span></p>
</div>
<p>where <span class="math inline">\ell</span> is differentiable with respect to the fitted value <span class="math inline">F(x_i)</span>. As under squared loss, we start from a constant predictor that minimizes the training loss, assuming a finite minimizer exists.</p>
<p>At iteration <span class="math inline">m</span>, hold <span class="math inline">y_i</span> fixed, regard <span class="math inline">\ell(y_i,z)</span> as a function of the scalar prediction <span class="math inline">z</span>, and evaluate its negative derivative at the current fitted value:</p>
<div class="display-math-block">
<p><span class="math display">
r_{im}
=
-
\left.
\frac{\partial \ell(y_i,z)}{\partial z}
\right|_{z=\hat F_{m-1}(x_i)}.
</span></p>
</div>
<p>A positive pseudo-residual indicates that a small increase in the prediction lowers the observation’s loss; a negative one indicates that a small decrease does so. Fitting a shallow regression tree to these pseudo-residuals gives a tree approximation to the negative-gradient direction. The update retains the same additive form,</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_m(x)=\hat F_{m-1}(x)+\nu\hat h_m(x).
</span></p>
</div>
<p>For a general loss, the average pseudo-residual in a leaf provides a gradient-based correction but need not minimize the original loss within that leaf. We can therefore refine the leaf values after choosing the splits: choose each leaf’s correction using the original loss, then apply shrinkage <span class="citation" data-cites="Friedman2001Greedy">(<a href="#ref-Friedman2001Greedy" role="doc-biblioref">J. H. Friedman 2001</a>)</span>.</p>
<p>The loss defines the population risk criterion: the ideal predictor minimizes <span class="math inline">\mathbb{E}[\ell(Y,F(X))]</span>. Changing the loss can change the statistical target, although different losses can target the same quantity.</p>
<p><strong>Classification with Bernoulli Log-Loss</strong></p>
<p>For binary outcomes <span class="math inline">y_i\in\{0,1\}</span>, squared-error boosting still targets the conditional mean, which is the event probability:</p>
<div class="display-math-block">
<p><span class="math display">
\mathbb{E}[Y\mid X=x]=\mathbb{P}(Y=1\mid X=x).
</span></p>
</div>
<p>The fitted values, however, need not stay in <span class="math inline">[0,1]</span>. A classification forest preserves this range by averaging leaf probabilities. Boosting adds signed corrections, so a direct probability fit can leave the range even when its initial constant is a valid probability.</p>
<p>In the Bernoulli construction below, we let the ensemble predict unrestricted log-odds, just as the linear index <span class="math inline">x_i'\beta</span> does in a logit model. The sigmoid converts the ensemble output into a probability:</p>
<div class="display-math-block">
<p><span class="math display">
p_i=\sigma(F(x_i))=\frac{1}{1+e^{-F(x_i)}}.
</span></p>
</div>
<p>The <strong>log-odds</strong>, also called the <strong>logit</strong>, are the logarithm of the odds <span class="math inline">p_i/(1-p_i)</span>:</p>
<div class="display-math-block">
<p><span class="math display">
F(x_i)=\log\left(\frac{p_i}{1-p_i}\right).
</span></p>
</div>
<p>The log-odds can take any real value, and the sigmoid maps every finite updated value into <span class="math inline">(0,1)</span>. We can therefore add tree corrections on the log-odds scale while preserving valid probabilities.</p>
<p>The sigmoid enforces the probability range; the loss is a separate choice. We use the negative log-likelihood of a Bernoulli model. For event probability <span class="math inline">p_i</span>, this model assigns the observed outcome <span class="math inline">y_i</span> probability</p>
<div class="display-math-block">
<p><span class="math display">
p_i^{y_i}(1-p_i)^{1-y_i}.
</span></p>
</div>
<p>Taking its negative logarithm gives the Bernoulli log-loss:</p>
<div class="display-math-block">
<p><span class="math display">
\ell(y_i,F(x_i))
=-\log\!\left[p_i^{y_i}(1-p_i)^{1-y_i}\right]
=-y_i\log p_i-(1-y_i)\log(1-p_i).
</span></p>
</div>
<p>Boosting adds corrections to the model’s log-odds output <span class="math inline">F(x_i)</span>, so we need the derivative with respect to this output. Write <span class="math inline">z</span> for a possible value of <span class="math inline">F(x_i)</span> and <span class="math inline">p=\sigma(z)</span> for the corresponding probability. Holding <span class="math inline">y_i</span> fixed, the sigmoid derivative and the chain rule give</p>
<!-- Keep paragraph last-line centering from overriding the math alignment. -->
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
\frac{dp}{dz}
&amp;=\frac{e^{-z}}{(1+e^{-z})^2}\\
&amp;=p(1-p),\\[0.5em]
\frac{\partial\ell(y_i,z)}{\partial z}
&amp;=\left(-\frac{y_i}{p}+\frac{1-y_i}{1-p}\right)\frac{dp}{dz}\\
&amp;=\left(-\frac{y_i}{p}+\frac{1-y_i}{1-p}\right)p(1-p)\\
&amp;=-y_i(1-p)+(1-y_i)p\\
&amp;=p-y_i\\
&amp;=\sigma(z)-y_i.
\end{aligned}
</span></span></p>
</div>
<p>At iteration <span class="math inline">m</span>, we evaluate this derivative at the current log-odds <span class="math inline">z=\hat F_{m-1}(x_i)</span>, whose corresponding probability is <span class="math inline">p_{i,m-1}=\sigma(\hat F_{m-1}(x_i))</span>. The pseudo-residual is therefore</p>
<div class="display-math-block">
<p><span class="math display">
r_{im}=y_i-p_{i,m-1}.
</span></p>
</div>
<p>The next regression tree thus fits the discrepancy between the binary outcome and the current probability. When both classes occur in the training sample, the loss-minimizing initial probability is <span class="math inline">\bar y</span>, giving <span class="math inline">\hat F_0(x)=\log[\bar y/(1-\bar y)]</span>.</p>
<p>The distinction between the residual and the update matters: <span class="math inline">y_i-p_{i,m-1}</span> compares an outcome with a probability, but the tree’s correction is added to the log-odds <span class="math inline">\hat F_{m-1}</span>. We then recompute the probability using the sigmoid. A common refinement uses a Newton step, which adjusts each leaf correction using the curvature of the Bernoulli loss. The Newton correction also lives on the log-odds scale. Newton’s method is an optional refinement of the gradient step; <span class="math inline">y_i-p_{i,m-1}</span> is already the negative derivative with respect to log-odds. The <a href="#gb-newton-details">optional calculation below</a> gives the details.</p>
<div id="gb-newton-details" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional derivation: Bernoulli leaf corrections
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">R_{jm}</span> denote leaf <span class="math inline">j</span> of the tree at iteration <span class="math inline">m</span>. Once the tree’s splits are fixed, we can choose a common correction <span class="math inline">\gamma</span> for all observations in that leaf by minimizing its original loss <span class="citation" data-cites="Friedman2001Greedy">(<a href="#ref-Friedman2001Greedy" role="doc-biblioref">J. H. Friedman 2001</a>)</span>:</p>
<div class="display-math-block">
<p><span class="math display">
Q_{jm}(\gamma)
=\sum_{i:\,x_i\in R_{jm}}
\ell\bigl(y_i,\hat F_{m-1}(x_i)+\gamma\bigr),
\qquad
\gamma_{jm}^{\star}\in\arg\min_\gamma Q_{jm}(\gamma).
</span></p>
</div>
<p>For squared loss, the minimizing correction is the mean residual in the leaf. For Bernoulli loss, there is generally no closed-form solution. With finite current log-odds, a finite minimizer exists when both classes occur in the leaf. An all-one or all-zero leaf instead approaches its infimum as <span class="math inline">\gamma\to+\infty</span> or <span class="math inline">\gamma\to-\infty</span>, respectively.</p>
<p>A common approximation takes one Newton step from <span class="math inline">\gamma=0</span>. The first and second derivatives there are</p>
<div class="display-math-block">
<p><span class="math display">
Q'_{jm}(0)=\sum_{i:\,x_i\in R_{jm}}(p_{i,m-1}-y_i),
\qquad
Q''_{jm}(0)=\sum_{i:\,x_i\in R_{jm}}p_{i,m-1}(1-p_{i,m-1}).
</span></p>
</div>
<p>Minimizing the quadratic approximation <span class="math inline">Q_{jm}(0)+Q'_{jm}(0)\gamma+\tfrac12Q''_{jm}(0)\gamma^2</span> gives</p>
<div class="display-math-block">
<p><span class="math display">
\widetilde\gamma_{jm}
=-\frac{Q'_{jm}(0)}{Q''_{jm}(0)}
=\frac{\sum_{i:\,x_i\in R_{jm}}(y_i-p_{i,m-1})}
       {\sum_{i:\,x_i\in R_{jm}}p_{i,m-1}(1-p_{i,m-1})}.
</span></p>
</div>
<p>The tilde distinguishes this approximate correction from an exact minimizer <span class="math inline">\gamma_{jm}^{\star}</span>. Using <span class="math inline">\widetilde\gamma_{jm}</span> as the leaf value in <span class="math inline">\hat h_m</span> gives, for <span class="math inline">x_i\in R_{jm}</span>,</p>
<div class="display-math-block">
<p><span class="math display">
p_{im}=\sigma\!\left(\hat F_{m-1}(x_i)+\nu\widetilde\gamma_{jm}\right).
</span></p>
</div>
<p>Even though each pseudo-residual is bounded, the Newton correction need not be: a non-negligible summed residual divided by very small total curvature produces a large log-odds correction. One Newton step can also overshoot and increase the loss. Shrinkage reduces the step size, but no fixed positive learning rate guarantees a loss decrease for every possible leaf and current fit.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Connection to Cross-Entropy
</div>
</div>
<div class="callout-body-container callout-body">
<p>For classification, boosting with Bernoulli log-loss is minimizing cross-entropy, i.e., the negative log-likelihood of a Bernoulli model. The equivalence links boosting directly to the <a href="./information_theory.html#sec-mle-kl-divergence">maximum-likelihood and Kullback–Leibler discussion</a>: fitting the boosted classifier means reducing the discrepancy between observed class outcomes and predicted event probabilities.</p>
</div>
</div>
<p><strong>AdaBoost as Exponential-Loss Boosting</strong></p>
<p>AdaBoost predates gradient boosting and illustrates the same idea with a different loss <span class="citation" data-cites="FreundSchapire1997 FriedmanHastieTibshirani2000">(<a href="#ref-FreundSchapire1997" role="doc-biblioref">Freund and Schapire 1997</a>; <a href="#ref-FriedmanHastieTibshirani2000" role="doc-biblioref">J. Friedman, Hastie, and Tibshirani 2000</a>)</span>. For this comparison, use labels <span class="math inline">y_i\in\{-1,+1\}</span> and let <span class="math inline">F</span> be a real-valued classification score. AdaBoost uses exponential loss,</p>
<div class="display-math-block">
<p><span class="math display">
\ell(y_i,F(x_i))=e^{-y_iF(x_i)}.
</span></p>
</div>
<p>At iteration <span class="math inline">m</span>, AdaBoost fits a classifier using observation weights</p>
<div class="display-math-block">
<p><span class="math display">
w_{im}=e^{-y_i\hat F_{m-1}(x_i)}.
</span></p>
</div>
<p>The product <span class="math inline">y_i\hat F_{m-1}(x_i)</span> is the signed margin: it is positive for a correctly classified observation and negative for a misclassified one. A more negative margin gives a larger weight, so the next classifier places more emphasis on the current mistakes. After fitting that classifier, AdaBoost chooses its weight in the ensemble to minimize the exponential training loss. Only this one weight is optimized at that step; the selected classifier stays fixed.</p>
<p>Exponential loss can assign arbitrarily large weights to confidently misclassified observations. For Bernoulli boosting, with its <span class="math inline">0/1</span> labels, the pseudo-residuals instead satisfy <span class="math inline">|y_i-p_{i,m-1}|&lt;1</span>. That bound limits each observation’s contribution to the gradient at a given iteration; it does not guarantee that the fitted ensemble is insensitive to individual observations.</p>
<div id="gb-adaboost-details" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional derivation: AdaBoost weights and coefficient
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With <span class="math inline">y_i\in\{-1,+1\}</span> and exponential loss, the negative gradient is</p>
<div class="display-math-block">
<p><span class="math display">
r_{im}
=-\left.\frac{\partial\ell(y_i,z)}{\partial z}\right|_{z=\hat F_{m-1}(x_i)}
=y_i\,e^{-y_i\hat F_{m-1}(x_i)}=y_iw_{im}.
</span></p>
</div>
<p>Suppose the weak learner is a classifier with <span class="math inline">h(x_i)\in\{-1,+1\}</span>. Because <span class="math inline">h(x_i)^2=1</span>, its least-squares criterion satisfies</p>
<div class="display-math-block">
<p><span class="math display">
\sum_{i=1}^N\bigl(r_{im}-h(x_i)\bigr)^2
=C_m-2\sum_{i=1}^Nw_{im}y_i h(x_i),
\qquad
C_m=\sum_{i=1}^N(w_{im}^2+1).
</span></p>
</div>
<p>The constant <span class="math inline">C_m</span> does not depend on <span class="math inline">h</span>. Moreover,</p>
<div class="display-math-block">
<p><span class="math display">
\mathbf{1}\{y_i\neq h(x_i)\}=\frac{1-y_i h(x_i)}{2}.
</span></p>
</div>
<p>Minimizing the least-squares criterion is therefore equivalent to minimizing weighted misclassification error. This equivalence relies on the restriction <span class="math inline">h(x_i)\in\{-1,+1\}</span>; it does not apply to the real-valued regression-tree leaves used elsewhere in this chapter.</p>
<p>Write <span class="math inline">\hat g_m(x)\in\{-1,+1\}</span> for the selected classifier and <span class="math inline">\mathrm{err}_m=\sum_i w_{im}\mathbf{1}\{y_i\ne\hat g_m(x_i)\}/\sum_i w_{im}</span> for its weighted misclassification rate. Holding <span class="math inline">\hat g_m</span> fixed, the exponential loss after adding <span class="math inline">\alpha\hat g_m</span> is proportional to</p>
<div class="display-math-block">
<p><span class="math display">
(1-\mathrm{err}_m)e^{-\alpha}+\mathrm{err}_m e^{\alpha}.
</span></p>
</div>
<p>Differentiating with respect to <span class="math inline">\alpha</span> and setting the derivative to zero gives <span class="math inline">e^{2\alpha}=(1-\mathrm{err}_m)/\mathrm{err}_m</span>, hence</p>
<div class="display-math-block">
<p><span class="math display">
\alpha_m=\frac12\log\!\left(\frac{1-\mathrm{err}_m}{\mathrm{err}_m}\right),
\qquad
\hat F_m=\hat F_{m-1}+\alpha_m\hat g_m.
</span></p>
</div>
<p>A finite positive coefficient requires <span class="math inline">0&lt;\mathrm{err}_m&lt;1/2</span>. Error <span class="math inline">1/2</span> gives zero weight; a perfect classifier requires a stopping or finite-step convention. AdaBoost therefore builds the ensemble stage by stage by minimizing exponential loss over each new classifier’s coefficient <span class="citation" data-cites="FriedmanHastieTibshirani2000">(<a href="#ref-FriedmanHastieTibshirani2000" role="doc-biblioref">J. Friedman, Hastie, and Tibshirani 2000</a>)</span>.</p>
<p>The score convention differs from Bernoulli boosting. For <span class="math inline">p(x)=\mathbb{P}(Y=+1\mid X=x)\in(0,1)</span>, minimizing the conditional risk <span class="math inline">p(x)e^{-F}+(1-p(x))e^F</span> gives <span class="math inline">F=\tfrac12\log[p(x)/(1-p(x))]</span>. The corresponding probability map is <span class="math inline">\sigma(2F)</span>, whereas Bernoulli boosting uses <span class="math inline">\sigma(F)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-gb-regularization" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="sec-gb-regularization"><span class="header-section-number">12.6</span> Regularization in Boosting</h2>
<p>Boosting can keep refining the fit indefinitely. That is why regularization is essential, not optional.</p>
<p><strong>Learning Rate</strong></p>
<p>The learning rate <span class="math inline">\nu</span> shrinks each update:</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_m(x) = \hat F_{m-1}(x) + \nu \hat h_m(x).
</span></p>
</div>
<p>Smaller <span class="math inline">\nu</span> means:</p>
<ul>
<li>slower learning</li>
<li>more trees needed</li>
<li>often better generalization, because the fit evolves more cautiously</li>
</ul>
<p>Scaling each update by <span class="math inline">\nu&lt;1</span> is called <strong>shrinkage</strong>. Along the <em>training-risk</em> path, the interaction between <span class="math inline">\nu</span> and <span class="math inline">M</span> is roughly reciprocal: a smaller <span class="math inline">\nu</span> requires correspondingly more iterations to reach the same training risk, so as a heuristic, halving <span class="math inline">\nu</span> roughly doubles the number of trees needed. The validation-optimal <span class="math inline">M</span> is a different matter—if small-<span class="math inline">\nu</span> paths merely retraced the same fits more slowly, shrinkage could not improve generalization. What <span class="citation" data-cites="Friedman2001Greedy">J. H. Friedman (<a href="#ref-Friedman2001Greedy" role="doc-biblioref">2001</a>)</span> reports empirically is the qualitative pattern: smaller <span class="math inline">\nu</span> tends to deliver better test error and requires a correspondingly larger <span class="math inline">M</span>; this is a rule of thumb, not a theorem. <span class="citation" data-cites="ZhangYu2005">Zhang and Yu (<a href="#ref-ZhangYu2005" role="doc-biblioref">2005</a>)</span> supply theoretical support for treating the iteration count as a regularization device.</p>
<p><strong>Number of Trees</strong></p>
<p>The number of iterations <span class="math inline">M</span> controls how long the algorithm keeps refining the fit.</p>
<ul>
<li>too few trees can underfit</li>
<li>too many trees can eventually overfit</li>
<li>the optimal <span class="math inline">M</span> is usually chosen by validation or early stopping—that is, by stopping boosting at the iteration where validation error is minimized (see <a href="#sec-gb-early-stopping" class="quarto-xref">Section&nbsp;12.7</a>)</li>
</ul>
<p><strong>Tree Depth</strong></p>
<p>Depth controls the maximum interaction order available along a root-to-leaf path.</p>
<ul>
<li>depth 1: additive threshold effects only</li>
<li>depth 2: two-way interactions can appear, but need not</li>
<li>deeper trees: higher-order local interactions are permitted, but repeated variables or additive structure can keep the realized interaction order lower</li>
</ul>
<p><strong>Subsampling</strong></p>
<p>Some boosting implementations fit each new tree on a random subsample of the data rather than the full sample. This is called <strong>stochastic gradient boosting</strong> <span class="citation" data-cites="Friedman2002Stochastic">(<a href="#ref-Friedman2002Stochastic" role="doc-biblioref">J. H. Friedman 2002</a>)</span>.</p>
<p>Subsampling can reduce variance and speed computation by making each stage cheaper and less tied to one full-sample pseudo-residual fit. It introduces additional randomness into the stagewise updates, so any predictive benefit must be checked over repeated seeds and with the appropriate validation design.</p>
<p><strong>Monotonicity Constraints</strong></p>
<p>Sometimes the econometrician has credible prior knowledge about the sign of a predictive relationship even if the rest of the conditional mean is complicated. For example, one might regard it as implausible that a higher debt-service burden should <em>lower</em> predicted default risk, or that a tighter financial-conditions index should <em>lower</em> predicted recession risk, all else equal. A monotonicity constraint imposes exactly such a shape restriction on the fitted function.</p>
<p>In a tree-ensemble model, this means restricting the fitted prediction to move only in one direction as a chosen predictor increases, holding the other predictors fixed. The idea is not unique to boosting, but it is especially prominent in modern boosted-tree implementations because it fits naturally into the broader regularization toolkit. This does not make the model structural or causal. It is better understood as a regularization device that uses economic theory to rule out locally implausible wiggles in the prediction surface.</p>
<p>When the sign restriction is well founded, monotonicity constraints can improve credibility, stabilize partial-effect summaries, and prevent the ensemble from fitting noise in directions that contradict economic reasoning. But they are not free. If the true conditional relationship is non-monotone, changes sign across regimes, or is only monotone after conditioning on variables the model does not include, the constraint can introduce systematic misspecification.</p>
<p><strong>How the constraint is enforced.</strong> A monotonicity constraint is a hard restriction on the fitted function, not a penalty added to the loss. The mechanism is the one described in the <a href="./random_forests.html#sec-rf-hyperparameters">random-forests chapter</a>: candidate splits that would violate the requested ordering are rejected, and bounds on leaf values are propagated down the tree. In boosting, each successive tree is constrained in this way, so the accumulated sum of trees respects the ordering as well.</p>
<p><strong>In scikit-learn.</strong> The histogram-based gradient-boosting estimator <code>HistGradientBoostingRegressor</code> accepts a <code>monotonic_cst</code> argument with one integer per feature: <code>+1</code> for increasing, <code>-1</code> for decreasing, and <code>0</code> for no constraint. For three predictors, with the first constrained to have a monotonically increasing effect:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> HistGradientBoostingRegressor</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> HistGradientBoostingRegressor(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    monotonic_cst<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>],</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    max_iter<span class="op">=</span><span class="dv">500</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>See the scikit-learn example <a href="https://scikit-learn.org/stable/auto_examples/ensemble/plot_monotonic_constraints.html">Monotonic Constraints</a> for a visual comparison of constrained and unconstrained fits and a full working interface example.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Implementation Note: Extreme Gradient Boosting (XGBoost)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Implementation Note: Extreme Gradient Boosting (XGBoost)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Extreme gradient boosting (XGBoost) <span class="citation" data-cites="ChenGuestrin2016">(<a href="#ref-ChenGuestrin2016" role="doc-biblioref">Chen and Guestrin 2016</a>)</span> is an optimized implementation family for gradient-boosted trees. Relative to the basic algorithm in this chapter, it adds engineering and regularization features such as efficient split search, <span class="math inline">\ell_1</span> and <span class="math inline">\ell_2</span> penalties, sparse or missing-value handling, monotone constraints, and scalable training. The econometric interpretation remains the same: it is still a tuned predictive tree ensemble, so validation design and the information set are central.</p>
</div>
</div>
<p><a href="#fig-boosting-learning-rate" class="quarto-xref">Figure&nbsp;12.2</a> plots training and validation mean squared error (MSE) along the boosting path for two learning rates, again on simulated data: one predictor, a smooth nonlinearity with a threshold shift, and independent training and validation samples of 280 observations each. The vertical axis is logarithmic, so proportional changes are equally visible everywhere and the behavior near the validation minimum is not compressed by the large initial errors. Because the held-out sample is inspected at every iteration, it is a tuning sample rather than a final test sample.</p>
<div id="cell-fig-boosting-learning-rate" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.ticker <span class="im">import</span> NullFormatter, ScalarFormatter</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> GradientBoostingRegressor</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">77</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>n_train <span class="op">=</span> <span class="dv">280</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>n_validation <span class="op">=</span> <span class="dv">280</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> rng.uniform(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, size<span class="op">=</span>(n_train, <span class="dv">1</span>))</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>X_validation <span class="op">=</span> rng.uniform(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, size<span class="op">=</span>(n_validation, <span class="dv">1</span>))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> g(x):</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> x[:, <span class="dv">0</span>]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.sin(<span class="fl">1.5</span> <span class="op">*</span> z) <span class="op">+</span> <span class="fl">0.4</span> <span class="op">*</span> z <span class="op">+</span> <span class="fl">0.7</span> <span class="op">*</span> (z <span class="op">&gt;</span> <span class="fl">1.0</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> g(X_train) <span class="op">+</span> rng.normal(scale<span class="op">=</span><span class="fl">0.35</span>, size<span class="op">=</span>n_train)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>y_validation <span class="op">=</span> g(X_validation) <span class="op">+</span> rng.normal(scale<span class="op">=</span><span class="fl">0.35</span>, size<span class="op">=</span>n_validation)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>configs <span class="op">=</span> [(<span class="fl">0.05</span>, <span class="st">"C0"</span>), (<span class="fl">0.2</span>, <span class="st">"C3"</span>)]</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lr, color <span class="kw">in</span> configs:</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> GradientBoostingRegressor(</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>        n_estimators<span class="op">=</span><span class="dv">180</span>,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>        learning_rate<span class="op">=</span>lr,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>        max_depth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>        min_samples_leaf<span class="op">=</span><span class="dv">6</span>,</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        random_state<span class="op">=</span><span class="dv">77</span>,</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    model.fit(X_train, y_train)</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    initial_prediction <span class="op">=</span> np.mean(y_train)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    train_mse <span class="op">=</span> [np.mean((y_train <span class="op">-</span> initial_prediction) <span class="op">**</span> <span class="dv">2</span>)]</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    validation_mse <span class="op">=</span> [np.mean((y_validation <span class="op">-</span> initial_prediction) <span class="op">**</span> <span class="dv">2</span>)]</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> pred_train, pred_validation <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>        model.staged_predict(X_train), model.staged_predict(X_validation)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>    ):</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>        train_mse.append(np.mean((y_train <span class="op">-</span> pred_train) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>        validation_mse.append(np.mean((y_validation <span class="op">-</span> pred_validation) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    tree_counts <span class="op">=</span> np.arange(<span class="bu">len</span>(train_mse))</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[<span class="dv">0</span>] <span class="cf">if</span> lr <span class="op">==</span> <span class="fl">0.05</span> <span class="cf">else</span> axes[<span class="dv">1</span>]</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>    ax.plot(tree_counts, train_mse, label<span class="op">=</span><span class="st">"Training MSE"</span>, color<span class="op">=</span><span class="st">"C0"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    ax.plot(tree_counts, validation_mse, label<span class="op">=</span><span class="st">"Validation MSE"</span>, color<span class="op">=</span><span class="st">"C3"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"Learning rate = </span><span class="sc">{</span>lr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Number of trees"</span>)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>    ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Mean squared error (log scale)"</span>)</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yscale(<span class="st">"log"</span>)</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yticks([<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].yaxis.set_major_formatter(ScalarFormatter())</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].yaxis.set_minor_formatter(NullFormatter())</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-boosting-learning-rate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boosting-learning-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="gradient_boosting_files/figure-html/fig-boosting-learning-rate-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boosting-learning-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Training MSE (blue) and independent validation-sample MSE (red) from the initial constant model at zero trees through 180 boosting iterations, shown on a logarithmic vertical axis. The validation path is available for choosing the iteration count, so it is not a final test evaluation. The left panel uses a learning rate of 0.05; the right panel uses 0.2.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The smaller learning rate gives a flatter, more forgiving validation-error profile—so flat here that its minimum has not clearly been reached within the 180 iterations plotted, so the grid’s upper bound rather than the validation curve would determine the stopping point. With the larger learning rate, validation error falls more quickly, reaches its minimum within the first few dozen trees, and then drifts mildly upward.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Question for Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question for Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>If two boosted models have similar validation error, what evidence from the validation curve would justify the small-learning-rate, many-tree model, and what evidence would justify the larger-learning-rate, fewer-tree model?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggested Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A small learning rate with many trees is better supported when its validation curve is flatter near the minimum, making performance less sensitive to the chosen stopping point. A larger learning rate with fewer trees is better supported when it reaches similar validation error with fewer boosting steps and lower computational cost. For forecasting, compare validation loss over the relevant forecast origins; for prediction with independent and identically distributed (i.i.d.) observations, use an appropriate independent validation sample. Training fit alone does not settle the comparison.</p>
</div>
</div>
</div>
<p>Real macroeconomic data can be less forgiving. <a href="#fig-gb-fredqd" class="quarto-xref">Figure&nbsp;12.3</a> shows training and validation MSE curves—again on a logarithmic vertical axis—for annualized gross domestic product (GDP) growth in quarter <span class="math inline">t+1</span> from the quarterly Federal Reserve Economic Data collection (FRED-QD) developed by <span class="citation" data-cites="McCrackenNg2020FREDQD">McCracken and Ng (<a href="#ref-McCrackenNg2020FREDQD" role="doc-biblioref">2020</a>)</span>; the <a href="./datasets.html#fred-qd">data appendix</a> documents the repository copy. The five predictors are dated quarter <span class="math inline">t</span>: GDP growth, inflation, the term spread, the log of the volatility index (VIX), and the unemployment rate. The evaluation uses a fixed-estimation-window, time-ordered 75/25 holdout: each model is fitted once on the first 75% of quarters—forecast origins 1962Q3 through 2009Q2—and evaluated, without re-estimation, on the remaining 25%, origins 2009Q3 through 2025Q1.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Training MSE falls steadily in both panels. Neither validation curve improves on the stage-zero constant forecast: both attain their global minimum at zero trees, although they fluctuate locally thereafter. The learning rate governs how fast the deterioration accumulates—gradually at <span class="math inline">\nu = 0.02</span>, faster and more erratically at <span class="math inline">\nu = 0.2</span>. On the logarithmic axis this deterioration looks mild—about 6% of the zero-tree level at <span class="math inline">\nu=0.02</span> and 16% at <span class="math inline">\nu=0.2</span>—while the training MSE falls to roughly half and a tenth of its starting value, respectively; the widening gap between the two curves is the clearest visual sign that the added flexibility buys nothing out of sample.</p>
<p>The immediate deterioration is worth confronting rather than hiding. The lesson of early stopping is not that boosting always improves for a while and then degrades; it is that the iteration count is a regularization dial whose right setting is chosen on held-out data, and here the honest setting is no boosting at all. That zero-tree conclusion is conditional on this split and on keeping the model fitted on the training quarters fixed rather than re-estimating it; a recursive or rolling design that refits at each forecast origin estimates a different deployment risk and could select a different stopping point. The result is not driven solely by the four 2020 outcomes: dropping those validation targets leaves the minimum of both validation curves at zero trees. Those quarters strongly affect the <em>level</em> of the validation MSE—the 2020 contraction and rebound generate residuals of tens of annualized percentage points, and removing those quarters cuts the zero-tree validation MSE by an order of magnitude. Under this fixed-estimation design, these predictors and boosting settings yield no validation gain over the constant. Weak usable signal, instability in the predictive relationship, and estimation error could all contribute; the exclusion check does not distinguish them. In the synthetic example above, the data-generating process is known to be stable and to contain nonlinear signal, and validation error improves substantially on the constant model before flattening out.</p>
<div id="cell-fig-gb-fredqd" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.ticker <span class="im">import</span> NullFormatter, ScalarFormatter</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> GradientBoostingRegressor</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> pd.read_csv(<span class="st">"data/fred_qd_current.csv"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>fred_qd <span class="op">=</span> raw.iloc[<span class="dv">2</span>:].copy()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>fred_qd[<span class="st">"sasdate"</span>] <span class="op">=</span> pd.to_datetime(fred_qd[<span class="st">"sasdate"</span>])</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> fred_qd.columns:</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> col <span class="op">!=</span> <span class="st">"sasdate"</span>:</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>        fred_qd[col] <span class="op">=</span> pd.to_numeric(fred_qd[col], errors<span class="op">=</span><span class="st">"coerce"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>fred_qd <span class="op">=</span> fred_qd.sort_values(<span class="st">"sasdate"</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>gdp_growth  <span class="op">=</span> <span class="dv">400</span> <span class="op">*</span> np.log(fred_qd[<span class="st">"GDPC1"</span>]).diff()</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>inflation   <span class="op">=</span> <span class="dv">400</span> <span class="op">*</span> np.log(fred_qd[<span class="st">"CPIAUCSL"</span>]).diff()</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>term_spread <span class="op">=</span> fred_qd[<span class="st">"GS10"</span>] <span class="op">-</span> fred_qd[<span class="st">"TB3MS"</span>]</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>log_vix     <span class="op">=</span> np.log(fred_qd[<span class="st">"VIXCLSx"</span>])</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>macro <span class="op">=</span> pd.DataFrame({</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"y"</span>:           gdp_growth.shift(<span class="op">-</span><span class="dv">1</span>),</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"gdp_lag1"</span>:    gdp_growth,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"infl_lag1"</span>:   inflation,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"spread_lag1"</span>: term_spread,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"vix_lag1"</span>:    log_vix,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unrate_lag1"</span>: fred_qd[<span class="st">"UNRATE"</span>],</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>}).dropna()</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>feature_cols <span class="op">=</span> [<span class="st">"gdp_lag1"</span>, <span class="st">"infl_lag1"</span>, <span class="st">"spread_lag1"</span>, <span class="st">"vix_lag1"</span>, <span class="st">"unrate_lag1"</span>]</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> <span class="bu">int</span>(<span class="bu">len</span>(macro) <span class="op">*</span> <span class="fl">0.75</span>)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> macro.iloc[:split][feature_cols].values</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> macro.iloc[:split][<span class="st">"y"</span>].values</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>X_validation <span class="op">=</span> macro.iloc[split:][feature_cols].values</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>y_validation <span class="op">=</span> macro.iloc[split:][<span class="st">"y"</span>].values</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>configs <span class="op">=</span> [(<span class="fl">0.02</span>, <span class="st">"C0"</span>), (<span class="fl">0.2</span>, <span class="st">"C3"</span>)]</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (lr, _), ax <span class="kw">in</span> <span class="bu">zip</span>(configs, axes):</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> GradientBoostingRegressor(</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>        n_estimators<span class="op">=</span><span class="dv">250</span>, learning_rate<span class="op">=</span>lr, max_depth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>        min_samples_leaf<span class="op">=</span><span class="dv">6</span>, random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>    model.fit(X_train, y_train)</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>    initial_prediction <span class="op">=</span> np.mean(y_train)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>    train_mse <span class="op">=</span> [np.mean((y_train <span class="op">-</span> initial_prediction) <span class="op">**</span> <span class="dv">2</span>)]</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>    val_mse <span class="op">=</span> [np.mean((y_validation <span class="op">-</span> initial_prediction) <span class="op">**</span> <span class="dv">2</span>)]</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> p_tr, p_val <span class="kw">in</span> <span class="bu">zip</span>(model.staged_predict(X_train), model.staged_predict(X_validation)):</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>        train_mse.append(np.mean((y_train <span class="op">-</span> p_tr) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>        val_mse.append(np.mean((y_validation <span class="op">-</span> p_val) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>    tree_counts <span class="op">=</span> np.arange(<span class="bu">len</span>(train_mse))</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>    ax.plot(tree_counts, train_mse, color<span class="op">=</span><span class="st">"C0"</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Training MSE"</span>)</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>    ax.plot(tree_counts, val_mse,   color<span class="op">=</span><span class="st">"C3"</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Validation MSE"</span>)</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"Learning rate = </span><span class="sc">{</span>lr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Number of trees"</span>)</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>    ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Mean squared error (log scale)"</span>)</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yscale(<span class="st">"log"</span>)</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yticks([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>])</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].yaxis.set_major_formatter(ScalarFormatter())</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].yaxis.set_minor_formatter(NullFormatter())</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-gb-fredqd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gb-fredqd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="gradient_boosting_files/figure-html/fig-gb-fredqd-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gb-fredqd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Training MSE (blue) and time-ordered validation MSE (red) for one-step-ahead GDP growth from FRED-QD, shown on a logarithmic vertical axis. Both panels include the initial constant model at zero trees followed by 250 depth-2 trees; the left panel uses a learning rate of 0.02 and the right panel 0.2.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The zero-tree minima in <a href="#fig-gb-fredqd" class="quarto-xref">Figure&nbsp;12.3</a> show why an early-stopping rule must be allowed to retain the initial constant model rather than being forced to select at least one tree.</p>
</section>
<section id="sec-gb-early-stopping" class="level2" data-number="12.7">
<h2 data-number="12.7" class="anchored" data-anchor-id="sec-gb-early-stopping"><span class="header-section-number">12.7</span> Early Stopping and Validation</h2>
<p>Because boosting can continue to improve the training fit for many iterations, some external criterion is needed to decide when to stop. Early stopping uses a validation set or validation path to choose the number of trees, and it is one of the central regularization devices of boosting—not a minor implementation detail.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Econometric Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>For forecasting applications, early stopping must be based on time-ordered validation data. Random <span class="math inline">K</span>-fold validation contaminates the forecast-origin information set by allowing later observations into training folds. It can therefore select a materially different stopping point from a real-time design; when future observations reveal useful related structure, it often favors an overly flexible path, but the direction is data-dependent under drift or structural change.</p>
</div>
</div>
<p>The validation design should mirror the actual forecast exercise:</p>
<ul>
<li>rolling or expanding windows for time series</li>
<li>group-aware validation for clustered or panel-style dependence—folds built so that all observations from the same group (borrower, firm, region) stay together</li>
<li>leakage-safe preprocessing inside each training fold</li>
</ul>
<p>Once validation selects the learning rate, depth, and stopping point, assess the chosen procedure on an untouched test sample or a subsequent forecast period. The smallest loss on the tuning path is not an independent estimate of the selected model’s performance.</p>
</section>
<section id="sec-gb-credit-default" class="level2" data-number="12.8">
<h2 data-number="12.8" class="anchored" data-anchor-id="sec-gb-credit-default"><span class="header-section-number">12.8</span> Empirical Comparison: Credit-Default Probabilities</h2>
<p>The three tree-based chapters introduce a single tree, a random forest, and gradient boosting separately. We can now compare them on one common task. The <a href="./datasets.html#sec-taiwan-credit-default">Taiwan credit-card default data</a> contain records for 30,000 clients, including a binary indicator for default in the month after six months of observed repayment histories <span class="citation" data-cites="Yeh2009CreditDefaultData YehLien2009">(<a href="#ref-Yeh2009CreditDefaultData" role="doc-biblioref">Yeh 2009</a>; <a href="#ref-YehLien2009" role="doc-biblioref">Yeh and Lien 2009</a>)</span>. The predictors also include the granted credit limit, bill and payment amounts, age, and coded demographic characteristics.</p>
<p>The design exactly reuses the stratified 60% training, 20% validation, and 20% test split from the <a href="./feed_forward_nns.html#sec-ffn-credit-default">feed-forward networks chapter</a>. This reuse makes the model scores directly comparable, but it does not create a second independent test of the neural network. The network architecture remains fixed at the eight-unit, one-hidden-layer candidate selected there; we do not alter it after seeing its earlier test result.</p>
<p>The single-tree and random-forest settings are chosen by validation log loss from small candidate sets declared in the code. For boosting, the learning rate and depth come from a small grid, and the number of trees is chosen by early stopping: the validation log loss is tracked from the initial constant prediction through each grid point’s staged predictions, and the iteration with the smallest loss is kept. Exact ties along a path favor fewer trees. If zero trees wins, we retain a constant-probability model and re-estimate its probability on the combined training and validation samples before testing. The iteration count is thus tuned jointly with the learning rate. The comparison uses the same transformed predictors for every model: continuous variables are standardized and categorical variables are one-hot encoded. Standardization helps numerical optimization for logistic regression and the network. It does not change a tree’s available split order because it is a strictly increasing transformation, but using one representation removes an incidental difference between the model pipelines. One consequence of the encoding is not incidental, though: the repayment-status codes are ordered categories (months of payment delay), and one-hot encoding discards the ordering, so no single split can implement a threshold rule such as “delay of two months or more”; the tree-based models must assemble such rules from several level-versus-rest splits. We accept this to keep one representation for all models; an ordinal encoding could well favor the tree-based methods. All transformations are estimated without the test observations.</p>
<p>We evaluate the final probability forecasts by log loss, by the Brier score <span class="math inline">N_{\mathrm{test}}^{-1}\sum_{i=1}^{N_{\mathrm{test}}}(y_i-\hat p_i)^2</span>, and by accuracy after applying a 0.5 threshold. Log loss and the Brier score evaluate the probabilities themselves; accuracy evaluates one particular binary decision rule.</p>
<div class="cell" data-tbl-pos="H" data-execution_count="5">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> book_tables <span class="im">import</span> display_styled_table</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.base <span class="im">import</span> clone</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.compose <span class="im">import</span> ColumnTransformer</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.dummy <span class="im">import</span> DummyClassifier</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> GradientBoostingClassifier, RandomForestClassifier</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, brier_score_loss, log_loss</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neural_network <span class="im">import</span> MLPClassifier</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OneHotEncoder, StandardScaler</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>credit_default <span class="op">=</span> pd.read_csv(<span class="st">"data/credit_card_default_taiwan.csv"</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> credit_default[<span class="st">"default_next_month"</span>]</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> credit_default.drop(columns<span class="op">=</span>[<span class="st">"id"</span>, <span class="st">"default_next_month"</span>])</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>categorical_columns <span class="op">=</span> [</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sex_code"</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"education_code"</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"marriage_code"</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"repay_status_sep"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"repay_status_aug"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"repay_status_jul"</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"repay_status_jun"</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"repay_status_may"</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"repay_status_apr"</span>,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>continuous_columns <span class="op">=</span> [</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    column <span class="cf">for</span> column <span class="kw">in</span> X.columns <span class="cf">if</span> column <span class="kw">not</span> <span class="kw">in</span> categorical_columns</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>X_development, X_test, y_development, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.20</span>, stratify<span class="op">=</span>y, random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>X_train, X_validation, y_train, y_validation <span class="op">=</span> train_test_split(</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    X_development,</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    y_development,</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    test_size<span class="op">=</span><span class="fl">0.25</span>,</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    stratify<span class="op">=</span>y_development,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_preprocessor():</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ColumnTransformer(</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>        [</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>            (<span class="st">"continuous"</span>, StandardScaler(), continuous_columns),</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>            (</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>                <span class="st">"categorical"</span>,</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>                OneHotEncoder(</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>                    drop<span class="op">=</span><span class="st">"first"</span>,</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>                    handle_unknown<span class="op">=</span><span class="st">"ignore"</span>,</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>                    sparse_output<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>                ),</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>                categorical_columns,</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>            ),</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>        ]</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Use training-only transformations for model selection.</span></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>selection_preprocessor <span class="op">=</span> make_preprocessor()</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>X_train_transformed <span class="op">=</span> selection_preprocessor.fit_transform(X_train)</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>X_validation_transformed <span class="op">=</span> selection_preprocessor.transform(X_validation)</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> select_by_log_loss(candidates):</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>    fitted_candidates <span class="op">=</span> []</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> setting, model <span class="kw">in</span> candidates:</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>        model.fit(X_train_transformed, y_train)</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>        probability <span class="op">=</span> model.predict_proba(X_validation_transformed)[:, <span class="dv">1</span>]</span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>        fitted_candidates.append(</span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>            (log_loss(y_validation, probability), setting, model)</span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">min</span>(fitted_candidates, key<span class="op">=</span><span class="kw">lambda</span> result: result[<span class="dv">0</span>])</span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>tree_candidates <span class="op">=</span> [</span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a>    (</span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"depth </span><span class="sc">{</span>depth<span class="sc">}</span><span class="ss">, leaf </span><span class="sc">{</span>leaf<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>        DecisionTreeClassifier(</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>            max_depth<span class="op">=</span>depth,</span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a>            min_samples_leaf<span class="op">=</span>leaf,</span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>            random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> depth <span class="kw">in</span> [<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>]</span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> leaf <span class="kw">in</span> [<span class="dv">20</span>, <span class="dv">100</span>]</span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a>forest_candidates <span class="op">=</span> [</span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a>    (</span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"300 trees, max features </span><span class="sc">{</span>max_features<span class="sc">}</span><span class="ss">, leaf </span><span class="sc">{</span>leaf<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a>        RandomForestClassifier(</span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a>            n_estimators<span class="op">=</span><span class="dv">300</span>,</span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a>            max_features<span class="op">=</span>max_features,</span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a>            min_samples_leaf<span class="op">=</span>leaf,</span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a>            n_jobs<span class="op">=-</span><span class="dv">1</span>,</span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a>            random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> max_features <span class="kw">in</span> [<span class="st">"sqrt"</span>, <span class="fl">0.5</span>]</span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> leaf <span class="kw">in</span> [<span class="dv">5</span>, <span class="dv">20</span>, <span class="dv">50</span>]</span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a>_, tree_setting, selected_tree <span class="op">=</span> select_by_log_loss(tree_candidates)</span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a>_, forest_setting, selected_forest <span class="op">=</span> select_by_log_loss(forest_candidates)</span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a><span class="co"># Boosting: for each (rate, depth) grid point, the number of trees is</span></span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a><span class="co"># chosen by early stopping, including the initial constant at zero trees.</span></span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a>initial_validation_loss <span class="op">=</span> log_loss(</span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a>    y_validation, np.full(<span class="bu">len</span>(y_validation), y_train.mean())</span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-112"><a href="#cb5-112" aria-hidden="true" tabindex="-1"></a>boosting_results <span class="op">=</span> []</span>
<span id="cb5-113"><a href="#cb5-113" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> rate <span class="kw">in</span> [<span class="fl">0.1</span>, <span class="fl">0.05</span>]:</span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> depth <span class="kw">in</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>]:</span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a>        path_model <span class="op">=</span> GradientBoostingClassifier(</span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a>            n_estimators<span class="op">=</span><span class="dv">400</span>,</span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a>            learning_rate<span class="op">=</span>rate,</span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a>            max_depth<span class="op">=</span>depth,</span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a>            min_samples_leaf<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a>            random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a>        path_model.fit(X_train_transformed, y_train)</span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a>        staged_losses <span class="op">=</span> [initial_validation_loss]</span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a>        staged_losses.extend(</span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a>            log_loss(y_validation, staged[:, <span class="dv">1</span>])</span>
<span id="cb5-126"><a href="#cb5-126" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> staged <span class="kw">in</span> path_model.staged_predict_proba(</span>
<span id="cb5-127"><a href="#cb5-127" aria-hidden="true" tabindex="-1"></a>                X_validation_transformed</span>
<span id="cb5-128"><a href="#cb5-128" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb5-129"><a href="#cb5-129" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-130"><a href="#cb5-130" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Index zero is the constant; argmin favors fewer trees on exact ties.</span></span>
<span id="cb5-131"><a href="#cb5-131" aria-hidden="true" tabindex="-1"></a>        best_m <span class="op">=</span> <span class="bu">int</span>(np.argmin(staged_losses))</span>
<span id="cb5-132"><a href="#cb5-132" aria-hidden="true" tabindex="-1"></a>        boosting_results.append((<span class="bu">min</span>(staged_losses), rate, depth, best_m))</span>
<span id="cb5-133"><a href="#cb5-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-134"><a href="#cb5-134" aria-hidden="true" tabindex="-1"></a>_, boosting_rate, boosting_depth, boosting_m <span class="op">=</span> <span class="bu">min</span>(boosting_results)</span>
<span id="cb5-135"><a href="#cb5-135" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> boosting_m <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb5-136"><a href="#cb5-136" aria-hidden="true" tabindex="-1"></a>    boosting_setting <span class="op">=</span> <span class="st">"0 trees (constant probability)"</span></span>
<span id="cb5-137"><a href="#cb5-137" aria-hidden="true" tabindex="-1"></a>    <span class="co"># fit() below re-estimates the class probability on the development sample.</span></span>
<span id="cb5-138"><a href="#cb5-138" aria-hidden="true" tabindex="-1"></a>    selected_boosting <span class="op">=</span> DummyClassifier(strategy<span class="op">=</span><span class="st">"prior"</span>)</span>
<span id="cb5-139"><a href="#cb5-139" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb5-140"><a href="#cb5-140" aria-hidden="true" tabindex="-1"></a>    boosting_setting <span class="op">=</span> <span class="ss">f"rate </span><span class="sc">{</span>boosting_rate<span class="sc">}</span><span class="ss">, depth </span><span class="sc">{</span>boosting_depth<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>boosting_m<span class="sc">}</span><span class="ss"> trees"</span></span>
<span id="cb5-141"><a href="#cb5-141" aria-hidden="true" tabindex="-1"></a>    selected_boosting <span class="op">=</span> GradientBoostingClassifier(</span>
<span id="cb5-142"><a href="#cb5-142" aria-hidden="true" tabindex="-1"></a>        n_estimators<span class="op">=</span>boosting_m,</span>
<span id="cb5-143"><a href="#cb5-143" aria-hidden="true" tabindex="-1"></a>        learning_rate<span class="op">=</span>boosting_rate,</span>
<span id="cb5-144"><a href="#cb5-144" aria-hidden="true" tabindex="-1"></a>        max_depth<span class="op">=</span>boosting_depth,</span>
<span id="cb5-145"><a href="#cb5-145" aria-hidden="true" tabindex="-1"></a>        min_samples_leaf<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb5-146"><a href="#cb5-146" aria-hidden="true" tabindex="-1"></a>        random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-147"><a href="#cb5-147" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-148"><a href="#cb5-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-149"><a href="#cb5-149" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-estimate all preprocessing on the development sample before testing.</span></span>
<span id="cb5-150"><a href="#cb5-150" aria-hidden="true" tabindex="-1"></a>final_preprocessor <span class="op">=</span> make_preprocessor()</span>
<span id="cb5-151"><a href="#cb5-151" aria-hidden="true" tabindex="-1"></a>X_development_transformed <span class="op">=</span> final_preprocessor.fit_transform(X_development)</span>
<span id="cb5-152"><a href="#cb5-152" aria-hidden="true" tabindex="-1"></a>X_test_transformed <span class="op">=</span> final_preprocessor.transform(X_test)</span>
<span id="cb5-153"><a href="#cb5-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-154"><a href="#cb5-154" aria-hidden="true" tabindex="-1"></a>final_models <span class="op">=</span> {</span>
<span id="cb5-155"><a href="#cb5-155" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Logistic regression"</span>: (</span>
<span id="cb5-156"><a href="#cb5-156" aria-hidden="true" tabindex="-1"></a>        <span class="st">"No penalty"</span>,</span>
<span id="cb5-157"><a href="#cb5-157" aria-hidden="true" tabindex="-1"></a>        LogisticRegression(penalty<span class="op">=</span><span class="va">None</span>, max_iter<span class="op">=</span><span class="dv">1000</span>),</span>
<span id="cb5-158"><a href="#cb5-158" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-159"><a href="#cb5-159" aria-hidden="true" tabindex="-1"></a>    <span class="st">"FNN"</span>: (</span>
<span id="cb5-160"><a href="#cb5-160" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Hidden layer 8"</span>,</span>
<span id="cb5-161"><a href="#cb5-161" aria-hidden="true" tabindex="-1"></a>        MLPClassifier(</span>
<span id="cb5-162"><a href="#cb5-162" aria-hidden="true" tabindex="-1"></a>            hidden_layer_sizes<span class="op">=</span>(<span class="dv">8</span>,),</span>
<span id="cb5-163"><a href="#cb5-163" aria-hidden="true" tabindex="-1"></a>            activation<span class="op">=</span><span class="st">"relu"</span>,</span>
<span id="cb5-164"><a href="#cb5-164" aria-hidden="true" tabindex="-1"></a>            solver<span class="op">=</span><span class="st">"adam"</span>,</span>
<span id="cb5-165"><a href="#cb5-165" aria-hidden="true" tabindex="-1"></a>            alpha<span class="op">=</span><span class="fl">0.0</span>,</span>
<span id="cb5-166"><a href="#cb5-166" aria-hidden="true" tabindex="-1"></a>            batch_size<span class="op">=</span><span class="dv">256</span>,</span>
<span id="cb5-167"><a href="#cb5-167" aria-hidden="true" tabindex="-1"></a>            learning_rate_init<span class="op">=</span><span class="fl">0.001</span>,</span>
<span id="cb5-168"><a href="#cb5-168" aria-hidden="true" tabindex="-1"></a>            max_iter<span class="op">=</span><span class="dv">500</span>,</span>
<span id="cb5-169"><a href="#cb5-169" aria-hidden="true" tabindex="-1"></a>            tol<span class="op">=</span><span class="fl">1e-4</span>,</span>
<span id="cb5-170"><a href="#cb5-170" aria-hidden="true" tabindex="-1"></a>            n_iter_no_change<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb5-171"><a href="#cb5-171" aria-hidden="true" tabindex="-1"></a>            random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-172"><a href="#cb5-172" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb5-173"><a href="#cb5-173" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-174"><a href="#cb5-174" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Classification tree"</span>: (tree_setting, clone(selected_tree)),</span>
<span id="cb5-175"><a href="#cb5-175" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Random forest"</span>: (forest_setting, clone(selected_forest)),</span>
<span id="cb5-176"><a href="#cb5-176" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Gradient boosting"</span>: (boosting_setting, clone(selected_boosting)),</span>
<span id="cb5-177"><a href="#cb5-177" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-178"><a href="#cb5-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-179"><a href="#cb5-179" aria-hidden="true" tabindex="-1"></a>test_probabilities <span class="op">=</span> {</span>
<span id="cb5-180"><a href="#cb5-180" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Constant probability"</span>: np.full(<span class="bu">len</span>(y_test), y_development.mean())</span>
<span id="cb5-181"><a href="#cb5-181" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-182"><a href="#cb5-182" aria-hidden="true" tabindex="-1"></a>selected_settings <span class="op">=</span> {<span class="st">"Constant probability"</span>: <span class="st">"Development mean"</span>}</span>
<span id="cb5-183"><a href="#cb5-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-184"><a href="#cb5-184" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (setting, model) <span class="kw">in</span> final_models.items():</span>
<span id="cb5-185"><a href="#cb5-185" aria-hidden="true" tabindex="-1"></a>    model.fit(X_development_transformed, y_development)</span>
<span id="cb5-186"><a href="#cb5-186" aria-hidden="true" tabindex="-1"></a>    test_probabilities[name] <span class="op">=</span> model.predict_proba(X_test_transformed)[:, <span class="dv">1</span>]</span>
<span id="cb5-187"><a href="#cb5-187" aria-hidden="true" tabindex="-1"></a>    selected_settings[name] <span class="op">=</span> setting</span>
<span id="cb5-188"><a href="#cb5-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-189"><a href="#cb5-189" aria-hidden="true" tabindex="-1"></a>comparison <span class="op">=</span> pd.DataFrame(</span>
<span id="cb5-190"><a href="#cb5-190" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb5-191"><a href="#cb5-191" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb5-192"><a href="#cb5-192" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Model"</span>: name,</span>
<span id="cb5-193"><a href="#cb5-193" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Selected setting"</span>: selected_settings[name],</span>
<span id="cb5-194"><a href="#cb5-194" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Log loss"</span>: log_loss(y_test, probability),</span>
<span id="cb5-195"><a href="#cb5-195" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Brier score"</span>: brier_score_loss(y_test, probability),</span>
<span id="cb5-196"><a href="#cb5-196" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Accuracy at 0.5"</span>: accuracy_score(y_test, probability <span class="op">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb5-197"><a href="#cb5-197" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb5-198"><a href="#cb5-198" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> name, probability <span class="kw">in</span> test_probabilities.items()</span>
<span id="cb5-199"><a href="#cb5-199" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb5-200"><a href="#cb5-200" aria-hidden="true" tabindex="-1"></a>).set_index(<span class="st">"Model"</span>)</span>
<span id="cb5-201"><a href="#cb5-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-202"><a href="#cb5-202" aria-hidden="true" tabindex="-1"></a>best_cell_style <span class="op">=</span> <span class="st">"background-color: #d9ead3; font-weight: bold;"</span></span>
<span id="cb5-203"><a href="#cb5-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-204"><a href="#cb5-204" aria-hidden="true" tabindex="-1"></a>display_styled_table(</span>
<span id="cb5-205"><a href="#cb5-205" aria-hidden="true" tabindex="-1"></a>    comparison.style</span>
<span id="cb5-206"><a href="#cb5-206" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">format</span>(</span>
<span id="cb5-207"><a href="#cb5-207" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb5-208"><a href="#cb5-208" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Log loss"</span>: <span class="st">"</span><span class="sc">{:.4f}</span><span class="st">"</span>,</span>
<span id="cb5-209"><a href="#cb5-209" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Brier score"</span>: <span class="st">"</span><span class="sc">{:.4f}</span><span class="st">"</span>,</span>
<span id="cb5-210"><a href="#cb5-210" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Accuracy at 0.5"</span>: <span class="st">"</span><span class="sc">{:.4f}</span><span class="st">"</span>,</span>
<span id="cb5-211"><a href="#cb5-211" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb5-212"><a href="#cb5-212" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-213"><a href="#cb5-213" aria-hidden="true" tabindex="-1"></a>    .highlight_min(</span>
<span id="cb5-214"><a href="#cb5-214" aria-hidden="true" tabindex="-1"></a>        subset<span class="op">=</span>[<span class="st">"Log loss"</span>, <span class="st">"Brier score"</span>],</span>
<span id="cb5-215"><a href="#cb5-215" aria-hidden="true" tabindex="-1"></a>        props<span class="op">=</span>best_cell_style,</span>
<span id="cb5-216"><a href="#cb5-216" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-217"><a href="#cb5-217" aria-hidden="true" tabindex="-1"></a>    .highlight_max(</span>
<span id="cb5-218"><a href="#cb5-218" aria-hidden="true" tabindex="-1"></a>        subset<span class="op">=</span>[<span class="st">"Accuracy at 0.5"</span>],</span>
<span id="cb5-219"><a href="#cb5-219" aria-hidden="true" tabindex="-1"></a>        props<span class="op">=</span>best_cell_style,</span>
<span id="cb5-220"><a href="#cb5-220" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-221"><a href="#cb5-221" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-gb-credit-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gb-credit-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.1: Probability-forecast performance on the common 6,000-client test sample from the Taiwan credit-card default data. Hyperparameters for the FNN and the three tree-based methods are chosen by validation log loss; for gradient boosting, the number of trees is additionally chosen by early stopping along the validation path. Logistic regression has no tuned hyperparameter. All nonconstant models are then refitted on the combined training and validation samples. Lower log loss and Brier score are better; higher accuracy under the 0.5 threshold is better.
</figcaption>
<div aria-describedby="tbl-gb-credit-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_20678_row4_col3, #T_20678_row5_col1, #T_20678_row5_col2 {
  background-color: #d9ead3;
  font-weight: bold;
}
</style>

<table id="T_20678" class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_20678_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Selected setting</th>
<th id="T_20678_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Log loss</th>
<th id="T_20678_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Brier score</th>
<th id="T_20678_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Accuracy at 0.5</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_20678_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">Constant probability</td>
<td id="T_20678_row0_col0" class="data row0 col0">Development mean</td>
<td id="T_20678_row0_col1" class="data row0 col1">0.5284</td>
<td id="T_20678_row0_col2" class="data row0 col2">0.1723</td>
<td id="T_20678_row0_col3" class="data row0 col3">0.7788</td>
</tr>
<tr class="even">
<td id="T_20678_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">Logistic regression</td>
<td id="T_20678_row1_col0" class="data row1 col0">No penalty</td>
<td id="T_20678_row1_col1" class="data row1 col1">0.4431</td>
<td id="T_20678_row1_col2" class="data row1 col2">0.1390</td>
<td id="T_20678_row1_col3" class="data row1 col3">0.8170</td>
</tr>
<tr class="odd">
<td id="T_20678_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">FNN</td>
<td id="T_20678_row2_col0" class="data row2 col0">Hidden layer 8</td>
<td id="T_20678_row2_col1" class="data row2 col1">0.4369</td>
<td id="T_20678_row2_col2" class="data row2 col2">0.1376</td>
<td id="T_20678_row2_col3" class="data row2 col3">0.8170</td>
</tr>
<tr class="even">
<td id="T_20678_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">Classification tree</td>
<td id="T_20678_row3_col0" class="data row3 col0">depth 8, leaf 100</td>
<td id="T_20678_row3_col1" class="data row3 col1">0.4473</td>
<td id="T_20678_row3_col2" class="data row3 col2">0.1407</td>
<td id="T_20678_row3_col3" class="data row3 col3">0.8145</td>
</tr>
<tr class="odd">
<td id="T_20678_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">Random forest</td>
<td id="T_20678_row4_col0" class="data row4 col0">300 trees, max features 0.5, leaf 20</td>
<td id="T_20678_row4_col1" class="data row4 col1">0.4324</td>
<td id="T_20678_row4_col2" class="data row4 col2">0.1356</td>
<td id="T_20678_row4_col3" class="data row4 col3">0.8180</td>
</tr>
<tr class="even">
<td id="T_20678_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">Gradient boosting</td>
<td id="T_20678_row5_col0" class="data row5 col0">rate 0.1, depth 4, 91 trees</td>
<td id="T_20678_row5_col1" class="data row5 col1">0.4311</td>
<td id="T_20678_row5_col2" class="data row5 col2">0.1354</td>
<td id="T_20678_row5_col3" class="data row5 col3">0.8178</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Gradient boosting attains the lowest test log loss, 0.4311, and Brier score, 0.1354, in this comparison, with the random forest close behind on both probability scores and the selected FNN third. The single tree improves substantially on the constant-probability benchmark but has the weakest probability scores among the fitted models. The margin between the two tree ensembles is numerically small; no paired uncertainty estimate is reported here. Accuracy gives a less informative and slightly different ranking: the forest attains 81.80%, boosting 81.78%, and the FNN and logistic regression both attain 81.70%.</p>
<p>These results support a deliberately local conclusion. On this split, both tree ensembles improve on a single tree and outperform the FNN on the probability scores, while the table alone does not establish which ensemble has lower expected loss. The table does not show that boosting universally dominates forests or networks. The score gaps are small, the test observations are shared across models, and the data cover only one borrower cohort. A serious performance claim would require paired uncertainty assessment across fresh test observations or repeated deployment-relevant samples; a later-period cohort would also be needed to assess stability across credit regimes.</p>
<p>One data caveat applies to every model in the table alike. The dataset documentation does not pin down precisely how the most recent repayment-status code is timed relative to the outcome month; if that code partly reflects payment behavior in the outcome month itself, every model receives an informative signal that a real-time scoring system would not yet have. Such leakage could make the reported scores optimistic and also alter the relative ranking, because the models can exploit the same unavailable signal to different degrees. The table therefore compares methods on a fixed information set; it does not establish deployable performance.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Question for Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question for Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why does the table justify saying that the boosted model has the best realized log loss on this test sample, but not that it has the lowest population risk?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggested Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first claim is a direct comparison of scores computed for the same 6,000 clients. The second concerns expected performance over new samples. One realized test set contains sampling variation, and the small score gaps could change for another cohort or credit regime.</p>
</div>
</div>
</div>
</section>
<section id="summary" class="level2" data-number="12.9">
<h2 data-number="12.9" class="anchored" data-anchor-id="summary"><span class="header-section-number">12.9</span> Summary</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Gradient boosting builds an additive ensemble by fitting successive trees to negative loss gradients.</li>
<li>The pseudo-residuals are ordinary residuals under squared loss and <span class="math inline">y-p</span> under Bernoulli log-loss.</li>
<li>Learning rate, tree count, depth, subsampling, and early stopping control the ensemble complexity.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Common Pitfalls
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Rapid improvement in training loss does not justify a large learning rate or additional boosting stages.</li>
<li>Bernoulli pseudo-residuals are <span class="math inline">y-p</span>, but leaf corrections are added to the log-odds <span class="math inline">F</span>, which the sigmoid then converts into a probability.</li>
<li>Adding more trees does not give the ensemble an ability to extrapolate smooth trends outside the training support.</li>
</ul>
</div>
</div>
</section>
<section id="exercises" class="level2" data-number="12.10">
<h2 data-number="12.10" class="anchored" data-anchor-id="exercises"><span class="header-section-number">12.10</span> Exercises</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 12.1: First Step of Gradient Boosting with Shrinkage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider four monthly forecast-origin/target pairs, indexed by the forecast origins <span class="math inline">t=1,\dots,4</span>. At forecast origin <span class="math inline">t</span>, the leading indicator <span class="math inline">x_t</span> is observed and is used to predict next-month output growth <span class="math inline">y_{t+1}</span>. You observe:</p>
<div class="display-math-block">
<p><span class="math display">
(x_t, y_{t+1}) = (1,2), (2,3), (3,2.5), (4,5).
</span></p>
</div>
<p>In this small sample the indicator values happen to coincide with the time index; the stump below splits on the indicator value <span class="math inline">x</span>, not on time. Consider squared-error boosting with decision stumps as weak learners. Let the learning rate be <span class="math inline">\nu = 0.4</span>.</p>
<ol type="1">
<li>Compute the initial model <span class="math inline">\hat F_0(x)</span> and the residuals <span class="math inline">r_{t+1} = y_{t+1} - \hat F_0(x_t)</span>, <span class="math inline">t=1,\dots,4</span>, and explain why these residuals are exactly the negative gradients of the squared-error training loss <span class="math inline">\frac{1}{2}\sum_{t=1}^{4} \bigl(y_{t+1} - F(x_t)\bigr)^2</span> with respect to the fitted values.</li>
<li>Fit the optimal first stump <span class="math inline">\hat h_1(x)</span> by checking the candidate split points <span class="math inline">1.5</span>, <span class="math inline">2.5</span>, and <span class="math inline">3.5</span>.</li>
<li>Write the updated model <span class="math display">
\hat F_1(x) = \hat F_0(x) + 0.4\, \hat h_1(x).
</span> Compute the fitted values at the four training points.</li>
<li>The stump from Part 2 is fitted by least squares, so its leaf values are the leaf means of the residuals. Show that the training sum of squared errors (SSE) after one shrunken update satisfies <span class="math display">
\mathrm{SSE}(\nu)
=
\sum_{t=1}^{4} r_{t+1}^2 \;-\; \nu(2-\nu)\sum_{t=1}^{4} \hat h_1(x_t)^2,
</span> and verify the formula at <span class="math inline">\nu=0.4</span> and <span class="math inline">\nu=1</span> by comparing with the directly computed SSE. Conclude that on the training sample, the full step <span class="math inline">\nu=1</span> always fits at least as well as any shrunken step—and explain why this does not make <span class="math inline">\nu=1</span> the right choice out of sample.</li>
<li><strong>A limit of stumps.</strong> For this part only, replace the scalar predictor by two binary economic indicators <span class="math inline">x_1,x_2\in\{0,1\}</span>, with all four combinations possible. Suppose the conditional mean of next-month output growth is <span class="math inline">f(x_1,x_2)=x_1x_2</span>. Consider a stump ensemble <span class="math inline">\hat F_M=\hat F_0+\nu\sum_{m=1}^{M}\hat h_m</span> with a constant initial model <span class="math inline">\hat F_0</span>, a learning rate <span class="math inline">\nu&gt;0</span>, and decision stumps <span class="math inline">\hat h_1,\dots,\hat h_M</span>. Show that it can be written as <span class="math display">
\hat F_M(x_1,x_2)=a+g_1(x_1)+g_2(x_2),
</span> where <span class="math inline">a</span> is a constant, <span class="math inline">g_1</span> is a function of <span class="math inline">x_1</span> alone, and <span class="math inline">g_2</span> is a function of <span class="math inline">x_2</span> alone. Compute the contrast <span class="math display">
F(1,1)-F(1,0)-F(0,1)+F(0,0)
</span> both for <span class="math inline">F=\hat F_M</span> and for <span class="math inline">F=f</span>. Can increasing <span class="math inline">M</span> or changing <span class="math inline">\nu</span> make a stump ensemble match all four conditional means? Construct a depth-2 tree that represents <span class="math inline">f</span> exactly.</li>
</ol>
<p><em>Exam level: suitable as-is. Parts 1–4 combine boosting mechanics with a projection argument for shrinkage, and Part 5 isolates an interaction restriction that additional stumps cannot remove.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint for Part 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For each candidate split, compute the mean residual in the left and right leaves and then the residual SSE.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint for Part 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Expand <span class="math inline">\sum_{t=1}^{4} \bigl(r_{t+1} - \nu \hat h_1(x_t)\bigr)^2</span>. For the cross term, use that within each leaf <span class="math inline">\hat h_1</span> is constant and equal to the mean of the residuals it fits, so <span class="math inline">\sum_{t=1}^{4} r_{t+1}\hat h_1(x_t) = \sum_{t=1}^{4} \hat h_1(x_t)^2</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint for Part 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Each stump splits on only one of the two indicators. Group the stumps by that indicator, then substitute the additive form into the contrast.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part 1: Initial model, residuals, and the gradient view</strong></p>
<p>The initial model is the sample mean:</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_0(x)=\bar y=\frac{2+3+2.5+5}{4}=3.125.
</span></p>
</div>
<p>Therefore the residuals are</p>
<div class="display-math-block">
<p><span class="math display">
(r_2,\,r_3,\,r_4,\,r_5) = (-1.125,\,-0.125,\,-0.625,\,1.875).
</span></p>
</div>
<p>These are negative gradients because differentiating the training loss <span class="math inline">\frac{1}{2}\sum_{t=1}^{4} (y_{t+1}-F(x_t))^2</span> with respect to the fitted value <span class="math inline">F(x_t)</span> gives <span class="math inline">-(y_{t+1}-F(x_t))</span>; evaluating at the current fit <span class="math inline">F=\hat F_0</span> and flipping the sign yields exactly the residual <span class="math inline">r_{t+1}</span>. Fitting the next stump to the residuals is therefore fitting it to the steepest-descent direction of the training loss.</p>
<p><strong>Part 2: Best first stump</strong></p>
<p>Check the three candidate cutoffs.</p>
<p>For split <span class="math inline">1.5</span>:</p>
<ul>
<li>left mean residual: <span class="math inline">-1.125</span></li>
<li>right mean residual: <span class="math inline">\frac{-0.125-0.625+1.875}{3}=0.375</span></li>
</ul>
<p>Residual SSE:</p>
<div class="display-math-block">
<p><span class="math display">
0 + (-0.125-0.375)^2 + (-0.625-0.375)^2 + (1.875-0.375)^2 = 3.5.
</span></p>
</div>
<p>For split <span class="math inline">2.5</span>:</p>
<ul>
<li>left mean residual: <span class="math inline">\frac{-1.125-0.125}{2}=-0.625</span></li>
<li>right mean residual: <span class="math inline">\frac{-0.625+1.875}{2}=0.625</span></li>
</ul>
<p>Residual SSE:</p>
<div class="display-math-block">
<p><span class="math display">
(-1.125+0.625)^2 + (-0.125+0.625)^2 + (-0.625-0.625)^2 + (1.875-0.625)^2 = 3.625.
</span></p>
</div>
<p>For split <span class="math inline">3.5</span>:</p>
<ul>
<li>left mean residual: <span class="math inline">\frac{-1.125-0.125-0.625}{3}=-0.625</span></li>
<li>right mean residual: <span class="math inline">1.875</span></li>
</ul>
<p>Residual SSE:</p>
<div class="display-math-block">
<p><span class="math display">
(-1.125+0.625)^2 + (-0.125+0.625)^2 + (-0.625+0.625)^2 + (1.875-1.875)^2 = 0.5.
</span></p>
</div>
<p>So the best first stump is</p>
<div class="display-math-block">
<p><span class="math display">
\hat h_1(x)=
\begin{cases}
-0.625, &amp; x \leq 3.5, \\
1.875, &amp; x &gt; 3.5.
\end{cases}
</span></p>
</div>
<p><strong>Part 3: Shrinkage update</strong></p>
<p>With <span class="math inline">\nu=0.4</span>,</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_1(x)=\hat F_0(x)+0.4\,\hat h_1(x).
</span></p>
</div>
<p>Therefore</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_1(x)=
\begin{cases}
3.125 + 0.4(-0.625)=2.875, &amp; x \leq 3.5, \\
3.125 + 0.4(1.875)=3.875, &amp; x &gt; 3.5.
\end{cases}
</span></p>
</div>
<p>So the fitted values at the four training points are</p>
<div class="display-math-block">
<p><span class="math display">
(2.875,\ 2.875,\ 2.875,\ 3.875).
</span></p>
</div>
<p><strong>Part 4: The effect of shrinkage on the training fit</strong></p>
<p>After the update, the new residuals are <span class="math inline">r_{t+1}-\nu\hat h_1(x_t)</span>, so</p>
<div class="display-math-block">
<p><span class="math display">
\mathrm{SSE}(\nu)
=\sum_{t=1}^{4}\bigl(r_{t+1}-\nu\hat h_1(x_t)\bigr)^2
=\sum_{t=1}^{4} r_{t+1}^2-2\nu\sum_{t=1}^{4} r_{t+1}\hat h_1(x_t)+\nu^2\sum_{t=1}^{4}\hat h_1(x_t)^2.
</span></p>
</div>
<p>Denote the two leaves of the stump by <span class="math inline">R_{11}</span> and <span class="math inline">R_{21}</span>. On leaf <span class="math inline">R_{j1}</span>, <span class="math inline">\hat h_1</span> is constant and equal to the mean residual <span class="math inline">\gamma_{j1}^{\star}</span> in that leaf, so <span class="math inline">\sum_{t:\,x_t\in R_{j1}} r_{t+1}=\sum_{t:\,x_t\in R_{j1}}\gamma_{j1}^{\star}</span>. Summing leaf by leaf therefore gives</p>
<div class="display-math-block">
<p><span class="math display">
\sum_{t=1}^{4} r_{t+1}\hat h_1(x_t)
=\sum_{j=1}^{2}\gamma_{j1}^{\star}\sum_{t:\,x_t\in R_{j1}}r_{t+1}
=\sum_{j=1}^{2}\sum_{t:\,x_t\in R_{j1}}\bigl(\gamma_{j1}^{\star}\bigr)^2
=\sum_{t=1}^{4}\hat h_1(x_t)^2,
</span></p>
</div>
<p>and substituting this identity into the expansion yields</p>
<div class="display-math-block">
<p><span class="math display">
\mathrm{SSE}(\nu)=\sum_{t=1}^{4} r_{t+1}^2-\nu(2-\nu)\sum_{t=1}^{4}\hat h_1(x_t)^2.
</span></p>
</div>
<p>Numerically, <span class="math inline">\sum_{t=1}^{4} r_{t+1}^2=1.125^2+0.125^2+0.625^2+1.875^2=5.1875</span> and <span class="math inline">\sum_{t=1}^{4}\hat h_1(x_t)^2=3\times 0.625^2+1.875^2=4.6875</span>. At <span class="math inline">\nu=0.4</span> the formula gives <span class="math inline">5.1875-0.4\times 1.6\times 4.6875=2.1875</span>, which matches the direct computation using the fitted values from Part 3:</p>
<div class="display-math-block">
<p><span class="math display">
(2-2.875)^2 + (3-2.875)^2 + (2.5-2.875)^2 + (5-3.875)^2
= 2.1875.
</span></p>
</div>
<p>At <span class="math inline">\nu=1</span> the formula gives <span class="math inline">5.1875-4.6875=0.5</span>, again matching the direct computation with fitted values <span class="math inline">(2.5,\,2.5,\,2.5,\,5)</span>:</p>
<div class="display-math-block">
<p><span class="math display">
(2-2.5)^2 + (3-2.5)^2 + (2.5-2.5)^2 + (5-5)^2 = 0.5.
</span></p>
</div>
<p>Because <span class="math inline">\nu(2-\nu)</span> is strictly increasing on <span class="math inline">(0,1]</span>, the training SSE after one update is strictly decreasing in <span class="math inline">\nu</span>: the full step always fits the training sample at least as well as any shrunken step. Out of sample this is beside the point. Boosting is a multi-step procedure, the learning rate regularizes the whole path of updates, and the combination of <span class="math inline">\nu</span> and the stopping iteration <span class="math inline">M</span> is chosen on validation data; cautious updates often generalize better than aggressive early corrections even though they lose the one-step training comparison by construction.</p>
<p><strong>Part 5: An interaction that stumps cannot represent</strong></p>
<p>Each stump has a single split, on either <span class="math inline">x_1</span> or <span class="math inline">x_2</span>, and is therefore a function of that indicator alone. Grouping the terms in <span class="math inline">\hat F_M=\hat F_0+\nu\sum_{m=1}^M\hat h_m</span> by their split variable gives</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_M(x_1,x_2)=a+g_1(x_1)+g_2(x_2),
</span></p>
</div>
<p>with <span class="math inline">a=\hat F_0</span>, <span class="math inline">g_1(x_1)</span> equal to <span class="math inline">\nu</span> times the sum of the stumps that split on <span class="math inline">x_1</span>, and <span class="math inline">g_2(x_2)</span> equal to <span class="math inline">\nu</span> times the sum of the stumps that split on <span class="math inline">x_2</span>; if no stump splits on an indicator, the corresponding function is zero. Therefore</p>
<div class="display-math-block">
<p><span class="math display">
\begin{aligned}
&amp;\hat F_M(1,1)-\hat F_M(1,0)-\hat F_M(0,1)+\hat F_M(0,0)\\
&amp;=[a+g_1(1)+g_2(1)]-[a+g_1(1)+g_2(0)]\\
&amp;\quad-[a+g_1(0)+g_2(1)]+[a+g_1(0)+g_2(0)]
=0.
\end{aligned}
</span></p>
</div>
<p>For <span class="math inline">f(x_1,x_2)=x_1x_2</span>, the same contrast is <span class="math inline">1-0-0+0=1</span>. Thus no stump ensemble can match all four conditional means, regardless of the number of iterations or the learning rate. More iterations cannot remove this restriction on interactions.</p>
<p>A depth-2 tree can represent <span class="math inline">f</span>: split first at <span class="math inline">x_1=0.5</span> and assign the left leaf the value <span class="math inline">0</span>. In the right branch, split at <span class="math inline">x_2=0.5</span>, assigning values <span class="math inline">0</span> and <span class="math inline">1</span> to its left and right leaves. The tree predicts <span class="math inline">1</span> exactly when both indicators equal one.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 12.2: Bernoulli Log-Loss and Initialization
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider binary outcomes <span class="math inline">y_i\in\{0,1\}</span> and a boosting model with finite log-odds <span class="math inline">F(x_i)</span> and probability</p>
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
p_i&amp;=\sigma(F(x_i))\\
&amp;=\frac{1}{1+e^{-F(x_i)}}.
\end{aligned}
</span></span></p>
</div>
<p>The per-observation Bernoulli log-loss is</p>
<div class="display-math-block">
<p><span class="math display">
\ell(y_i,z)=-y_i\log\sigma(z)-(1-y_i)\log(1-\sigma(z)).
</span></p>
</div>
<ol type="1">
<li><strong>Gradient and pseudo-residuals.</strong> Derive the derivative of <span class="math inline">\ell(y_i,z)</span> with respect to <span class="math inline">z</span> and evaluate it at <span class="math inline">z=F(x_i)</span>. Hence obtain the pseudo-residual <span class="math inline">r_i</span>. State whether the tree’s correction is added to the probability or to the log-odds.</li>
<li><strong>Initialization and numerical example.</strong> Suppose both classes occur in the training sample and the initial model is a constant, <span class="math inline">\hat F_0(x)\equiv c</span>. Derive the value of <span class="math inline">c</span> minimizing total log-loss and show that it is the unique minimizer. For the sample <span class="math inline">y=(1,1,0,1)</span>, compute <span class="math inline">\bar y</span>, the optimal <span class="math inline">\hat F_0</span>, the implied initial probability for each observation, and the pseudo-residuals. Exact logarithms are acceptable.</li>
</ol>
<p><em>Exam level: suitable as-is. The two parts derive and apply the classification gradient and initialization.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint for Part 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A first-order condition identifies a candidate constant. To establish uniqueness, examine the second derivative of the total loss with respect to <span class="math inline">c</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Part 1: Gradient and pseudo-residuals</strong></p>
<p>Hold <span class="math inline">y_i</span> fixed and write <span class="math inline">p=\sigma(z)</span>. Since <span class="math inline">dp/dz=p(1-p)</span>, the chain rule gives</p>
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
\frac{\partial\ell(y_i,z)}{\partial z}
&amp;=\left(-\frac{y_i}{p}+\frac{1-y_i}{1-p}\right)p(1-p)\\
&amp;=-y_i(1-p)+(1-y_i)p\\
&amp;=p-y_i.
\end{aligned}
</span></span></p>
</div>
<p>At the current log-odds <span class="math inline">z=F(x_i)</span>, the corresponding probability is <span class="math inline">p_i</span>. The pseudo-residual is the negative derivative,</p>
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
r_i
&amp;=-\left.\frac{\partial\ell(y_i,z)}{\partial z}\right|_{z=F(x_i)}\\
&amp;=y_i-p_i.
\end{aligned}
</span></span></p>
</div>
<p>The tree’s correction is added to the log-odds <span class="math inline">F(x_i)</span>. The sigmoid then converts the updated log-odds into a new probability.</p>
<p><strong>Part 2: Optimal constant and numerical example</strong></p>
<p>For a constant model, all observations have the same probability <span class="math inline">p=\sigma(c)</span>. Write <span class="math inline">L(c)=\sum_{i=1}^N\ell(y_i,c)</span> for its total loss. Using Part 1,</p>
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
L'(c)
&amp;=\sum_{i=1}^N(p-y_i)\\
&amp;=N(p-\bar y).
\end{aligned}
</span></span></p>
</div>
<p>The first-order condition therefore requires <span class="math inline">p=\bar y</span>. Because both classes occur, <span class="math inline">0&lt;\bar y&lt;1</span>, so the corresponding log-odds are finite:</p>
<div class="display-math-block">
<p><span class="math display">
\hat F_0(x)=\log\left(\frac{\bar y}{1-\bar y}\right).
</span></p>
</div>
<p>For every finite <span class="math inline">c</span>, the sigmoid probability lies in <span class="math inline">(0,1)</span>, and</p>
<div class="display-math-block">
<p><span class="math display">
L''(c)=Np(1-p)&gt;0.
</span></p>
</div>
<p>Thus <span class="math inline">L</span> is strictly convex, and the stationary point is its unique global minimizer.</p>
<p>For <span class="math inline">y=(1,1,0,1)</span>, the sample mean is <span class="math inline">\bar y=3/4</span>, so</p>
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
\hat F_0(x)
&amp;=\log\left(\frac{3/4}{1/4}\right)\\
&amp;=\log 3.
\end{aligned}
</span></span></p>
</div>
<p>Every initial probability is <span class="math inline">p_i=3/4</span>. The pseudo-residuals are</p>
<div class="display-math-block">
<p><span style="text-align-last: auto;"><span class="math display">
\begin{aligned}
(r_1,r_2,r_3,r_4)
&amp;=(1-3/4,\;1-3/4,\;0-3/4,\;1-3/4)\\
&amp;=(1/4,\;1/4,\;-3/4,\;1/4).
\end{aligned}
</span></span></p>
</div>
</div>
</div>
</div>
</section>
<section id="references" class="level2" data-number="12.11">
<h2 data-number="12.11" class="anchored" data-anchor-id="references"><span class="header-section-number">12.11</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ChenGuestrin2016" class="csl-entry" role="listitem">
Chen, Tianqi, and Carlos Guestrin. 2016. <span>“<span>XGBoost</span>: A Scalable Tree Boosting System.”</span> In <em>Proceedings of the 22nd <span>ACM SIGKDD</span> International Conference on Knowledge Discovery and Data Mining</em>, 785–94. <a href="https://doi.org/10.1145/2939672.2939785">https://doi.org/10.1145/2939672.2939785</a>.
</div>
<div id="ref-FreundSchapire1997" class="csl-entry" role="listitem">
Freund, Yoav, and Robert E. Schapire. 1997. <span>“<span class="nocase">A Decision-Theoretic Generalization of On-Line Learning and an Application to Boosting</span>.”</span> <em>Journal of Computer and System Sciences</em> 55 (1): 119–39. <a href="https://doi.org/10.1006/jcss.1997.1504">https://doi.org/10.1006/jcss.1997.1504</a>.
</div>
<div id="ref-Friedman2001Greedy" class="csl-entry" role="listitem">
Friedman, Jerome H. 2001. <span>“Greedy Function Approximation: A Gradient Boosting Machine.”</span> <em>Annals of Statistics</em> 29 (5): 1189–1232. <a href="https://doi.org/10.1214/aos/1013203451">https://doi.org/10.1214/aos/1013203451</a>.
</div>
<div id="ref-Friedman2002Stochastic" class="csl-entry" role="listitem">
———. 2002. <span>“Stochastic Gradient Boosting.”</span> <em>Computational Statistics &amp; Data Analysis</em> 38 (4): 367–78. <a href="https://doi.org/10.1016/S0167-9473(01)00065-2">https://doi.org/10.1016/S0167-9473(01)00065-2</a>.
</div>
<div id="ref-FriedmanHastieTibshirani2000" class="csl-entry" role="listitem">
Friedman, Jerome, Trevor Hastie, and Robert Tibshirani. 2000. <span>“Additive Logistic Regression: A Statistical View of Boosting.”</span> <em>Annals of Statistics</em> 28 (2): 337–407. <a href="https://doi.org/10.1214/aos/1016218223">https://doi.org/10.1214/aos/1016218223</a>.
</div>
<div id="ref-McCrackenNg2020FREDQD" class="csl-entry" role="listitem">
McCracken, Michael W., and Serena Ng. 2020. <span>“FRED-QD: A Quarterly Database for Macroeconomic Research.”</span> Working Paper 26872. National Bureau of Economic Research. <a href="https://doi.org/10.3386/w26872">https://doi.org/10.3386/w26872</a>.
</div>
<div id="ref-Yeh2009CreditDefaultData" class="csl-entry" role="listitem">
Yeh, I-Cheng. 2009. <span>“Default of Credit Card Clients.”</span> UCI Machine Learning Repository. <a href="https://doi.org/10.24432/C55S3H">https://doi.org/10.24432/C55S3H</a>.
</div>
<div id="ref-YehLien2009" class="csl-entry" role="listitem">
Yeh, I-Cheng, and Che-hui Lien. 2009. <span>“The Comparisons of Data Mining Techniques for the Predictive Accuracy of Probability of Default of Credit Card Clients.”</span> <em>Expert Systems with Applications</em> 36 (2): 2473–80. <a href="https://doi.org/10.1016/j.eswa.2007.12.020">https://doi.org/10.1016/j.eswa.2007.12.020</a>.
</div>
<div id="ref-ZhangYu2005" class="csl-entry" role="listitem">
Zhang, Tong, and Bin Yu. 2005. <span>“Boosting with Early Stopping: Convergence and Consistency.”</span> <em>Annals of Statistics</em> 33 (4): 1538–79. <a href="https://doi.org/10.1214/009053605000000255">https://doi.org/10.1214/009053605000000255</a>.
</div>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>This is a pedagogical final-vintage FRED-QD example. A full real-time GDP forecasting evaluation would also need to account for release calendars and data revisions.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mlmetrics\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./random_forests.html" class="pagination-link" aria-label="11. Random Forests">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">11. Random Forests</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./adv_tree_based_methods.html" class="pagination-link" aria-label="13. Advanced Tree-Based Methods">
        <span class="nav-page-text">13. Advanced Tree-Based Methods</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2026, Onno Kleen</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>