<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>nn_example – MLmetrics: Machine Learning for Econometricians</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./distributions_via_nns.html" rel="next">
<link href="./lstm_neural_networks.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
(function () {
  function markInternalLinks() {
    const links = window.document.querySelectorAll("a[href]");

    for (const link of links) {
      if (link.origin !== window.location.origin) {
        continue;
      }

      link.classList.add("no-external");

      if (link.getAttribute("target") === "_blank") {
        link.removeAttribute("target");
      }

      const rel = link.getAttribute("rel");
      if (rel === "noopener") {
        link.removeAttribute("rel");
      }
    }
  }

  if (window.document.readyState === "loading") {
    window.document.addEventListener("DOMContentLoaded", markInternalLinks, {
      once: true,
    });
  } else {
    markInternalLinks();
  }
})();
</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./feed_forward_nns.html">Neural Networks</a></li><li class="breadcrumb-item"><a href="./nn_example.html">8. Empirical Exercise: Networks for Time Series</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About This Book</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./information_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Information Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cross_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Cross-Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Optimization for Machine Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluating_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Evaluating Predictive Distributions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Neural Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./feed_forward_nns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Feed-Forward Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recurrent_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Recurrent Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lstm_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. LSTM Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nn_example.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">8. Empirical Exercise: Networks for Time Series</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions_via_nns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Distribution Modeling with Neural Networks</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Tree-Based Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Decision Trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random_forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11. Random Forests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gradient_boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12. Gradient Boosting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./adv_tree_based_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13. Advanced Tree-Based Methods</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Further Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hpo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14. Advanced Hyperparameter Optimization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conformal_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">15. Conformal Prediction</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Appendix</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#empirical-illustration-neural-networks-for-realized-volatility" id="toc-empirical-illustration-neural-networks-for-realized-volatility" class="nav-link active" data-scroll-target="#empirical-illustration-neural-networks-for-realized-volatility"><span class="header-section-number">8</span> Empirical Illustration: Neural Networks for Realized Volatility</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">8.1</span> Overview</a></li>
  <li><a href="#roadmap" id="toc-roadmap" class="nav-link" data-scroll-target="#roadmap"><span class="header-section-number">8.2</span> Roadmap</a></li>
  <li><a href="#data-and-forecast-target" id="toc-data-and-forecast-target" class="nav-link" data-scroll-target="#data-and-forecast-target"><span class="header-section-number">8.3</span> Data and Forecast Target</a></li>
  <li><a href="#comparable-specifications" id="toc-comparable-specifications" class="nav-link" data-scroll-target="#comparable-specifications"><span class="header-section-number">8.4</span> Comparable Specifications</a></li>
  <li><a href="#validation-and-tuning" id="toc-validation-and-tuning" class="nav-link" data-scroll-target="#validation-and-tuning"><span class="header-section-number">8.5</span> Validation and Tuning</a></li>
  <li><a href="#annual-forecasting-and-replication" id="toc-annual-forecasting-and-replication" class="nav-link" data-scroll-target="#annual-forecasting-and-replication"><span class="header-section-number">8.6</span> Annual Forecasting and Replication</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">8.7</span> Results</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8.8</span> Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8.9</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./feed_forward_nns.html">Neural Networks</a></li><li class="breadcrumb-item"><a href="./nn_example.html">8. Empirical Exercise: Networks for Time Series</a></li></ol></nav></header>
<div class="alert alert-warning" role="alert" style="margin: 0; border-radius: 0; border: none; border-bottom: 1px solid #f0c842; text-align: center; font-size: 0.9em; padding: 0.5rem 1rem;">
  <strong>Under active development.</strong> A stable version is expected in November 2026. Feedback is welcome by <a href="mailto:kleen@ese.eur.nl">email</a> or via <a href="https://github.com/onnokleen/mlmetrics/issues">GitHub issues</a>.
</div>




<section id="empirical-illustration-neural-networks-for-realized-volatility" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Empirical Illustration: Neural Networks for Realized Volatility</h1>
<section id="overview" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">8.1</span> Overview</h2>
<p>Neural-network architectures are often introduced as if the main empirical question were which architecture is most powerful. In time-series econometrics, that is usually the wrong starting point. Before comparing a feed-forward network, a recurrent network, or a Long Short-Term Memory (LSTM) network, we must define the forecast target, the information set at each forecast origin, the validation scheme, and the loss function used for evaluation. Throughout this chapter, <em>volatility</em> names the broad forecasting application; the measured target is realized <strong>variance</strong>, not its square root.</p>
<p>This chapter makes those choices explicit in a single empirical illustration. The object is one-step-ahead forecasting of the realized variance of the S&amp;P 500 exchange-traded fund (ETF; ticker <code>SPY</code>), using the daily measures described in <a href="./datasets.html#sec-spy-taq-realized">the dataset appendix</a>.</p>
<p>The empirical comparison has two purposes. First, it compares a log-target pipeline with a level-target pipeline. The comparison changes both the target transformation and the normalization of the lag inputs, so it does not isolate the effect of the target transformation alone. Second, it compares a linear benchmark, the heterogeneous autoregressive (HAR) model estimated by ordinary least squares (OLS), with four neural specifications: a HAR feed-forward neural network (HAR-FNN) on the same three volatility summaries, a direct FNN on 22 individual daily observations, a Simple RNN (recurrent neural network), and an LSTM, with both recurrent models using 756 daily observations. The long input history lets us ask whether learning from roughly three years of daily observations improves on a parsimonious volatility summary. In this illustration, HAR remains competitive with the neural models, and the ranking depends on the evaluation criterion.</p>
</section>
<section id="roadmap" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="roadmap"><span class="header-section-number">8.2</span> Roadmap</h2>
<ol type="1">
<li>We define the realized-variance target and the information available at each forecast origin.</li>
<li>We separate the 756-day input history from the sliding estimation sample and specify annual refitting.</li>
<li>We compare HAR summaries, a dense lag vector, and recurrent sequence representations.</li>
<li>We select neural hyperparameters before the test period and apply the fixed refitting rule.</li>
<li>We compare forecast errors across models and loss functions and assess what the rankings can establish.</li>
</ol>
</section>
<section id="data-and-forecast-target" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="data-and-forecast-target"><span class="header-section-number">8.3</span> Data and Forecast Target</h2>
<p>Let <span class="math inline">r_{t,j}</span> denote the <span class="math inline">j</span>th intraday return on trading day <span class="math inline">t</span>. A standard realized-variance measure is </p>
<div class="display-math-block">
<p><span class="math display">
RV_t=\sum_{j=1}^{M} r_{t,j}^2,
</span></p>
</div>
<p> where <span class="math inline">M</span> is the number of intraday return intervals. The empirical series uses 5-minute log returns multiplied by 100, so <span class="math inline">RV</span> and its root mean squared error (RMSE) on the level scale are measured in squared percentage points. Realized variance <span class="math inline">RV_t</span> is a canonical high-frequency volatility measure; <span class="citation" data-cites="AndersenBollerslevDieboldLabys2003">Andersen et al. (<a href="#ref-AndersenBollerslevDieboldLabys2003" role="doc-biblioref">2003</a>)</span> is a standard reference for modeling and forecasting it.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> It is positive, highly right-skewed, and persistent. For that reason, a common forecasting target is </p>
<div class="display-math-block">
<p><span class="math display">
z_t = \log(RV_t),
</span></p>
</div>
<p> although the empirical comparison below also reports what happens when the networks are fit directly to <span class="math inline">RV_t</span> in levels.</p>
<p>A note on case: this chapter is a worked empirical illustration, so its formulas operate on the observed series: lowercase <span class="math inline">z_t</span> and <span class="math inline">r_{t,j}</span> denote realized values, in line with the book’s convention. In the few analytic statements that treat the target as random, we write <span class="math inline">Z_t = \log RV_t</span> for the random variable whose realization is <span class="math inline">z_t</span>; the capitalization of the acronym <span class="math inline">RV_t</span> does not itself mark randomness, and where <span class="math inline">RV_t</span> appears inside a conditional expectation it denotes the random realized variance.</p>
<p>For the recurrent models with a log target, the one-step-ahead forecasting problem is </p>
<div class="display-math-block">
<p><span class="math display">
\widehat z_{t+1\mid t}
=
f_\theta(z_{t-755},\ldots,z_t),
</span></p>
</div>
<p> where the input contains <strong>756 daily observations</strong>, approximately three trading years at 252 observations per year. The sequence is ordered from oldest to newest. We forecast after observing day <span class="math inline">t</span>; the target <span class="math inline">z_{t+1}</span> is excluded from the input. The Simple RNN and LSTM process these observations sequentially. The direct FNN instead receives only the most recent 22 daily observations, <span class="math inline">(z_{t-21},\ldots,z_t)</span>, as a fixed-position vector. For the level-target versions, replace the log observations by the corresponding <span class="math inline">RV</span> observations.</p>
<p>The HAR specifications instead receive three summaries known at origin <span class="math inline">t</span>: </p>
<div class="display-math-block">
<p><span class="math display">
\left(
RV_t,\quad
\frac{1}{5}\sum_{j=0}^{4}RV_{t-j},\quad
\frac{1}{21}\sum_{j=0}^{20}RV_{t-j}
\right).
</span></p>
</div>
<p> The daily, weekly, and monthly components are the parsimonious volatility representation of <span class="citation" data-cites="CorsiHAR2009">Corsi (<a href="#ref-CorsiHAR2009" role="doc-biblioref">2009</a>)</span>. For the log target, we take the logarithm of each component; for the level target, we use each component in levels. In particular, the weekly and monthly log inputs are <em>logs of average RV</em>, not averages of log RV.</p>
<p><strong>Input history and estimation sample.</strong> The input history describes one forecast example: 22 daily values for the direct FNN and 756 for the recurrent models. Separately, we fit each model on the most recent <strong>756 training examples</strong>, each pairing a past input with its subsequently observed target. At an annual refit, older examples leave this sliding estimation sample as newer examples enter. The sample never expands. Each training example still needs its own lag history, so preparing 756 recurrent-model examples with 756 daily inputs requires 1,512 consecutive daily observations, roughly six trading years. The earlier observations supply predictors; they do not add training targets.</p>
<p>The data contain 2,516 trading-day observations from 2015-01-02 to 2024-12-31. After constructing the long recurrent input windows, 1,760 forecast examples remain; the other models use the same target dates for comparability. We use complete calendar years: <strong>2022 for validation</strong> (251 trading-day predictions) and <strong>2023–2024 for testing</strong> (502 predictions). Each annual fit uses the most recent 756 observed training outcomes available before that year starts. The validation year therefore follows the same fit-once, forecast-for-one-year rule as each test year.</p>
<p><a href="#fig-nn-forecast-window" class="quarto-xref">Figure&nbsp;8.1</a> distinguishes the information used for one forecast from the examples used to estimate its model. Within each validation or test year, the weights and scaling constants stay fixed, while the daily input window advances after every observed outcome.</p>
<div id="cell-fig-nn-forecast-window" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Rectangle</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">6.2</span>), height_ratios<span class="op">=</span>[<span class="dv">1</span>, <span class="fl">1.7</span>], layout<span class="op">=</span><span class="st">"constrained"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">12</span>), ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="fl">3.5</span>))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x, label <span class="kw">in</span> [(<span class="fl">0.5</span>, <span class="st">"$z_{t-755}$"</span>), (<span class="fl">2.3</span>, <span class="st">"$z_{t-754}$"</span>), (<span class="dv">6</span>, <span class="st">"$z_{t-1}$"</span>), (<span class="fl">7.8</span>, <span class="st">"$z_t$"</span>)]:</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(Rectangle((x, <span class="fl">1.2</span>), <span class="fl">1.35</span>, <span class="fl">.8</span>, facecolor<span class="op">=</span><span class="st">"#d7e5f5"</span>, edgecolor<span class="op">=</span><span class="st">"#4c78a8"</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    ax.text(x<span class="op">+</span><span class="fl">.675</span>, <span class="fl">1.6</span>, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">4.8</span>, <span class="fl">1.6</span>, <span class="st">"..."</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>ax.add_patch(Rectangle((<span class="fl">10.2</span>, <span class="fl">1.2</span>), <span class="fl">1.35</span>, <span class="fl">.8</span>, facecolor<span class="op">=</span><span class="st">"#f7d7c4"</span>, edgecolor<span class="op">=</span><span class="st">"#d65f00"</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">10.875</span>, <span class="fl">1.6</span>, <span class="st">"$z_{t+1}$"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, xy<span class="op">=</span>(<span class="fl">10.1</span>, <span class="fl">1.6</span>), xytext<span class="op">=</span>(<span class="fl">9.3</span>, <span class="fl">1.6</span>), arrowprops<span class="op">=</span>{<span class="st">"arrowstyle"</span>:<span class="st">"-&gt;"</span>})</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">4.8</span>, <span class="fl">2.55</span>, <span class="st">"RNN / LSTM: 756 inputs known at origin t"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">10.875</span>, <span class="fl">2.55</span>, <span class="st">"Target"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> day(s):</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> mdates.date2num(datetime.fromisoformat(s))</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">2</span>, <span class="st">"Validation"</span>, <span class="st">"2019-01-03"</span>, <span class="st">"2021-12-31"</span>, <span class="dv">2022</span>, <span class="st">"#fff0bf"</span>),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span>, <span class="st">"Test"</span>, <span class="st">"2020-01-02"</span>, <span class="st">"2022-12-30"</span>, <span class="dv">2023</span>, <span class="st">"#f7d7c4"</span>),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">0</span>, <span class="st">"Test refit"</span>, <span class="st">"2020-12-29"</span>, <span class="st">"2023-12-29"</span>, <span class="dv">2024</span>, <span class="st">"#f7d7c4"</span>),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> y, label, start, end, year, color <span class="kw">in</span> rows:</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    ax.barh(y, day(end)<span class="op">-</span>day(start), left<span class="op">=</span>day(start), height<span class="op">=</span><span class="fl">.56</span>, color<span class="op">=</span><span class="st">"#cfe8cf"</span>, edgecolor<span class="op">=</span><span class="st">"0.45"</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    ax.text((day(start)<span class="op">+</span>day(end))<span class="op">/</span><span class="dv">2</span>, y, <span class="st">"756 training outcomes"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    prediction_start, prediction_end <span class="op">=</span> day(<span class="ss">f"</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">-01-01"</span>), day(<span class="ss">f"</span><span class="sc">{</span>year<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">-01-01"</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    ax.barh(y, prediction_end<span class="op">-</span>prediction_start, left<span class="op">=</span>prediction_start, height<span class="op">=</span><span class="fl">.56</span>, color<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">"0.45"</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    ax.text((prediction_start<span class="op">+</span>prediction_end)<span class="op">/</span><span class="dv">2</span>, y, <span class="bu">str</span>(year), ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>ax.set_yticks([r[<span class="dv">0</span>] <span class="cf">for</span> r <span class="kw">in</span> rows], [r[<span class="dv">1</span>] <span class="cf">for</span> r <span class="kw">in</span> rows])</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_locator(mdates.YearLocator())</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">"%Y"</span>))</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(day(<span class="st">"2018-10-01"</span>), day(<span class="st">"2025-03-01"</span>))</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Green: training outcomes; yellow/orange: prediction year. Lag inputs start earlier."</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> spine <span class="kw">in</span> [<span class="st">"top"</span>, <span class="st">"right"</span>, <span class="st">"left"</span>]:</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    ax.spines[spine].set_visible(<span class="va">False</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-nn-forecast-window" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-forecast-window-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="nn_example_files/figure-html/fig-nn-forecast-window-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-forecast-window-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Two different windows in the forecasting design. Top: a recurrent-model forecast uses the preceding 756 daily observations, ordered from oldest to newest. Bottom: each row is one annual fit, with its 756 training outcomes in green and its prediction year in yellow (validation) or orange (test). The training window slides forward each year. Validation predictions cover 2022; only predictions for 2023 and 2024 enter the reported test scores.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The table separates <strong>validation</strong>, whose prediction errors select the neural configuration, from <strong>testing</strong>, whose prediction errors assess the selected procedure. Every row uses a sliding estimation sample of 756 training outcomes. The middle column is the information cutoff for fitting; the final column is the calendar year being predicted, one trading day at a time.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Phase</th>
<th>Fit using outcomes observed through</th>
<th>Predict each trading day in</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Validation:</strong> choose the configuration</td>
<td>December 2021</td>
<td><strong>2022</strong></td>
</tr>
<tr class="even">
<td><strong>Test:</strong> first evaluation year</td>
<td>December 2022</td>
<td><strong>2023</strong></td>
</tr>
<tr class="odd">
<td><strong>Test:</strong> annual refit</td>
<td>December 2023</td>
<td><strong>2024</strong></td>
</tr>
</tbody>
</table>
<p>The validation predictions run from 3 January through 30 December 2022. Hyperparameters are then fixed before the first test prediction on 3 January 2023. At the beginning of 2024, we refit the weights and scalers using the same chosen configuration. Only the 2023 and 2024 prediction errors enter the reported test scores.</p>
<p>A 756-example training sample is approximately three trading years; its start need not coincide with 1 January. The exact training ranges are 2019-01-03–2021-12-31 for validation, 2020-01-02–2022-12-30 for the first test year, and 2020-12-29–2023-12-29 for the second test year. The 2022 validation outcomes can enter the 2023 fit once observed, and the 2023 test outcomes can enter the 2024 fit. Neither update changes an earlier forecast or uses the test errors to choose hyperparameters.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Question for Reflection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question for Reflection
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 2024 model is estimated using realized variances observed during 2023, even though 2023 belongs to the test period. Why does this not leak future information into the reported forecasts?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggested Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The annual refitting rule is fixed before testing begins. Each 2023 forecast uses only information available at its forecast origin, and the 2024 fit uses only outcomes already known at its forecast origin. Reusing an observed outcome for a later fit is compatible with sequential evaluation; using it to revise an earlier forecast or choose hyperparameters after inspecting test performance would change the protocol.</p>
</div>
</div>
</div>
<p>The following code constructs the examples and selects the sliding estimation sample. The code indexes rows by the <em>target date</em>, so a row with target at array position <code>t</code> uses positions <code>t-756</code> through <code>t-1</code> for the recurrent models and the last 22 of those positions for the direct FNN. This is the same timing as the formula above, with the target index shifted by one. The complete implementation is available in <a href="nn_example_pipeline.py">the replication module</a>.</p>
<div id="6600d72c" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nn_example_pipeline <span class="im">import</span> (</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    INPUT_DAYS, FNN_INPUT_DAYS, ESTIMATION_EXAMPLES, VALIDATION_START, TEST_START,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    TEST_END, N_TRIALS, MAX_EPOCHS, SEED,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="9e5b9d4e" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> load_data(path):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> pd.read_csv(path, parse_dates<span class="op">=</span>[<span class="st">"date"</span>]).sort_values(<span class="st">"date"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> data.loc[data.date <span class="op">&lt;=</span> TEST_END, [<span class="st">"date"</span>, <span class="st">"rv"</span>]].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> data.date.duplicated().<span class="bu">any</span>() <span class="kw">or</span> <span class="kw">not</span> data.date.is_monotonic_increasing:</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Dates must be distinct and increasing."</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> np.isfinite(data.rv).<span class="bu">all</span>() <span class="kw">or</span> <span class="kw">not</span> (data.rv <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">all</span>():</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Every observed trading-day RV must be finite and positive."</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> data</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_inputs(data, input_days<span class="op">=</span>INPUT_DAYS):</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""One row per target date; all inputs end on its preceding trading day."""</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    rv <span class="op">=</span> data.rv.to_numpy(dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> np.log(rv)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    targets <span class="op">=</span> np.arange(input_days, <span class="bu">len</span>(data))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    lag_rv <span class="op">=</span> np.stack([rv[t<span class="op">-</span>input_days:t] <span class="cf">for</span> t <span class="kw">in</span> targets])</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    har_rv <span class="op">=</span> np.array([[rv[t<span class="op">-</span><span class="dv">1</span>], rv[t<span class="op">-</span><span class="dv">5</span>:t].mean(), rv[t<span class="op">-</span><span class="dv">21</span>:t].mean()]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">for</span> t <span class="kw">in</span> targets])</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"dates"</span>: data.date.iloc[targets].reset_index(drop<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"target_positions"</span>: targets,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">"lag_log"</span>: np.log(lag_rv), <span class="st">"lag_rv"</span>: lag_rv,</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>        <span class="st">"har_log"</span>: np.log(har_rv), <span class="st">"har_rv"</span>: har_rv,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        <span class="st">"y_log"</span>: z[targets], <span class="st">"y_rv"</span>: rv[targets],</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimation_indices(dates, first_forecast_date, n_examples<span class="op">=</span>ESTIMATION_EXAMPLES):</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""The last n_examples outcomes observed before this forecast target."""</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> np.flatnonzero(np.asarray(dates <span class="op">&lt;</span> first_forecast_date))</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(idx) <span class="op">&lt;</span> n_examples:</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Not enough forecast-origin examples for the estimation window."</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> idx[<span class="op">-</span>n_examples:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="a1ec2fb0" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> load_data(Path(<span class="st">"data/taq_spy/SPY_daily_measures.csv"</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>panel <span class="op">=</span> make_inputs(data)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>train_idx <span class="op">=</span> estimation_indices(panel[<span class="st">"dates"</span>], VALIDATION_START)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="comparable-specifications" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="comparable-specifications"><span class="header-section-number">8.4</span> Comparable Specifications</h2>
<p>With the forecast dates fixed, the specifications differ in how they represent the past.</p>
<ul>
<li>HAR-OLS regresses the target on the three HAR components, in logs or levels according to the target.</li>
<li>HAR-FNN uses exactly the same three components through one hidden dense layer and a linear output.</li>
<li>The direct FNN jointly processes the most recent 22 individual daily inputs through one hidden dense layer and a linear output; each lag position receives its own weights.</li>
<li>The Simple RNN processes the 756 inputs from oldest to newest through one recurrent layer and a linear output.</li>
<li>The LSTM processes the same sequence through one recurrent layer with gated memory and a linear output.</li>
</ul>
<p>The HAR-OLS and HAR-FNN comparison holds the target and predictor information fixed. It asks whether a tuned nonlinear procedure improves on linear OLS with the same summaries. The direct FNN receives 22 individual observations instead of the HAR summaries, while the recurrent models receive 756. Their comparison with HAR therefore changes both the representation and the available information. Comparing the direct FNN with the recurrent models also changes the history length, so the results do not isolate the effect of recurrence. The direct FNN is a neural network on individual lags, not a HAR model without averaging.</p>
<p><a href="#fig-nn-architectures" class="quarto-xref">Figure&nbsp;8.2</a> shows where aggregation and parameter sharing enter. Increasing the input history raises the dense FNN’s parameter count but does not raise the recurrent layers’ parameter counts at a fixed width. It does increase the number of recurrent updates and the length of the gradient path.</p>
<div id="cell-fig-nn-architectures" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Rectangle, FancyArrowPatch</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">11.5</span>, <span class="fl">6.4</span>))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.ravel()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>titles <span class="op">=</span> [<span class="st">"HAR-FNN"</span>, <span class="st">"FNN"</span>, <span class="st">"Simple RNN"</span>, <span class="st">"LSTM"</span>]</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, title <span class="kw">in</span> <span class="bu">zip</span>(axes, titles):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="dv">0</span>, <span class="dv">6</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    ax.axis(<span class="st">"off"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, label <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">"$RV_t$"</span>, <span class="st">"avg 5"</span>, <span class="st">"avg 21"</span>]):</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].add_patch(Rectangle((<span class="fl">0.7</span>, <span class="fl">4.0</span> <span class="op">-</span> i <span class="op">*</span> <span class="fl">1.0</span>), <span class="fl">1.3</span>, <span class="fl">0.55</span>, facecolor<span class="op">=</span><span class="st">"#d7e5f5"</span>, edgecolor<span class="op">=</span><span class="st">"#4c78a8"</span>))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].text(<span class="fl">1.35</span>, <span class="fl">4.27</span> <span class="op">-</span> i <span class="op">*</span> <span class="fl">1.0</span>, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].text(<span class="fl">1.35</span>, <span class="fl">4.85</span>, <span class="st">"HAR inputs"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].add_patch(Rectangle((<span class="fl">4.2</span>, <span class="fl">2.35</span>), <span class="fl">1.5</span>, <span class="fl">1.3</span>, facecolor<span class="op">=</span><span class="st">"#e6d8f2"</span>, edgecolor<span class="op">=</span><span class="st">"#7b4fa3"</span>))</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].text(<span class="fl">4.95</span>, <span class="fl">3.0</span>, <span class="st">"1 hidden</span><span class="ch">\n</span><span class="st">layer"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].add_patch(Rectangle((<span class="fl">7.6</span>, <span class="fl">2.65</span>), <span class="fl">1.25</span>, <span class="fl">0.7</span>, facecolor<span class="op">=</span><span class="st">"#f7d7c4"</span>, edgecolor<span class="op">=</span><span class="st">"#c44e52"</span>))</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].text(<span class="fl">8.22</span>, <span class="fl">3.0</span>, <span class="st">"forecast"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].add_patch(FancyArrowPatch((<span class="fl">2.2</span>, <span class="fl">3.0</span>), (<span class="fl">4.2</span>, <span class="fl">3.0</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">13</span>))</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].add_patch(FancyArrowPatch((<span class="fl">5.7</span>, <span class="fl">3.0</span>), (<span class="fl">7.6</span>, <span class="fl">3.0</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">13</span>))</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>):</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].add_patch(Rectangle((<span class="fl">0.8</span> <span class="op">+</span> i <span class="op">*</span> <span class="fl">0.5</span>, <span class="fl">2.55</span>), <span class="fl">0.32</span>, <span class="fl">0.9</span>, facecolor<span class="op">=</span><span class="st">"#d7e5f5"</span>, edgecolor<span class="op">=</span><span class="st">"#4c78a8"</span>))</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].text(<span class="fl">1.8</span>, <span class="fl">3.8</span>, <span class="st">"22 lags flattened"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].add_patch(Rectangle((<span class="fl">4.2</span>, <span class="fl">2.35</span>), <span class="fl">1.5</span>, <span class="fl">1.3</span>, facecolor<span class="op">=</span><span class="st">"#e6d8f2"</span>, edgecolor<span class="op">=</span><span class="st">"#7b4fa3"</span>))</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].text(<span class="fl">4.95</span>, <span class="fl">3.0</span>, <span class="st">"1 hidden</span><span class="ch">\n</span><span class="st">layer"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].add_patch(Rectangle((<span class="fl">7.6</span>, <span class="fl">2.65</span>), <span class="fl">1.25</span>, <span class="fl">0.7</span>, facecolor<span class="op">=</span><span class="st">"#f7d7c4"</span>, edgecolor<span class="op">=</span><span class="st">"#c44e52"</span>))</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].text(<span class="fl">8.22</span>, <span class="fl">3.0</span>, <span class="st">"forecast"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].add_patch(FancyArrowPatch((<span class="fl">3.6</span>, <span class="fl">3.0</span>), (<span class="fl">4.2</span>, <span class="fl">3.0</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">13</span>))</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].add_patch(FancyArrowPatch((<span class="fl">5.7</span>, <span class="fl">3.0</span>), (<span class="fl">7.6</span>, <span class="fl">3.0</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">13</span>))</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, kind <span class="kw">in</span> [(axes[<span class="dv">2</span>], <span class="st">"rnn"</span>), (axes[<span class="dv">3</span>], <span class="st">"lstm"</span>)]:</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    ax.text(<span class="dv">5</span>, <span class="fl">5.15</span>, <span class="st">"756 steps; final four shown"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    ax.text(<span class="fl">0.35</span>, <span class="fl">2.02</span>, <span class="st">"..."</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> [<span class="fl">0.8</span>, <span class="fl">2.7</span>, <span class="fl">4.6</span>, <span class="fl">6.5</span>]</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j, x <span class="kw">in</span> <span class="bu">enumerate</span>(xs):</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>        lag <span class="op">=</span> <span class="bu">len</span>(xs) <span class="op">-</span> <span class="dv">1</span> <span class="op">-</span> j</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>        suffix <span class="op">=</span> <span class="st">"t"</span> <span class="cf">if</span> lag <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="ss">f"t-</span><span class="sc">{</span>lag<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>        lag_label <span class="op">=</span> <span class="ss">f"$z_</span><span class="ch">{{</span><span class="sc">{</span>suffix<span class="sc">}</span><span class="ch">}}</span><span class="ss">$"</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>        cell_label <span class="op">=</span> <span class="ss">f"$h_</span><span class="ch">{{</span><span class="sc">{</span>suffix<span class="sc">}</span><span class="ch">}}</span><span class="ss">$"</span> <span class="cf">if</span> kind <span class="op">==</span> <span class="st">"rnn"</span> <span class="cf">else</span> <span class="ss">f"$h_</span><span class="ch">{{</span><span class="sc">{</span>suffix<span class="sc">}</span><span class="ch">}}</span><span class="ss">$</span><span class="ch">\n</span><span class="ss">$C_</span><span class="ch">{{</span><span class="sc">{</span>suffix<span class="sc">}</span><span class="ch">}}</span><span class="ss">$"</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>        ax.add_patch(Rectangle((x, <span class="fl">3.35</span>), <span class="fl">0.9</span>, <span class="fl">0.75</span>, facecolor<span class="op">=</span><span class="st">"#d7e5f5"</span>, edgecolor<span class="op">=</span><span class="st">"#4c78a8"</span>))</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>        ax.text(x <span class="op">+</span> <span class="fl">0.45</span>, <span class="fl">3.73</span>, lag_label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>        ax.add_patch(Rectangle((x, <span class="fl">1.65</span>), <span class="fl">0.9</span>, <span class="fl">0.75</span>, facecolor<span class="op">=</span><span class="st">"#e6d8f2"</span>, edgecolor<span class="op">=</span><span class="st">"#7b4fa3"</span>))</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>        ax.text(x <span class="op">+</span> <span class="fl">0.45</span>, <span class="fl">2.02</span>, cell_label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>        ax.add_patch(FancyArrowPatch((x <span class="op">+</span> <span class="fl">0.45</span>, <span class="fl">3.35</span>), (x <span class="op">+</span> <span class="fl">0.45</span>, <span class="fl">2.4</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">11</span>))</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> j <span class="op">&lt;</span> <span class="bu">len</span>(xs) <span class="op">-</span> <span class="dv">1</span>:</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>            ax.add_patch(FancyArrowPatch((x <span class="op">+</span> <span class="fl">0.9</span>, <span class="fl">2.02</span>), (xs[j<span class="op">+</span><span class="dv">1</span>], <span class="fl">2.02</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">11</span>))</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(Rectangle((<span class="fl">8.35</span>, <span class="fl">1.72</span>), <span class="fl">1.1</span>, <span class="fl">0.6</span>, facecolor<span class="op">=</span><span class="st">"#f7d7c4"</span>, edgecolor<span class="op">=</span><span class="st">"#c44e52"</span>))</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>    ax.text(<span class="fl">8.9</span>, <span class="fl">2.02</span>, <span class="st">"forecast"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(FancyArrowPatch((<span class="fl">7.4</span>, <span class="fl">2.02</span>), (<span class="fl">8.35</span>, <span class="fl">2.02</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, mutation_scale<span class="op">=</span><span class="dv">11</span>))</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-nn-architectures" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-architectures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="nn_example_files/figure-html/fig-nn-architectures-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-architectures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Four volatility-forecasting specifications. The HAR-FNN uses the same three HAR components as HAR-OLS: yesterday’s realized variance, the trailing 5-day average, and the trailing 21-day average (in logs for the log target, in levels for the level target). The direct FNN flattens the 22-day window. The Simple RNN and LSTM process a 756-day ordered sequence; the last four steps are shown.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The dense hidden layers use softplus activations, as in the <a href="./feed_forward_nns.html">feed-forward chapter</a>. The recurrent layers use <span class="math inline">\tanh</span> updates, as in the <a href="./recurrent_neural_networks.html">RNN chapter</a> and <a href="./lstm_neural_networks.html">LSTM chapter</a>. The input shapes are <code>(3,)</code> for HAR-FNN, <code>(22,)</code> for the direct FNN, and <code>(756, 1)</code> for the recurrent models.</p>
<p>Both recurrent models use <code>stateful=False</code> and receive no initial state. The hidden state starts at zero for each window, as does the LSTM cell state. Estimated weights persist between daily forecasts within a year; states do not pass from one input window to the next. The forward state and gradient paths are therefore limited to 756 steps. A long input window makes distant observations available without ensuring that their information survives the recurrent updates.</p>
<p>All neural models minimize mean squared error (MSE) with Adam. We apply global gradient-norm clipping at 1.0 to the stacked raw gradient before Adam’s update, following the <a href="./recurrent_neural_networks.html">RNN chapter’s clipping discussion</a>. Clipping limits large raw gradients; it neither restores vanished gradients nor directly bounds the final Adam parameter step. No weight decay or dropout is used in this illustration.</p>
<div id="c8196177" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_network(model_name, input_shape, width, learning_rate):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="im">import</span> keras</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> keras <span class="im">import</span> layers</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    keras.backend.clear_session()</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    keras.utils.set_random_seed(SEED)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> model_name <span class="kw">in</span> (<span class="st">"FNN"</span>, <span class="st">"HAR-FNN"</span>):</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        hidden <span class="op">=</span> layers.Dense(width, activation<span class="op">=</span><span class="st">"softplus"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> model_name <span class="op">==</span> <span class="st">"Simple RNN"</span>:</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        hidden <span class="op">=</span> layers.SimpleRNN(width, activation<span class="op">=</span><span class="st">"tanh"</span>, stateful<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> model_name <span class="op">==</span> <span class="st">"LSTM"</span>:</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        hidden <span class="op">=</span> layers.LSTM(width, activation<span class="op">=</span><span class="st">"tanh"</span>, stateful<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(model_name)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> keras.Sequential([keras.Input(shape<span class="op">=</span>input_shape), hidden, layers.Dense(<span class="dv">1</span>)])</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Clip the stacked raw gradient, following the recurrent-network chapter.</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">compile</span>(loss<span class="op">=</span><span class="st">"mse"</span>, optimizer<span class="op">=</span>keras.optimizers.Adam(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>        learning_rate<span class="op">=</span>learning_rate, global_clipnorm<span class="op">=</span><span class="fl">1.0</span>))</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Training-only normalization.</strong> For raw log inputs, every lag and the target use the current estimation sample’s target mean and standard deviation. For raw level inputs, each lag coordinate is standardized using its own moments across the current training examples. The HAR components are standardized column by column in either pipeline, and the neural target uses its own training mean and standard deviation. At an annual refit, we reestimate these constants from the new sliding sample, then hold them fixed during that year’s forecasting. HAR-OLS is fit directly on the unstandardized HAR inputs; with an intercept, nonsingular affine standardization would leave its fitted predictions unchanged.</p>
<p>The normalization rule differs between the log and level pipelines. Thus their empirical comparison changes the complete training procedure, rather than identifying the effect of the target transform alone. The <a href="./cross_validation.html#sec-cv-leakage">cross-validation chapter</a> explains why fitting preprocessing on future observations would invalidate the forecast exercise.</p>
<div id="5ca1f534" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> arrays_for(panel, model_name, target):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    prefix <span class="op">=</span> <span class="st">"har"</span> <span class="cf">if</span> model_name.startswith(<span class="st">"HAR"</span>) <span class="cf">else</span> <span class="st">"lag"</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    suffix <span class="op">=</span> <span class="st">"log"</span> <span class="cf">if</span> target <span class="op">==</span> <span class="st">"log(rv)"</span> <span class="cf">else</span> <span class="st">"rv"</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> panel[<span class="ss">f"</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss">_</span><span class="sc">{</span>suffix<span class="sc">}</span><span class="ss">"</span>]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> model_name <span class="op">==</span> <span class="st">"FNN"</span>:</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        X <span class="op">=</span> X[:, <span class="op">-</span>FNN_INPUT_DAYS:]</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X, panel[<span class="ss">f"y_</span><span class="sc">{</span>suffix<span class="sc">}</span><span class="ss">"</span>]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_scaler(X, y, model_name, target):</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Fit only on the current estimation examples, including their inputs."""</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    y_center, y_scale <span class="op">=</span> <span class="bu">float</span>(y.mean()), <span class="bu">float</span>(y.std())</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> y_scale <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The estimation targets have zero variance."</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> model_name.startswith(<span class="st">"HAR"</span>) <span class="kw">and</span> target <span class="op">==</span> <span class="st">"log(rv)"</span>:</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        x_center, x_scale <span class="op">=</span> y_center, y_scale</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        x_center, x_scale <span class="op">=</span> X.mean(axis<span class="op">=</span><span class="dv">0</span>), X.std(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        x_scale <span class="op">=</span> np.where(x_scale <span class="op">&gt;</span> <span class="dv">0</span>, x_scale, <span class="fl">1.0</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"x_center"</span>: x_center, <span class="st">"x_scale"</span>: x_scale,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>            <span class="st">"y_center"</span>: y_center, <span class="st">"y_scale"</span>: y_scale}</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> transform(X, y, scaler, model_name):</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    X_scaled <span class="op">=</span> ((X<span class="op">-</span>scaler[<span class="st">"x_center"</span>])<span class="op">/</span>scaler[<span class="st">"x_scale"</span>]).astype(<span class="st">"float32"</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    y_scaled <span class="op">=</span> ((y<span class="op">-</span>scaler[<span class="st">"y_center"</span>])<span class="op">/</span>scaler[<span class="st">"y_scale"</span>]).astype(<span class="st">"float32"</span>)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> model_name <span class="kw">in</span> (<span class="st">"Simple RNN"</span>, <span class="st">"LSTM"</span>):</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>        X_scaled <span class="op">=</span> X_scaled[..., np.newaxis]</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X_scaled, y_scaled</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="validation-and-tuning" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="validation-and-tuning"><span class="header-section-number">8.5</span> Validation and Tuning</h2>
<p>The same input and scaling rules now apply to every candidate configuration. We tune each neural architecture separately for each target using 20 Optuna trials. Optuna is a hyperparameter-search library; its tree-structured Parzen estimator (TPE) selects configurations using earlier validation results. The <a href="./hpo.html">hyperparameter-optimization chapter</a> develops this search strategy. Here the search ranges are width 16–96 in steps of 4, batch size 16–64 in steps of 4, and learning rate <span class="math inline">10^{-4}</span>–<span class="math inline">10^{-3}</span> on a logarithmic scale.</p>
<p>For each candidate, we fit on the 756 training examples available at the start of 2022, run 30 training epochs, and evaluate each epoch’s fitted weights on all 251 validation targets in 2022. Each epoch is evaluated with one set of weights held fixed across that year; the daily inputs still update using observations available at each forecast origin. We select the configuration and epoch count with the lowest validation MSE, then reuse that epoch count at the start-of-year refits for 2023 and 2024. Validation and testing thus share the same annual fitting schedule. One validation year remains a limited basis for tuning: it does not measure sensitivity to choosing a different validation year, and the selected epoch count need not be optimal for each later training sample.</p>
<p>We use a fixed neural initialization seed of 0 and an Optuna sampler seed of 1. Every model has the same nominal trial and epoch budget, but the search spaces differ in parameter count and optimization difficulty. Each configuration is assessed with one initialization. The comparison therefore does not measure variability across seeds or establish that every architecture has been equally well optimized.</p>
<p>The time-series restrictions concern when outcomes become available and which examples are used to fit, tune, and evaluate the model. For these self-contained, stateless windows, shuffling the already constructed training examples would not introduce future observations. We set <code>shuffle=False</code> to use chronologically ordered mini-batches, a batch-composition choice. The <a href="./optimization.html#sec-optim-mini-batch">optimization chapter</a> describes mini-batch sampling and reshuffling. We never randomize the train-validation-test split.</p>
<div id="1feb36da" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> tune_network(panel, model_name, target, trials<span class="op">=</span>N_TRIALS, max_epochs<span class="op">=</span>MAX_EPOCHS):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="im">import</span> optuna</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    optuna.logging.set_verbosity(optuna.logging.WARNING)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    dates <span class="op">=</span> panel[<span class="st">"dates"</span>]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    tr <span class="op">=</span> estimation_indices(dates, VALIDATION_START)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    va <span class="op">=</span> np.flatnonzero(np.asarray((dates <span class="op">&gt;=</span> VALIDATION_START) <span class="op">&amp;</span> (dates <span class="op">&lt;</span> TEST_START)))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    X, y <span class="op">=</span> arrays_for(panel, model_name, target)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    scaler <span class="op">=</span> fit_scaler(X[tr], y[tr], model_name, target)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    X_tr, y_tr <span class="op">=</span> transform(X[tr], y[tr], scaler, model_name)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    X_va, y_va <span class="op">=</span> transform(X[va], y[va], scaler, model_name)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    trial_rows <span class="op">=</span> []</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> objective(trial):</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        start <span class="op">=</span> time.monotonic()</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        params <span class="op">=</span> {</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">"learning_rate"</span>: trial.suggest_float(<span class="st">"learning_rate"</span>, <span class="fl">1e-4</span>, <span class="fl">1e-3</span>, log<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">"batch_size"</span>: trial.suggest_int(<span class="st">"batch_size"</span>, <span class="dv">16</span>, <span class="dv">64</span>, step<span class="op">=</span><span class="dv">4</span>),</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">"width"</span>: trial.suggest_int(<span class="st">"width"</span>, <span class="dv">16</span>, <span class="dv">96</span>, step<span class="op">=</span><span class="dv">4</span>),</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        model <span class="op">=</span> make_network(model_name, X_tr.shape[<span class="dv">1</span>:], params[<span class="st">"width"</span>], params[<span class="st">"learning_rate"</span>])</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>        history <span class="op">=</span> model.fit(X_tr, y_tr, validation_data<span class="op">=</span>(X_va, y_va),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>                            epochs<span class="op">=</span>max_epochs, batch_size<span class="op">=</span>params[<span class="st">"batch_size"</span>],</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>                            shuffle<span class="op">=</span><span class="va">False</span>, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>        losses <span class="op">=</span> np.asarray(history.history[<span class="st">"val_loss"</span>], dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> np.isfinite(losses).<span class="bu">all</span>():</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">FloatingPointError</span>(<span class="st">"Nonfinite validation loss; investigate before using results."</span>)</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>        best_epoch <span class="op">=</span> <span class="bu">int</span>(np.argmin(losses))<span class="op">+</span><span class="dv">1</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>        best_loss <span class="op">=</span> <span class="bu">float</span>(losses[best_epoch<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>        trial.set_user_attr(<span class="st">"best_epoch"</span>, best_epoch)</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>        trial.set_user_attr(<span class="st">"parameters"</span>, model.count_params())</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>        row <span class="op">=</span> <span class="bu">dict</span>(trial<span class="op">=</span>trial.number, <span class="op">**</span>params, best_epoch<span class="op">=</span>best_epoch,</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>                   validation_loss<span class="op">=</span>best_loss, parameters<span class="op">=</span>model.count_params(),</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>                   seconds<span class="op">=</span><span class="bu">round</span>(time.monotonic()<span class="op">-</span>start, <span class="dv">2</span>))</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>        trial_rows.append(row)</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(json.dumps({<span class="st">"stage"</span>: <span class="st">"trial"</span>, <span class="st">"model"</span>: model_name, <span class="st">"target"</span>: target, <span class="op">**</span>row}), flush<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> best_loss</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    study <span class="op">=</span> optuna.create_study(direction<span class="op">=</span><span class="st">"minimize"</span>, sampler<span class="op">=</span>optuna.samplers.TPESampler(seed<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>    study.optimize(objective, n_trials<span class="op">=</span>trials)</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>    best <span class="op">=</span> <span class="bu">dict</span>(study.best_params, <span class="op">**</span>study.best_trial.user_attrs,</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>                validation_loss<span class="op">=</span><span class="bu">float</span>(study.best_value))</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> best, trial_rows</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The validation-selected configurations are reported below. Validation losses are comparable within a target group; between groups, the standardized targets differ. Parameter counts include the hidden or recurrent layer and the final linear output. HAR-OLS has no neural hyperparameters and is fit by OLS at each annual refit.</p>
<div id="de3e4286" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Target fit</th>
<th>Model</th>
<th style="text-align: right;">Width</th>
<th style="text-align: right;">Parameters</th>
<th style="text-align: right;">Learning rate</th>
<th style="text-align: right;">Batch size</th>
<th style="text-align: right;">Epochs</th>
<th style="text-align: right;">Validation loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>log(rv)</code></td>
<td>HAR-FNN</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">0.000987</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.2380</td>
</tr>
<tr class="even">
<td><code>log(rv)</code></td>
<td>FNN</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">1,729</td>
<td style="text-align: right;">0.000930</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.2345</td>
</tr>
<tr class="odd">
<td><code>log(rv)</code></td>
<td>Simple RNN</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">9,505</td>
<td style="text-align: right;">0.000461</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.2336</td>
</tr>
<tr class="even">
<td><code>log(rv)</code></td>
<td>LSTM</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">26,321</td>
<td style="text-align: right;">0.000653</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.2260</td>
</tr>
<tr class="odd">
<td><code>rv</code></td>
<td>HAR-FNN</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">0.000671</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.0913</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>FNN</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">1,345</td>
<td style="text-align: right;">0.000513</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0.0905</td>
</tr>
<tr class="odd">
<td><code>rv</code></td>
<td>Simple RNN</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">5,401</td>
<td style="text-align: right;">0.000930</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.0873</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>LSTM</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">21,385</td>
<td style="text-align: right;">0.000930</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.0936</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="annual-forecasting-and-replication" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="annual-forecasting-and-replication"><span class="header-section-number">8.6</span> Annual Forecasting and Replication</h2>
<p>After validation, we freeze the selected hyperparameters and apply the annual sliding-window rule. At the first test origin in each year, we select the most recent 756 observed training targets, reestimate the scalers, and fit each selected network from a fresh initialization. We then forecast daily with those weights until the next refit. The first test fit occurs before the target on 2023-01-03; the next occurs before the target on 2024-01-02. No test loss is used to alter the hyperparameters or refitting rule.</p>
<p>The implementation below reconstructs the sequential forecasts retrospectively. It can predict a whole year in one batch because each row uses only its own past observations and the weights stay fixed within that year. It stores a separate forecast for each target date. Its scoring helper also counts nonpositive variance forecasts; log-scale losses and the volatility loss introduced in the next section require positive predictions and are returned as undefined if that condition fails. Squared and absolute errors on the RV scale remain well defined.</p>
<div id="6750843c" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score_forecasts(rv_true, rv_hat):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    rv_true, rv_hat <span class="op">=</span> np.asarray(rv_true), np.asarray(rv_hat)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> np.isfinite(rv_hat).<span class="bu">all</span>():</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">FloatingPointError</span>(<span class="st">"Nonfinite forecast."</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    nonpositive <span class="op">=</span> <span class="bu">int</span>(np.count_nonzero(rv_hat <span class="op">&lt;=</span> <span class="dv">0</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nonpositive:</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        rmse_log <span class="op">=</span> mae_log <span class="op">=</span> qlike <span class="op">=</span> <span class="va">None</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        log_error <span class="op">=</span> np.log(rv_hat)<span class="op">-</span>np.log(rv_true)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        ratio <span class="op">=</span> rv_true<span class="op">/</span>rv_hat</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        rmse_log <span class="op">=</span> <span class="bu">float</span>(np.sqrt(np.mean(log_error<span class="op">**</span><span class="dv">2</span>)))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        mae_log <span class="op">=</span> <span class="bu">float</span>(np.mean(np.<span class="bu">abs</span>(log_error)))</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        qlike <span class="op">=</span> <span class="bu">float</span>(np.mean(ratio<span class="op">-</span>np.log(ratio)<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"rmse_log_rv"</span>: rmse_log, <span class="st">"mae_log_rv"</span>: mae_log,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>            <span class="st">"rmse_rv"</span>: <span class="bu">float</span>(np.sqrt(np.mean((rv_hat<span class="op">-</span>rv_true)<span class="op">**</span><span class="dv">2</span>))),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">"mae_rv"</span>: <span class="bu">float</span>(np.mean(np.<span class="bu">abs</span>(rv_hat<span class="op">-</span>rv_true))), <span class="st">"qlike"</span>: qlike,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">"nonpositive_rv_forecasts"</span>: nonpositive}</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> annual_forecasts(panel, model_name, target, params):</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Refit once per test year on a sliding window; freeze within the year."""</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    dates <span class="op">=</span> panel[<span class="st">"dates"</span>]</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    X, y <span class="op">=</span> arrays_for(panel, model_name, target)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    predictions, records <span class="op">=</span> [], []</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> year <span class="kw">in</span> <span class="bu">sorted</span>(dates.loc[dates <span class="op">&gt;=</span> TEST_START].dt.year.unique()):</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        te <span class="op">=</span> np.flatnonzero(np.asarray((dates <span class="op">&gt;=</span> TEST_START) <span class="op">&amp;</span> (dates.dt.year <span class="op">==</span> year)))</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>        first_date <span class="op">=</span> dates.iloc[te[<span class="dv">0</span>]]</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        tr <span class="op">=</span> estimation_indices(dates, first_date)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> model_name <span class="op">==</span> <span class="st">"HAR-OLS"</span>:</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>            model <span class="op">=</span> LinearRegression().fit(X[tr], y[tr])</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>            target_hat <span class="op">=</span> model.predict(X[te])</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>            scaler <span class="op">=</span> fit_scaler(X[tr], y[tr], model_name, target)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>            X_tr, y_tr <span class="op">=</span> transform(X[tr], y[tr], scaler, model_name)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>            X_te, _ <span class="op">=</span> transform(X[te], y[te], scaler, model_name)</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>            model <span class="op">=</span> make_network(model_name, X_tr.shape[<span class="dv">1</span>:], params[<span class="st">"width"</span>], params[<span class="st">"learning_rate"</span>])</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>            model.fit(X_tr, y_tr, epochs<span class="op">=</span>params[<span class="st">"best_epoch"</span>], batch_size<span class="op">=</span>params[<span class="st">"batch_size"</span>],</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>                      shuffle<span class="op">=</span><span class="va">False</span>, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>            target_hat <span class="op">=</span> model.predict(X_te, verbose<span class="op">=</span><span class="dv">0</span>).ravel()<span class="op">*</span>scaler[<span class="st">"y_scale"</span>]<span class="op">+</span>scaler[<span class="st">"y_center"</span>]</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>        rv_hat <span class="op">=</span> np.exp(target_hat) <span class="cf">if</span> target <span class="op">==</span> <span class="st">"log(rv)"</span> <span class="cf">else</span> target_hat</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> np.errstate(invalid<span class="op">=</span><span class="st">"ignore"</span>, divide<span class="op">=</span><span class="st">"ignore"</span>):</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>            z_hat <span class="op">=</span> np.where(rv_hat <span class="op">&gt;</span> <span class="dv">0</span>, np.log(rv_hat), np.nan)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j, index <span class="kw">in</span> <span class="bu">enumerate</span>(te):</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>            predictions.append({<span class="st">"date"</span>: dates.iloc[index].strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>),</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"rv"</span>: <span class="bu">float</span>(panel[<span class="st">"y_rv"</span>][index]),</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"forecast_rv"</span>: <span class="bu">float</span>(rv_hat[j]),</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"forecast_log_rv"</span>: <span class="bu">float</span>(z_hat[j]) <span class="cf">if</span> np.isfinite(z_hat[j]) <span class="cf">else</span> <span class="va">None</span>})</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>        records.append({<span class="st">"year"</span>: <span class="bu">int</span>(year), <span class="st">"estimation_examples"</span>: <span class="bu">len</span>(tr),</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"estimation_start"</span>: dates.iloc[tr[<span class="dv">0</span>]].strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>),</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"estimation_end"</span>: dates.iloc[tr[<span class="op">-</span><span class="dv">1</span>]].strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>),</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"first_test_target"</span>: first_date.strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>),</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"last_test_target"</span>: dates.iloc[te[<span class="op">-</span><span class="dv">1</span>]].strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>),</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"forecasts"</span>: <span class="bu">len</span>(te)})</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>    frame <span class="op">=</span> pd.DataFrame(predictions)</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> score_forecasts(frame.rv, frame.forecast_rv), predictions, records</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>All ten model-target combinations are reproduced with the commands below, using the local SPY file documented in <a href="./datasets.html#sec-spy-taq-realized">the dataset appendix</a>. The Python dependencies are pinned in <a href="requirements.txt">requirements.txt</a>. Model fitting is not repeated during chapter rendering. The first command saves the selected configurations, trial histories, annual estimation dates, metrics, and daily forecasts in the private data directory. The second verifies the data and pipeline hashes, recomputes metrics from those forecasts, and updates the public aggregate results and figure together.</p>
<pre class="{bash}"><code>#| eval: false

python nn_example_pipeline.py --all --jobs 4
python nn_example_outputs.py
quarto render nn_example.qmd</code></pre>
<p>The <a href="results/nn-example-756.json">aggregate results file</a> records the settings, package versions, selected configurations, annual estimation dates, and metrics. The <a href="nn_example_outputs.py">output helper</a> builds both displayed tables from this file and the performance figure from the private forecasts. The data directory remains private; the aggregate file and figure accompany the chapter. The fitting command can resume completed model runs, so use a fresh output directory after a data, code, or environment change rather than mixing old and new results.</p>
</section>
<section id="results" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="results"><span class="header-section-number">8.7</span> Results</h2>
<p>The following results use the common 502 test targets and the annual estimation schedule above. The log-target and level-target rows differ in their target and normalization rules, while preserving the calendar boundaries, input construction, tuning budget, and annual refit schedule.</p>
<p>The columns answer different questions. Write <span class="math inline">\mathcal T_{\mathrm{test}}</span> for the set of <span class="math inline">N_{\mathrm{test}}=502</span> test target dates and <span class="math inline">\mathcal F_{t-1}</span> for the information available after observing day <span class="math inline">t-1</span>. Here <span class="math inline">\text{RMSE}=\sqrt{\frac{1}{N_{\text{test}}}\sum_{t\in\mathcal T_{\mathrm{test}}}(\hat z_t-z_t)^2}</span> aggregates the squared forecast errors over the <span class="math inline">N_{\text{test}}</span> test origins; <span class="math inline">\hat z_t</span> denotes the forecast of <span class="math inline">z_t</span> formed at <span class="math inline">t-1</span>; we drop the two-index subscript of <span class="math inline">\hat z_{t+1\mid t}</span> in this section to keep the formulas readable. RMSE on <span class="math inline">\log(RV)</span> evaluates forecasts on the scale used by the log-target models and is the main comparison criterion here. For level-target models, the log-scale metrics require the level forecast <span class="math inline">\widehat{RV}_t</span> to be strictly positive so that its logarithm can be taken; they are reported as undefined for any model that violates this. RMSE on <span class="math inline">RV</span> evaluates the implied variance forecasts after exponentiating log-target forecasts. This back-transformation carries a subtlety: if <span class="math inline">\hat z_t</span> targets the conditional mean <span class="math inline">\mu_t:=\mathbb{E}[Z_t\mid\mathcal F_{t-1}]</span> of the random log target <span class="math inline">Z_t=\log RV_t</span>, then <span class="math inline">\exp(\hat z_t)</span> is a conditional geometric-mean forecast. It equals the conditional median only under an additional condition that makes the conditional mean and median of <span class="math inline">Z_t</span> coincide, such as conditional symmetry. Writing <span class="math inline">Z_t=\mu_t+\varepsilon_t</span> with <span class="math inline">\mathbb{E}[\varepsilon_t\mid\mathcal F_{t-1}]=0</span>, the conditional mean on the level scale is </p>
<div class="display-math-block">
<p><span class="math display">
\mathbb{E}[RV_t\mid\mathcal F_{t-1}]
=
\exp(\mu_t)\,\mathbb{E}[\exp(\varepsilon_t)\mid\mathcal F_{t-1}].
</span></p>
</div>
<p> The familiar correction <span class="math inline">\exp(\mu_t+\sigma_t^2/2)</span> follows only when the log-scale error is conditionally Gaussian with variance <span class="math inline">\sigma_t^2</span>; in general the smearing factor depends on its full conditional distribution. Transforming a complete predictive density is a separate change-of-variables step, discussed in the <a href="./distributions_via_nns.html">distributional networks chapter</a>. Because RV-scale squared-error and QLIKE losses are minimized by conditional-mean forecasts, the uncorrected exponentiated log forecasts do not generally target the same level-scale functional as the level-target models. The log-scale RMSE column, the main criterion here, is unaffected. QLIKE (quasi-likelihood) is the volatility loss </p>
<div class="display-math-block">
<p><span class="math display">
\frac{1}{N_{\text{test}}}\sum_{t\in\mathcal T_{\mathrm{test}}}
\left(
\frac{RV_t}{\widehat{RV}_t}
- \log\frac{RV_t}{\widehat{RV}_t}
-1
\right),
</span></p>
</div>
<p> which is defined only for positive variance forecasts; with the same indexing convention as above, <span class="math inline">\widehat{RV}_t</span> is the forecast of <span class="math inline">RV_t</span> formed at <span class="math inline">t-1</span>. All three measures are losses, so smaller values are better. If a model produces a nonpositive variance forecast, the two losses that require positivity, log-RV RMSE and QLIKE, are reported as undefined rather than rescued by clipping. The table includes the number of nonpositive forecasts; the aggregate results file also records mean absolute error (MAE) on both scales.</p>
<div id="27866315" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>Target fit</th>
<th>Model</th>
<th style="text-align: right;">RMSE log RV</th>
<th style="text-align: right;">RMSE RV</th>
<th style="text-align: right;">QLIKE</th>
<th style="text-align: right;">Nonpositive</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>log(rv)</code></td>
<td>HAR-OLS</td>
<td style="text-align: right;">0.5784</td>
<td style="text-align: right;">0.3191</td>
<td style="text-align: right;">0.1880</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><code>log(rv)</code></td>
<td>HAR-FNN</td>
<td style="text-align: right;">0.5836</td>
<td style="text-align: right;">0.3203</td>
<td style="text-align: right;">0.1918</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><code>log(rv)</code></td>
<td>FNN</td>
<td style="text-align: right;">0.6257</td>
<td style="text-align: right;">0.3212</td>
<td style="text-align: right;">0.1828</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><code>log(rv)</code></td>
<td>Simple RNN</td>
<td style="text-align: right;">0.5866</td>
<td style="text-align: right;">0.3257</td>
<td style="text-align: right;">0.1968</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><code>log(rv)</code></td>
<td>LSTM</td>
<td style="text-align: right;">0.5772</td>
<td style="text-align: right;">0.3216</td>
<td style="text-align: right;">0.1956</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>HAR-OLS</td>
<td style="text-align: right;">0.7129</td>
<td style="text-align: right;">0.3384</td>
<td style="text-align: right;">0.2048</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><code>rv</code></td>
<td>HAR-FNN</td>
<td style="text-align: right;">0.6201</td>
<td style="text-align: right;">0.3211</td>
<td style="text-align: right;">0.1777</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>FNN</td>
<td style="text-align: right;">0.6223</td>
<td style="text-align: right;">0.3217</td>
<td style="text-align: right;">0.1843</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td><code>rv</code></td>
<td>Simple RNN</td>
<td style="text-align: right;">0.9063</td>
<td style="text-align: right;">0.4231</td>
<td style="text-align: right;">0.2938</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><code>rv</code></td>
<td>LSTM</td>
<td style="text-align: right;">0.6598</td>
<td style="text-align: right;">0.3257</td>
<td style="text-align: right;">0.1964</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The two HAR specifications show that adding nonlinear layers does not uniformly improve the benchmark. With a log target, HAR-OLS has lower loss than HAR-FNN on all three displayed criteria (log-RV RMSE 0.5784 versus 0.5836). With a level target, HAR-FNN improves on HAR-OLS on all three criteria. These comparisons concern the selected complete procedures, not an isolated effect of nonlinearity.</p>
<p>All ten specifications produce positive variance forecasts in this run, so every displayed loss is defined. The linear output layer does not enforce positivity in the level-target models, however. The nonpositive count makes that restriction visible: a positive count renders log-scale RMSE and QLIKE undefined for that row. Clipping to a small arbitrary constant would change both the forecast and its score. A positive output transformation is an alternative specification, which should be chosen before test evaluation.</p>
<p><a href="#fig-nn-performance" class="quarto-xref">Figure&nbsp;8.3</a> displays the forecasts and compares the two pipelines on the chapter’s main log-scale criterion.</p>
<div id="fig-nn-performance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/nn-example-performance.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: Empirical output for the annually refitted SPY experiment, with 22 daily inputs for the direct FNN and 756 for the recurrent models. Top: observed log realized variance and daily forecasts from all five log-target models over the common test period; the dotted line marks the 2024 refit. Bottom: test RMSE on log RV, with blue bars for log-target fits and orange bars for level-target fits. The vertical axis starts at zero; an undefined marker replaces a score whenever a model produces a nonpositive variance forecast.
</figcaption>
</figure>
</div>
<p>Among the individual log-target models, LSTM has the lowest test log-RV RMSE (0.5772), with HAR-OLS close behind (0.5784). Their unrounded gap is about 0.0011 log-RV units, or 0.19% of the HAR-OLS RMSE. HAR-FNN follows at 0.5836, the Simple RNN at 0.5866, and the direct FNN at 0.6257. The parsimonious HAR-OLS benchmark therefore remains competitive with the long recurrent input history in this run.</p>
<p>The log-target pipeline has lower log-RV RMSE for both HAR specifications, the Simple RNN, and LSTM. The direct FNN instead slightly favors the level-target pipeline (0.6223 versus 0.6257). Among these individual specifications, secondary criteria give different rankings: log-target HAR-OLS has the lowest RV-scale RMSE (0.3191), while level-target HAR-FNN has the lowest QLIKE (0.1777). Because normalization also changes between target pipelines, these results do not isolate the effect of taking logs of the target.</p>
<p>The common test period makes the forecast errors comparable, but the information sets still differ. The direct FNN sees 22 daily inputs, while the recurrent models see 756. The figure therefore cannot identify the benefit of recurrence holding the input history fixed. Nor can a result from one initialization establish that an architecture is generally better optimized or more accurate.</p>
<p>Numerical rankings do not establish statistically significant performance differences. Let <span class="math inline">\mathcal T_{\mathrm{test}}</span> be the set of 502 test target dates and <span class="math inline">\delta_t</span> the difference between two models’ squared forecast errors at date <span class="math inline">t</span>. A <span class="citation" data-cites="DieboldMariano1995">Diebold and Mariano (<a href="#ref-DieboldMariano1995" role="doc-biblioref">1995</a>)</span> comparison relates the mean differential <span class="math inline">\bar\delta=N_{\mathrm{test}}^{-1}\sum_{t\in\mathcal T_{\mathrm{test}}}\delta_t</span> to its standard error, <span class="math inline">(\hat\omega^2/N_{\mathrm{test}})^{1/2}</span>, where <span class="math inline">\hat\omega^2</span> is a heteroskedasticity- and autocorrelation-consistent (HAC) estimate of the differential’s long-run variance. The relevant uncertainty is the standard error of the <em>mean</em>, not the dispersion of individual daily differences. Exercise 4.3 in the <a href="./evaluating_distributions.html">predictive-distributions chapter</a> develops the corresponding construction for score differentials. We do not run this test here, and the results do not establish equivalence between close performers.</p>
<p>QLIKE is the <span class="citation" data-cites="Patton2011">Patton (<a href="#ref-Patton2011" role="doc-biblioref">2011</a>)</span> quasi-likelihood loss for volatility. Its robustness result concerns rankings by <em>expected</em> loss: under the required conditional-unbiasedness condition for the variance proxy, replacing latent variance by the proxy preserves the expected-loss ranking. Sampling variation can still reverse finite-sample rankings. QLIKE is scale-invariant because it depends only on the ratio <span class="math inline">RV_t/\widehat{RV}_t</span>; it penalizes underprediction more heavily than overprediction. Thus QLIKE and log-RV RMSE can favor different forecasts.</p>
<p>HAR remains a strong benchmark in this comparison. A longer raw history, nonlinear mapping, or gated recurrent state does not by itself guarantee improved forecasts, and the ranking cannot be assigned to memory or nonlinearity alone.</p>
</section>
<section id="summary" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="summary"><span class="header-section-number">8.8</span> Summary</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Log-target LSTM has the lowest test log-RV RMSE among the individual models, only slightly below HAR-OLS.</li>
<li>Input history differs across models: 22 daily observations for the direct FNN, 756 for the recurrent models, and three HAR summaries.</li>
<li>Annual refits keep 756 training examples, while the neural hyperparameters stay fixed.</li>
<li>Empirical rankings depend on the loss and complete forecasting procedure; numerical gaps alone do not establish statistical significance.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Common Pitfalls
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Allowing the annual estimation sample to expand changes the intended forecasting rule.</li>
<li>Attributing performance differences to recurrence alone ignores the different input histories across models.</li>
<li>Clipping negative variance forecasts to an arbitrary positive constant changes the submitted forecast and its score.</li>
<li>Choosing hyperparameters after inspecting test performance turns the test period into additional validation data.</li>
</ul>
</div>
</div>
</section>
<section id="references" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="references"><span class="header-section-number">8.9</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-AndersenBollerslevDieboldLabys2003" class="csl-entry" role="listitem">
Andersen, Torben G., Tim Bollerslev, Francis X. Diebold, and Paul Labys. 2003. <span>“Modeling and Forecasting Realized Volatility.”</span> <em>Econometrica</em> 71 (2): 579–625. <a href="https://doi.org/10.1111/1468-0262.00418">https://doi.org/10.1111/1468-0262.00418</a>.
</div>
<div id="ref-CorsiHAR2009" class="csl-entry" role="listitem">
Corsi, Fulvio. 2009. <span>“A Simple Approximate Long-Memory Model of Realized Volatility.”</span> <em>Journal of Financial Econometrics</em> 7 (2): 174–96. <a href="https://doi.org/10.1093/jjfinec/nbp001">https://doi.org/10.1093/jjfinec/nbp001</a>.
</div>
<div id="ref-DieboldMariano1995" class="csl-entry" role="listitem">
Diebold, Francis X, and Robert S Mariano. 1995. <span>“<span class="nocase">Comparing predictive accuracy</span>.”</span> <em>Journal of Business and Economic Statistics</em> 13 (3): 253–63. <a href="https://doi.org/10.1080/07350015.1995.10524599">https://doi.org/10.1080/07350015.1995.10524599</a>.
</div>
<div id="ref-Patton2011" class="csl-entry" role="listitem">
Patton, Andrew J. 2011. <span>“Volatility Forecast Comparison Using Imperfect Volatility Proxies.”</span> <em>Journal of Econometrics</em> 160 (1): 246–56. <a href="https://doi.org/10.1016/j.jeconom.2010.03.034">https://doi.org/10.1016/j.jeconom.2010.03.034</a>.
</div>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Under standard semimartingale conditions, realized variance consistently estimates quadratic variation. In a continuous-path model without price jumps, quadratic variation equals integrated variance; with jumps, it also contains the sum of squared jump sizes.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mlmetrics\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./lstm_neural_networks.html" class="pagination-link" aria-label="7. LSTM Networks">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">7. LSTM Networks</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./distributions_via_nns.html" class="pagination-link" aria-label="9. Distribution Modeling with Neural Networks">
        <span class="nav-page-text">9. Distribution Modeling with Neural Networks</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2026, Onno Kleen</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>